Metadata/objects/Batch_Jobs__c.object
<CustomObject>
    <description>This holds the records for batch process of MRR and Renew Orders</description>
    <fields>
        <fullName>Completed_Date_and_Time__c</fullName>
        <label>Completed Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_and_Time__c</fullName>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed with errors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>MRR Calculation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Renewals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SteelBrick Batch Jobs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Credit_Line__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Credit_Note__c</fullName>
        <label>Credit Note</label>
        <referenceTo>Credit_Note__c</referenceTo>
        <relationshipLabel>Credit Lines</relationshipLabel>
        <relationshipName>Credit_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_Status__c</fullName>
        <label>Revenue Recognition Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Posted</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Line</label>
    <nameField>
        <displayFormat>CLINE--{0000}</displayFormat>
        <label>Credit Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Credit_Note__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Credit_Note_Status__c</fullName>
        <label>Credit Note Status</label>
        <picklist>
            <picklistValues>
                <fullName>Posted</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/BatchProcessRevenueForCreditNotes.cls
/*
      this class to used process the revenue transaction for the invoice lines
    */

    global with sharing class BatchProcessRevenueForCreditNotes implements Database.Batchable<sObject>, Database.Stateful,Database.AllowsCallouts{

        global list<id> listOfCreditNoteIds = new list<id>();
        global Batch_Jobs__c batchJobsObj;
        global String errorLog = '';
        list<id> listOfCreditLineIds = new list<id>();
        
        global BatchProcessRevenueForCreditNotes(list<Id> creditNoteIds) {
            this.listOfCreditNoteIds = creditNoteIds;
        }
        
        global Database.QueryLocator start(Database.BatchableContext BC){
           batchJobsObj = new Batch_Jobs__c(name = DateTime.now().format('yyyy-MM-dd'),Start_Date_and_Time__c = system.now(),Status__c = 'Started',Type__c = 'Batch Process Revenue For CreditNotes');
           insert batchJobsObj;
            
           if(listOfCreditNoteIds != null){ 
                return Database.getQueryLocator([select Name from Credit_Line__c where Credit_Note__c IN: listOfCreditNoteIds AND Credit_Note__r.Credit_Note_Status__c =: CommonUtilClass.STATUS_POSTED]);  
            } else {
                return Database.getQueryLocator([select Name from Credit_Line__c where Revenue_Recognition_Status__c =: CommonUtilClass.STATUS_QUEUED AND Credit_Note__r.Credit_Note_Status__c =: CommonUtilClass.STATUS_POSTED]);
            }
        }
        
         global void execute(Database.BatchableContext BC, list<Credit_Line__c> listOfCreditLines) {
           try {
            // add the all ids to list to process revenue after completion of this batch
            Set<Id> setOfRecordIds = (new Map<Id,Credit_Line__c>(listOfCreditLines)).keySet();
            listOfCreditLineIds = new list<id>();
            listOfCreditLineIds.addall(setOfRecordIds);
            // call the method to create revenue transactions
            RevenueTransactionsForCreditUtilClass.createRevenueTransactionForCreditLine(listOfCreditLineIds);
           
           }catch(Exception ex) {
            errorLog += system.Label.ExceptionMessage + ex.getTypeName() + ':'+ex.getMessage() + ':'  + ex.getLineNumber() + ':' + ex.getStackTraceString() + '\n';
           } 
         }
         
         global void finish(Database.BatchableContext BC) {
            
            batchJobsObj.Completed_Date_and_Time__c = system.now();
            batchJobsObj.Status__c = CommonUtilClass.STATUS_COMPLETED;
            if(errorLog != ''){
                batchJobsObj.Status__c = CommonUtilClass.STATUS_COMPLETED_WITH_ERRORS;
                // the maximum size of Long Text Area is 32768. If error log is more than this then create the attachment with error log 
                if(errorLog.Length() < 32768) {
                    batchJobsObj.Exception_Log__c = errorLog; 
                } else {
                    Attachment attachment = new Attachment(Body = Blob.valueOf(errorLog), Name = 'ErrorLog.txt', ParentId = batchJobsObj.Id );
                    insert attachment;  
                    batchJobsObj.Exception_Log__c = 'Error log is attached as an attachment, you can find the attachment in releated list';
                }
            }
            update batchJobsObj;       
         }
         
    }