Metadata/objects/Batch_Jobs__c.object
<CustomObject>
    <description>This holds the records for batch process of MRR and Renew Orders</description>
    <fields>
        <fullName>Completed_Date_and_Time__c</fullName>
        <label>Completed Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_and_Time__c</fullName>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed with errors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>MRR Calculation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Renewals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SteelBrick Batch Jobs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Engine__c</fullName>
        <label>Tax Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avalara AvaTax</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Invoice_Lines__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/BatchForPostingInvoices.cls
global class BatchForPostingInvoices implements Database.Batchable<sObject>,database.stateful,Database.AllowsCallouts{
     global string sQuery;
     global string InvoiceStatus = 'Draft';
     global Batch_Jobs__c batchJob;
     global string errorLog = null;
     global static boolean isExecuteAvaTax = true;
     global BatchForPostingInvoices(string query){
        this.sQuery = query;
         batchJob = new Batch_Jobs__c(Name = 'BatchInvoiceStatusUpdate- ' + system.today(), Type__c = 'BatchInvoiceStatusUpdate', Start_Date_and_Time__c = system.now(), Status__c = 'Processing');
         insert batchJob;  
      }
     global Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(sQuery);
      } 
      global void execute(Database.BatchableContext BC, List<Invoice__c> scope){
           try {
               isExecuteAvaTax = false;
               list<Invoice__c> listOfInvoice = new  list<Invoice__c>();
               Invoice__c invToUpdate;
               list<Invoice_Lines__c> listOfInvoiceLinesToUpdate = new list<Invoice_Lines__c>();
               for(Invoice__c inv : scope) {
                   if(inv.Tax_Engine__c == System.Label.Avalara) {
                         ClassforCalculatingAvaTax.calculateTaxInvoice(inv.Account__c,inv.Order__c,inv.id);
                       }
                       else{
                          invToUpdate = new Invoice__c(id = inv.id,Invoice_Status__c = 'Posted');
                          listOfInvoice.add(invToUpdate);
                   }
                   
               }
               update listOfInvoice;
           } catch(exception ex) {
              errorLog += '\n' + 'An exception has occured, exception type is ' + ex.getTypeName() + ':'+ex.getMessage() + ':' + ex.getLineNumber() + ':' + ex.getStackTraceString() + '\n';
          }    
     }
      global void finish(Database.BatchableContext BC){
          batchJob.Completed_Date_and_Time__c = system.now();
          if(errorLog == null) {
              batchJob.Status__c = 'Completed';
          } else {
              batchJob.Status__c = 'Completed with Errors';
              
              if(errorLog.Length() < 32768) {
                  batchJob.Exception_Log__c = errorLog; 
              } 
          }
          update batchJob;
      }
  }