Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it checked means Email has been sent to the customer.</description>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Run_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship to the Invoice Run.Invoice is child of  Invoice Run.
This field tells from which Invoice Run the Invoice is generated.</description>
        <label>Invoice Run (Created By)</label>
        <referenceTo>Invoice_Run__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to contact for Shipping Contact</description>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Shipping Contact)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Engine__c</fullName>
        <label>Tax Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avalara AvaTax</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Select the Account for that Quote</description>
        <inlineHelpText>This field will provide the Account for Quote</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Quote is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it is checked that means an Email has been sent to the customer.</description>
        <inlineHelpText>This field is used for indicating Email to customer when the Quote is generated</inlineHelpText>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Delivers the product to the customer</description>
        <inlineHelpText>This field represents for whom to Deliver the Product</inlineHelpText>
        <label>Primary(Shipping) Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quote (Shipping Contact)</relationshipLabel>
        <relationshipName>Quote1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <description>Service End Date</description>
        <inlineHelpText>This field is used as Service End Date for that particular charge</inlineHelpText>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassWebServiceEmailing.cls
global with sharing class ClassWebServiceEmailing {

    WebService static string sendInvoice(Id invoiceId) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        try {
            Invoice__c invoice = [SELECT Billing_Contact__c,Billing_Contact__r.Email 
                                    FROM Invoice__c 
                                    WHERE Id =: invoiceId];        
            string sEmailAddresses = invoice.Billing_Contact__r.Email;
            string sEmailId = invoice.Billing_Contact__c;

            Map<String,Configuration__c> mapConfiguration = Configuration__c.getAll();
            string sTemplateEmailId;

            if(mapConfiguration.containsKey('INVOICE_EMAIL_TEMPLATE')) {
                sTemplateEmailId = mapConfiguration.get('INVOICE_EMAIL_TEMPLATE').String_Value__c;
            }

            if(sEmailAddresses != null) {
                email.setSaveAsActivity(true);
                email.setTargetObjectId(sEmailId);
                email.setTemplateId(sTemplateEmailId);
                email.setWhatId(invoiceId);
                
                // Sends the email
                Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                return System.Label.Email_Success + ' ' + sEmailAddresses;
            }  
            else {
                return System.Label.BillingContact_Invoice;
            }
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }  
    }    

    WebService static string sendQuote(Id quoteId) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        try {           
            PageReference pdf = Page.sendQuote;
            pdf.getParameters().put('id',(String)quoteId);
            pdf.setRedirect(true);
            Blob b;
            if (!system.test.isRunningTest()){
                 b = pdf.getContent();
            }

            // Create the email attachment
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setBody(b);
            Quote__c quote = [SELECT Shipping_Contact__r.Email,Shipping_Contact__c,Valid_To__c,Name
                                FROM Quote__c 
                                WHERE Id =: quoteId];        
            
            efa.setFileName(quote.Name + '.pdf');

            if(!(quote.Valid_To__c < System.Today())) { 
                string sEmailAddresses = quote.Shipping_Contact__r.Email;
                string sEmailId = quote.Shipping_Contact__c;

                Map<String,Configuration__c> mapConfiguration = Configuration__c.getAll();
                string sTemplateEmailId = mapConfiguration.get('QUOTE_EMAIL_TEMPLATE').String_Value__c;

                if(sEmailAddresses != null){
                    email.setSaveAsActivity(true);
                    email.setTargetObjectId(sEmailId);
                    email.setTemplateId(sTemplateEmailId);
                    email.setWhatId(quoteId);

                    // Sets the paramaters of the email
                    email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                    // Sends the email
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                    Quote__c quote1 = new Quote__c(Id = quoteId,Email_Sent__c = CommonUtilClass.STATUS_TRUE);
                    update quote1;
                    return System.Label.Email_Success + ' ' + sEmailAddresses;
                }  
                else {
                    return System.Label.ShippingContact_Quote;
                }
            }
            else {
                return System.Label.Quote_is_Expired;
            }
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }  
    }

    webservice static string attachPdf(Id invoiceId,String invoiceName) {
        try {
            //create a attachment object and set the parameters
            Attachment attachment = new Attachment();
            attachment.OwnerId = UserInfo.getUserId();
            attachment.ParentId = invoiceId; // the record the file is attached to
            attachment.IsPrivate = true;
            attachment.Name = invoiceName + '-'+ System.today().format() + '.Pdf';
            
            //get the pdf content to be attached by passing the invoice id
            PageReference pdf = Page.viewinvoice;
            pdf.getParameters().put('id',(String)invoiceId);
            pdf.setRedirect(true);
            Blob b;
            if (!system.test.isRunningTest()){
                b = pdf.getContent();
            }
            
            attachment.body = b;       
            insert attachment;  

            return System.Label.AttachPDF_Invoice;
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }
    }
    
    webservice static string attachPdfToOpportunity(Id OppId,String quoteName,Id quoteId) {
        try {
            //create a attachment object and set the parameters
            Attachment attachment = new Attachment();
            attachment.OwnerId = UserInfo.getUserId();
            attachment.ParentId = quoteId; // the record the file is attached to
            attachment.IsPrivate = true;
            attachment.Name = 'Quote' + '.Pdf';
            
            //get the pdf content to be attached by passing the invoice id
            PageReference pdf = Page.sendquote;
            pdf.getParameters().put('id',(String)quoteId);
            pdf.setRedirect(true);
            Blob b;
            if (!system.test.isRunningTest()){
                b = pdf.getContent();
            }
            
            attachment.body = b;       
            insert attachment;  
            return System.Label.AttachPDF_Quote;
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }
    }
    
    webservice static string emailAllInvoicesForInvoiceRun(Id invoiceRunID) {
        try {
            list<Invoice__c> listOfInvoices = [SELECT Id,Email_Sent__c
                                               FROM Invoice__c
                                               WHERE Invoice_Run_Created_By__c =: invoiceRunID];
    
            list<Invoice__c> listOfInvoicesToUpdate = new list<Invoice__c>();
            
            for(Invoice__c invoice : listOfInvoices) {
                    Invoice__c invoiceToBeUpdated = new Invoice__c(Id = invoice.Id,
                                                        Email_Sent__c = CommonUtilClass.STATUS_TRUE);
                    listOfInvoicesToUpdate.add(invoiceToBeUpdated);
                }
                
            update  listOfInvoicesToUpdate; 
            
            return System.Label.Email_Success_All_Users;
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }
    }
    
    webservice static string postAllInvoicesForInvoiceRun(Id invoiceRunID) {
        try {
            
            //Commented by Dev INVOICEIT-595
             /* list<Invoice__c> listOfInvoices = [SELECT Id,Email_Sent__c
                                               FROM Invoice__c
                                               WHERE Invoice_Run_Created_By__c =: invoiceRunID
                                               AND Invoice_Status__c =: CommonUtilClass.STATUS_DRAFT];
    
            if(listOfInvoices.size() > 0) {
                for(Invoice__c invoice : listOfInvoices) {
                    invoice.Invoice_Status__c = CommonUtilClass.STATUS_POSTED;
                }
                    
                update  listOfInvoices; 
            } else {
                return 'No invoice(s) are present with status draft';
            } */
            
            string sQuery = 'SELECT Name,Tax_Engine__c,Order__c,Account__c,Invoice_Date__c,Amount__c FROM Invoice__c where Invoice_Run_Created_By__c =\'' +invoiceRunID + '\' And Invoice_Status__c = \'Draft\'';
            BatchForPostingInvoices  b = new BatchForPostingInvoices(sQuery);
            database.executebatch(b,1);

            return 'Batch job has been started, the invoice will posted soon';
        }
        catch(Exception ex) {
            return System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber();
        }
    }
}