Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Invoice_Lines__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Rate Plan Charge</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</description>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <description>The ending date for the period of calculation of this charge. Applicable only to Recurring Charges.</description>
        <inlineHelpText>The ending date for the period of calculation of this charge. Applicable only to Recurring Charges.</inlineHelpText>
        <label>Charge End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Job2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <formula>CurrencyL__r.Currency_Symbol__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency Symbol</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Billing_Master_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Consortium Billing. Check this field if you are using this Order to as the billing master Order for other child Orders. The Pricing/Discount should be recorded as part of this Order record</description>
        <inlineHelpText>Used in Consortium Billing. Check this field if you are using this Order to as the Billing Master Order for other child Orders. The Pricing/Discount should be recorded as part of this Order record</inlineHelpText>
        <label>Is Billing Master Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <description>Shows the Date on which the Service commences. The field can also be used to record the Order Delivery Date.</description>
        <inlineHelpText>The Service Starts on this Date. Can also be used to record the Order Delivery Date.</inlineHelpText>
        <label>Service Start Date / Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <description>The Service/Subscription for this Order ends on this Date.</description>
        <inlineHelpText>The Date on which the Order Service/Subscription ends.</inlineHelpText>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Job_Product__c.object
<CustomObject>
    <description>The tier 1 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Currency code for the order charge that will match to the currency code of the Order.</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/ControllerCreateAdhocInvoice.cls
public with sharing class ControllerCreateAdhocInvoice {
        public Job__c order {get;set;}
        public String responseMessage;
        public Job__c job{get;set;}
        public string sLogo {set; get;}
        
        public ControllerCreateAdhocInvoice(ApexPages.StandardController controller) {
            
            order = (Job__c) controller.getRecord();
            
            // Querying the order status INVOICEIT-520 By Dev M
            order = [select Id, Is_Billing_Master_Order__c , Status__c, Name, Currency_Symbol__c, CurrencyL__r.Name, CurrencyL__c,Billing_Contact__r.MailingCountry, Billing_Contact__r.MailingPostalCode, Billing_Contact__r.MailingState, Billing_Contact__r.MailingCity, Billing_Contact__r.MailingStreet, Billing_Contact__c, Billing_Contact__r.Salutation, Billing_Contact__r.LastName From Job__c where id=:order.Id];
            // just initalize the instance, since we want invoice date and target date
            job = new Job__c();
            
            if(order.Is_Billing_Master_Order__c) 
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO,system.Label.Invoice_For_Billing_Master_Order));
        }

        public PageReference createAdhocInvoice() {
            Date invoiceDate, targetDate, cutoffDate;
            String chargeStatusForInvoicing = (Configuration__c.getValues('CHARGE_STATUS_FOR_INVOICING').String_Value__c); 
            SavePoint sp;
            try {
                sp = Database.setSavepoint();
                String orderStatusForInvoicing = (Configuration__c.getValues('ORDER_STATUS_FOR_INVOICING').String_Value__c);
                
                if(orderStatusForInvoicing != null && orderStatusForInvoicing.trim().length() > 0 && orderStatusForInvoicing != order.Status__c) {
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Order_Status));
                    return null; 
                }
                
                invoiceDate = job.Service_Activation_Date__c; 
                targetDate = job.Service_End_Date__c;
            
                CustomInvoiceGenerator invoiceGenerator = new CustomInvoiceGenerator();

                responseMessage = invoiceGenerator.generateInvoiceForOrder(order.Id, invoiceDate, targetDate, true, false, false);

                if( responseMessage != null && responseMessage.length() > 0 && !responseMessage.contains('null')) {
                    if(responseMessage.contains('ERROR') || responseMessage.contains('null')) {
                        Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, responseMessage)); 
                    } else {
                        return new PageReference('/' + responseMessage);    
                    }
                } else {
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.NoInvoicesGenerated));
                }   
            } catch(Exception ex) {
                //Added by DL,NVOICEIT-665, 
                
                Database.rollback(sp);
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.ExceptionMessage + ex.getTypeName() + ':'+ex.getMessage() + ':'  + ex.getLineNumber()));         
            }

            return null;
        }
        //Added by dhanalakshmi for INVOICEIT-188
        
        public Invoice__c invoiceObj{get;set;}
        public list<Invoice_Lines__c> listOfInvoiceLinesForPreview{get;set;} 
        public decimal subtotal{get;set;}
        public decimal discount{get;set;}
        public decimal vat{get;set;}
        public decimal tax{get;set;}
        public decimal invoiceTotal{get;set;}
        public String sPriceType{get;set;}
        
        public PageReference generateInvoicePreview() {
            
            list<StaticResource> listOfStaticResources = [SELECT Id,SystemModstamp FROM StaticResource WHERE Name = 'logo'];
            if(!listOfStaticResources.isEmpty()) {
                
               sLogo = '/resource/'+listOfStaticResources[0].SystemModStamp.getTime()+'/logo';
            } else {
                sLogo = (Configuration__c.getValues('COMPANY_LOGO').String_Value__c);
            }
            
            Date invoiceDate, targetDate, cutoffDate;
            String chargeStatusForInvoicing = (Configuration__c.getValues('CHARGE_STATUS_FOR_INVOICING').String_Value__c); 
            try {
                
                String orderStatusForInvoicing = (Configuration__c.getValues('ORDER_STATUS_FOR_INVOICING').String_Value__c);
                if(orderStatusForInvoicing != null && orderStatusForInvoicing.trim().length() > 0 && orderStatusForInvoicing != order.Status__c) {
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label..Order_Status));
                    return null; 
                }
                
                invoiceDate = job.Service_Activation_Date__c;
                targetDate = job.Service_End_Date__c;
            
                CustomInvoiceGenerator invoiceGenerator = new CustomInvoiceGenerator();

                responseMessage = invoiceGenerator.generateInvoiceForOrder(order.Id, invoiceDate, targetDate, true, true, false);
                invoiceObj = new Invoice__c();
                listOfInvoiceLinesForPreview = new list<Invoice_Lines__c>();
                Map<Id, Job_Rate_Plan_Charge__c> mapOfOrderIdToCharge = new Map<Id, Job_Rate_Plan_Charge__c>([Select Price_Type__c, Order__c     
                                                                                  From Job_Rate_Plan_Charge__c 
                                                                                  where Job_Rate_Plan__r.Job_Product__r.Job__c =: order.Id]);
                
                invoiceObj = invoiceGenerator.invoiceObj;
                listOfInvoiceLinesForPreview = invoiceGenerator.listOfInvoiceLinesForPreview;
                subtotal = 0.0;
                discount = 0.0;
                vat = 0.0;
                tax = 0.0;
                invoiceTotal = 0.0;
                if(listOfInvoiceLinesForPreview.size() > 0)
                {
                    for(Invoice_Lines__c invoiceLines: listOfInvoiceLinesForPreview)
                    {   
                        
                        if(mapOfOrderIdToCharge.containskey(invoiceLines.Job_Rate_Plan_Charge__c)){
                            invoiceLines.Line_Name__c = mapOfOrderIdToCharge.get(invoiceLines.Job_Rate_Plan_Charge__c).Price_Type__c;
                        }
                        
                        
                        if(invoiceLines.Line_Amount__c != null && invoiceLines.Line_Amount__c != 0){
                            subtotal = subtotal + invoiceLines.Line_Amount__c;
                        }
                        if(invoiceLines.Discount_Value__c != null && invoiceLines.Discount_Value__c != 0){
                            discount = discount + invoiceLines.Discount_Value__c;
                        }
                        if(invoiceLines.VAT__c != null && invoiceLines.VAT__c != 0){
                            vat = vat + invoiceLines.VAT__c;
                        }
                        if(invoiceLines.Tax__c != null && invoiceLines.Tax__c != 0){
                            tax = tax + invoiceLines.Tax__c;
                        }
                        invoiceTotal = subtotal - discount + vat + tax;
                    }
                } 
                if(listOfInvoiceLinesForPreview.size() == 0)
                { 
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.NoInvoicesGenerated));
                    //return null;
                }
                else
                {
                    return page.generateInvoicePreview;
                }
                
            } catch(Exception ex) {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.ExceptionMessage + ex.getTypeName() + ':'+ex.getMessage() + ':'  + ex.getLineNumber()));         
            }

            return null;
            
        }
        //End
    }