Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <description>Exchange Rate Applied</description>
        <inlineHelpText>If you are a multi currency org, this field will hold the Exchange Rate between the Invoice Currency and your Corporate Currency. 
Value in Corporate Currency = Value in Invoice Currency x Exchange Rate Applied</inlineHelpText>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The payment Currency</description>
        <inlineHelpText>The payment Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment,allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment,allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.CurrencyL__c</field>
                <operation>equals</operation>
                <valueField>$Source.Currency__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.Invoice_State__c</field>
                <operation>notEqual</operation>
                <value>Proforma</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refunded_Amount__c</fullName>
        <label>Refunded Amount</label>
        <summarizedField>Refund_Line__c.Refund_Amount__c</summarizedField>
        <summaryForeignKey>Refund_Line__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Payment_Allocation__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Holds the Payment Allocation details which essentially splits the Payment among invoices.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <description>The Invoice against which this Payment is made.</description>
        <inlineHelpText>The Invoice against which this Payment is made.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <summarizedField>Refund_Line__c.Refund_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Refund_Line__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Refund_Line__c.Refund__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Refund_Line__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refund Lines</relationshipLabel>
        <relationshipName>Refund_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Refund Lines</relationshipLabel>
        <relationshipName>Refund_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund Line</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Refund Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Transaction__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassAfterOnPayment.cls
public with sharing class ClassAfterOnPayment {
        /** If AUTOMATE_PAYMENT_ALLOCATION boolean is true then the Payament Allocation is done for invoice*/
        public static boolean PAYMENT_AFTER_PROCESSING_COMPLETE = false;

        public void setPaymentsAfterProcessingComplete() {
            PAYMENT_AFTER_PROCESSING_COMPLETE = true;
        }

        public Boolean getPaymentsAfterProcessingComplete() {
            return PAYMENT_AFTER_PROCESSING_COMPLETE;
        }

        public void handleAfterOnPayments(map<Id,Payment__c> newMap, map<Id,Payment__c> oldMap)
        {
            list<Payment_Allocation__c> listOfPaymentAllocations = new list<Payment_Allocation__c>();
            decimal un_AllocatedAmount = 0;
            Payment_Allocation__c pAllocation;

            boolean isPaymentAutomated = Configuration__c.getValues('AUTOMATE_PAYMENT_ALLOCATION').Boolean_Value__c; 
            
            if(trigger.isInsert) {
                // Added by Shruthi for INVOICEIT-394,Payment allocation are automatically created when the invoice is populated on Payment
                for(Payment__c payment : newMap.values()) {
                    if(payment.Transaction__c == null && payment.Invoice__c != null &&  payment.status__c == 'Completed') {
                        pAllocation = new Payment_Allocation__c(Invoice__c = payment.Invoice__c, Amount__c = payment.Amount__c, Payment__c = payment.Id);
                        listOfPaymentAllocations.add(pAllocation);
                    }
                }
                            
                if(isPaymentAutomated) {
                    for(Payment__c payment : newMap.Values()) {
                        if(payment.Transaction__c == null && payment.Invoice__c == null &&  payment.status__c == 'Completed') {        
                            list<Invoice__c> listOfInvoices = ControllerAllocatePayments.getInvoicesForPayment(payment);
                            un_AllocatedAmount = payment.Amount__c;
                            
                            for(Invoice__c invoice : listOfInvoices) {
                                if(un_AllocatedAmount >= invoice.Unpaid_Amount__c) {
                                    pAllocation = new Payment_Allocation__c(Invoice__c = invoice.Id, Amount__c = invoice.Unpaid_Amount__c, Payment__c = payment.Id);
                                    un_AllocatedAmount = un_AllocatedAmount - invoice.Unpaid_Amount__c;
                                    listOfPaymentAllocations.add(pAllocation);
                                } else {
                                    // below if condition is added by ram to avoid 0$ allocation, jira tkt INVOICEIT-439, date : jan 21,2015
                                    if(un_AllocatedAmount <= 0){
                                        break;
                                    }
                                    pAllocation = new Payment_Allocation__c(Invoice__c = invoice.Id, Amount__c = un_AllocatedAmount, Payment__c = payment.Id);
                                    un_AllocatedAmount = 0;
                                    listOfPaymentAllocations.add(pAllocation);
                                    //once the un_AllocatedAmount is 0 break the loop
                                    break;
                                }
                            }
                        }
                    }
                } 
                
                if(!listOfPaymentAllocations.isEmpty()) {
                    insert listOfPaymentAllocations;
                }
                
            } else if(Trigger.isUpdate) {
                set<Id> setOfPaymentIdsOfInterest = new set<Id>();
                list<Payment_Allocation__c> listOfPAllocationToUpdate;
                list<Refund__c> listOfRefundsToInsert = new list<Refund__c>();
                list<Refund_Line__c> listOfRefundLinesToInsert = new list<Refund_Line__c>();

                for(Payment__c newPayment : newMap.Values()) {
                    Payment__c oldPayment = oldMap.get(newPayment.Id);
                    //Added by DL for Payment Refund INVOICEIT-683
                    Refund__c refund;
                    Refund_Line__c refundLine;
                    if(newPayment.Status__c == CommonUtilClass.STATUS_CANCELLED && newPayment.Status__c != oldPayment.Status__c
                       ) {
                        setOfPaymentIdsOfInterest.add(newPayment.Id);
                        if(newPayment.Amount__c != newPayment.Refunded_Amount__c) {
                            refund = new Refund__c(Account__c = newPayment.Account__c, Currency__c = newPayment.Currency__c);
                            refundLine = new Refund_Line__c(Payment__c = newPayment.Id,Status__c='Completed',Refund_Amount__c = newPayment.Amount__c - newPayment.Refunded_Amount__c);
                            listOfRefundsToInsert.add(refund);
                            listOfRefundLinesToInsert.add(refundLine);
                        }
                    }
                }
                //Added by DL for Payment Refund INVOICEIT-683, inserting refund and refund lines
                if(!listOfRefundsToInsert.isEmpty()){
                    insert listOfRefundsToInsert;
                    for(integer i=0; i<listOfRefundsToInsert.size(); i++) {
                        listOfRefundLinesToInsert[i].Refund__c = listOfRefundsToInsert[i].Id;
                    }
                    insert listOfRefundLinesToInsert;
                }

                if(setOfPaymentIdsOfInterest.size() > 0) {
                    // Dev M INVOICEIT-213 Previously there was not where clause in the status, I have added Status__c =: CommonUtilClass.STATUS_COMPLETED
                    listOfPAllocationToUpdate = [SELECT Invoice__c
                                                 FROM Payment_Allocation__c
                                                 WHERE Payment__c IN : setOfPaymentIdsOfInterest
                                                 AND Status__c =: CommonUtilClass.STATUS_COMPLETED];

                    for(Payment_Allocation__c payAllocation : listOfPAllocationToUpdate) {
                        payAllocation.Status__c = CommonUtilClass.STATUS_CANCELLED;
                    }       

                    update listOfPAllocationToUpdate;
                }
            }
        }

        public void handleBeforeOnPayments(list<Payment__c> newPayments)
        { 
            if(UserInfo.isMultiCurrencyOrganization()) {
                map<Id,Currency__c> mapId_Currency;
                set<Id> setCurrencyId = new set<Id>();
                map<string,decimal> map_Payment_ConversionRate = new map<string,decimal>();
                map<Id, string> map_CurrId_CurrIsoCode = new map<Id, string>();
                date startDate;
                date nextStartDate;
                string isoCode;
                string paymentIsoCode;
                boolean isAdvanceCurrEnabled = true;

                // adding the currency Ids.
                for(Payment__c payment : newPayments) {
                    setCurrencyId.add(payment.Currency__c);
                }

                //adding the all currency names to list.
                for(Currency__c currencyObj : [SELECT Name FROM Currency__c WHERE Id IN:setCurrencyId]) {
                    map_CurrId_CurrIsoCode.put(currencyObj.Id, currencyObj.Name);
                }
                
                // converting the all ListOfStings Into String format 
                string sCurrencyIds = CommonUtilClass.convertListOfStingsIntoString(map_CurrId_CurrIsoCode.values()); 
                string sQuery =   'SELECT ISOCode, ConversionRate, StartDate, NextStartDate FROM DatedConversionRate '
                                   + ' WHERE ISOCode IN (' + sCurrencyIds  + ')';
                                   
                //when creating a dynamic SOQL statement,to help prevent SOQL injection. 
                sQuery = String.escapeSingleQuotes(sQuery);
                sQuery = sQuery.replace('\\',''); 
                
                // querying the DatedConversionRate(Multi currencyObj).
                list<sobject> sobjectDatedConversionRates = Database.query(sQuery);
                
                //if advance currency is not enabled, then query from the CurrencyType
                if(sobjectDatedConversionRates.isEmpty()) {
                    sQuery = 'SELECT ConversionRate,DecimalPlaces,Id,IsActive,IsCorporate,IsoCode FROM CurrencyType WHERE IsActive = true AND ISOCode IN (' + sCurrencyIds + ')';
                    sQuery = String.escapeSingleQuotes(sQuery);
                    sQuery = sQuery.replace('\\',''); 
                    sobjectDatedConversionRates = Database.query(sQuery);
                    isAdvanceCurrEnabled = false;
                }
                if(isAdvanceCurrEnabled) {
                    for(Payment__c payment : newPayments) {
                        for(sobject sobjectExchangeRate : sobjectDatedConversionRates) {
                            startDate = (date) sobjectExchangeRate.get('StartDate');
                            nextStartDate = (date) sobjectExchangeRate.get('NextStartDate');
                            isoCode = (string) sobjectExchangeRate.get('ISOCode');
                            
                            if(map_CurrId_CurrIsoCode.containsKey(payment.Currency__c)) {
                                paymentIsoCode = map_CurrId_CurrIsoCode.get(payment.Currency__c);
                                if(isoCode == paymentIsoCode 
                                    && startDate != null
                                    && nextStartDate != null
                                    && startDate <= system.today()
                                    && nextStartDate > system.today()) 
                                {
                                    payment.Exchange_Rate_Applied__c = (decimal) sobjectExchangeRate.get('ConversionRate');
                                    // To populate currencyisocode in multi currency org,related to invoiceIT-464
                                    CommonUtilClass.populateCurrencyIsoCodeOnSobject(payment, paymentIsoCode);
                                    break;
                                }
                            }
                        }
                    }  
                } else {
                    for(Payment__c payment : newPayments) {
                        for(sobject sobjectExchangeRate : sobjectDatedConversionRates) {
                            isoCode = (string) sobjectExchangeRate.get('ISOCode');
                            if(map_CurrId_CurrIsoCode.containsKey(payment.Currency__c)) {
                                paymentIsoCode = map_CurrId_CurrIsoCode.get(payment.Currency__c);
                                if(isoCode == paymentIsoCode) {
                                    payment.Exchange_Rate_Applied__c = (decimal) sobjectExchangeRate.get('ConversionRate');
                                    break;
                                }
                            }
                        }
                    }
                }  
            }                 
        }
    }