Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>Percentage_of_other_Charges__c</fullName>
        <description>Use this in conjunction with &quot;Percentage Pricing&quot; in the pricing model. You can typically use this for charges that are a percentage of other charges. 
e.g., Maintenance Charges could be 25% of the License charges.</description>
        <inlineHelpText>Use this in conjunction with &quot;Percentage Pricing&quot; in the pricing model. You can typically use this for charges that are a percentage of other charges. 
e.g., Maintenance Charges could be 25% of the License charges.</inlineHelpText>
        <label>% of Other Charges</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <description>This will specify whether price is default or tiered</description>
        <inlineHelpText>Please refer to the user documentation for detailed information on what the different pricing models mean.
Search for &quot;Pricing Model&quot; in the documentation.</inlineHelpText>
        <label>Pricing Model</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Fee Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Per Unit Pricing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume Pricing</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>ProductRatePlanCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Discount offered on this Quote</description>
        <inlineHelpText>Discount offered on this Quote</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Quote_Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 1 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice IT Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 2 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan</relationshipLabel>
        <relationshipName>RatePlan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <label>Quote Product</label>
        <referenceTo>Quote_Product__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 3 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <description>This determines the Type of Discount(i.e discount applied by Value or Percentage).</description>
        <inlineHelpText>This determines the Type of Discount(i.e discount applied by Value or Percentage).</inlineHelpText>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percentage_of_other_Charges__c</fullName>
        <label>% of Other Charges</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <description>This will specify whether Price is Default or Tiered</description>
        <label>Pricing Model</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Fee Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Per Unit Pricing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Pricing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>RatePlanCharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <label>Quote Rate Plan</label>
        <referenceTo>Quote_Rate_Plan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <fields>
        <fullName>End_Unit__c</fullName>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>Quote_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge_Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <label>Start Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>Q-TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestQuoteChargesCalculator.cls
//This class contains unit tests for validating the behavior of QuoteChargesCalculator classes and triggers.
         // Created By Asish
    @isTest(oninstall = false)
    private class TestQuoteChargesCalculator {

        static testMethod void ChargesCalculator() {
            map<string, Configuration__c> Configuration = Configuration__c.getAll();
            delete Configuration.values();
            ControllerInsertCustomSettings controllerInsertCustomSettings = new ControllerInsertCustomSettings();
            controllerInsertCustomSettings.insertValues();
            
            Account account = ClassPopulateTestData.createAccount();
            list<Contact> listOfContacts = ClassPopulateTestData.createContacts(account);
            list<Currency__c> listOfCurrencies = ClassPopulateTestData.currencies();
            
             ClassPopulateTestData.createTaxAndVatRates();
            
            list<Product__c> listOfProducts = ClassPopulateTestData.createProduct(); 
            Product__c product = listOfProducts[0];
            
            list<Product_Rate_Plan__c> listOfPlans = ClassPopulateTestData.createProductRatePlan(product);
            list<Product_Rate_Plan_Charge__c>  listOfProductCharges = ClassPopulateTestData.createProductRatePlanCharge(listOfPlans[0],listOfCurrencies[1]);
            ClassPopulateTestData.createTaxAndVatRates();
            
            Quote__c quote = ClassPopulateTestData.createQuote(account,listOfContacts[2],listOfCurrencies[1]);
            
            Quote_Product__c quoteProduct =  new Quote_Product__c(Name = 'Test' , Quote__c = quote.Id,Product__c = product.id);
            insert quoteProduct;

            Quote_Product__c quoteProduct1 = [select Name From Quote_Product__c where id=:quoteProduct.id];
            System.assertEquals('Test', quoteProduct1.Name);
            
            Quote_Rate_Plan__c quotePlan = new Quote_Rate_Plan__c(Name = 'plan test',Quote_Product__c = quoteProduct.id);
            insert quotePlan;
            
            Quote_Rate_Plan_Charge__c quoteCharge = new Quote_Rate_Plan_Charge__c(Name='test Charges',Discount_Value__c  = 10,Quote_Rate_Plan__c = quotePlan.id,Quantity__c = 2,Unit_Price__c = 200,Price_Format__c = 'Percentage Pricing', Discount_Type__c = CommonUtilClass.DISCOUNT_TYPE_VALUE);
            quoteCharge.Percentage_of_other_Charges__c = 1.25;
            insert quoteCharge;
            
            Quote_Rate_Plan_Charge__c quoteCharge1 = new Quote_Rate_Plan_Charge__c(Name='test Charges',Discount_Value__c  = 15,Quote_Rate_Plan__c = quotePlan.id,Quantity__c = 1,Unit_Price__c = 200,Price_Format__c = 'Tiered Pricing');
            //quoteCharge1.Percentage_of_other_Charges__c = 1.25;
            insert quoteCharge1;
            
            Quote_Rate_Plan_Charge__c quoteCharge2 = new Quote_Rate_Plan_Charge__c(Name='test Charges',Discount_Value__c  = 12,Quote_Rate_Plan__c = quotePlan.id,Quantity__c = 1,Unit_Price__c = 200,Price_Format__c = 'Flat Fee Pricing');
            //quoteCharge1.Percentage_of_other_Charges__c = 1.25;
            insert quoteCharge2;
            
            Quote_Rate_Plan_Charge__c quoteCharge3 = new Quote_Rate_Plan_Charge__c(Name='test Charges',Discount_Value__c  = null,Quote_Rate_Plan__c = quotePlan.id,Quantity__c = 1,Unit_Price__c = 200,Price_Format__c = 'Per Unit Pricing');
            //quoteCharge1.Percentage_of_other_Charges__c = 1.25;
            insert quoteCharge3;
            
            Quote_Rate_Plan_Charge_Tier__c tier = new Quote_Rate_Plan_Charge_Tier__c(Start_Unit__c = 1,End_Unit__c=5,Unit_Price__c = 100,Quote_Rate_Plan_Charge__c = quoteCharge.id);
            insert tier;
            
            
            QuoteRatePlanChargeTierClass tierClsObj = new QuoteRatePlanChargeTierClass();
            tierClsObj.quoteRatePlanChargeTier = tier;
            list<QuoteRatePlanChargeTierClass> listofTierClass = new list<QuoteRatePlanChargeTierClass>();
            listofTierClass.add(tierClsObj);
            
            QuoteRatePlanChargeClass chargeClsObj = new QuoteRatePlanChargeClass();
            chargeClsObj.quoterateplancharge = quoteCharge;
            QuoteRatePlanChargeClass chargeClsObj1 = new QuoteRatePlanChargeClass();
            chargeClsObj1.quoterateplancharge = quoteCharge1;
            QuoteRatePlanChargeClass chargeClsObj2 = new QuoteRatePlanChargeClass();
            chargeClsObj2.quoterateplancharge = quoteCharge2;
            QuoteRatePlanChargeClass chargeClsObj3 = new QuoteRatePlanChargeClass();
            chargeClsObj3.quoterateplancharge = quoteCharge3;
            list<QuoteRatePlanChargeClass> listofCharges = new list<QuoteRatePlanChargeClass>();
            listofCharges.add(chargeClsObj);
            listofCharges.add(chargeClsObj1);
            listofCharges.add(chargeClsObj2);
            listofCharges.add(chargeClsObj3);
            chargeClsObj.quoteRatePlanChargeTiers = listofTierClass;
            
            QuoteRatePlanClass planClsObj = new QuoteRatePlanClass();
            planClsObj.quoterateplan = quotePlan;
            list<QuoteRatePlanClass> listOfPlansCls = new list<QuoteRatePlanClass>();
            listOfPlansCls.add(planClsObj);
            planClsObj.quoteRatePlanCharges = listofCharges;
            
            
            QuoteProductClass quoteproductClsObj = new QuoteProductClass();
            quoteproductClsObj.quoteproduct = quoteProduct;
            list<QuoteProductClass> listofProductsCls = new list<QuoteProductClass>();
            listofProductsCls.add(quoteproductClsObj);
            quoteproductClsObj.quoteRatePlans = listOfPlansCls;
            
            
            QuoteClass quoteClsObj = new QuoteClass();
            quoteClsObj.quote = quote;
            quoteClsObj.quoteProducts = listofProductsCls;
            
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.Charges quoteChargCalObj = new QuoteChargesCalculator.Charges();
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            Configuration__c automatedCS = Configuration__c.getValues('TAX_CALCULATION_BASED_ON'); 
            automatedCS.String_Value__c = 'Billing Contact';
            update automatedCS;
            
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            //when custom setting It is Shipping Contact
            
            automatedCS.String_Value__c = 'Shipping Contact';
            update automatedCS;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            Configuration__c automatedCS1 = Configuration__c.getValues('ACCOUNT_LEGAL_ENTITY_FIELD_NAME'); 
            automatedCS1.String_Value__c = 'Name';
            update automatedCS1;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            Configuration__c automatedCS2 = Configuration__c.getValues('QUOTE_LEGAL_ENTITY_FIELD_NAME'); 
            automatedCS2.String_Value__c = 'Name';
            automatedCS1.String_Value__c = null;
            update automatedCS2;
            update automatedCS1;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            automatedCS2.String_Value__c = null;
            update automatedCS2;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            Configuration__c automatedCS3 = Configuration__c.getValues('CALCULATION_PRECISION');
            automatedCS3.String_Value__c = 'ROUND_UP';
            update automatedCS3;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
            
            Configuration__c automatedCS4 = Configuration__c.getValues('CALCULATION_PRECISION');
            automatedCS4.String_Value__c = 'ROUND_DOWN';
            update automatedCS4;
            QuoteChargesCalculator.calculateCharges(quoteClsObj);
            QuoteChargesCalculator.calculateSubtotal(quoteClsObj ,quoteChargCalObj);
        }
    }