Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>This is the total Discount provided on this Invoice.</description>
        <inlineHelpText>This is the total Discount provided on this Invoice.</inlineHelpText>
        <label>Discount Value</label>
        <summarizedField>Invoice_Lines__c.Discount_Value__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <description>Exchange Rate Applied</description>
        <inlineHelpText>If you are a multi currency org, this field will hold the Exchange Rate between the Invoice Currency and your Corporate Currency. 
Value in Corporate Currency = Value in Invoice Currency x Exchange Rate Applied</inlineHelpText>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to contact for Shipping Contact</description>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Shipping Contact)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target  Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Invoice_Lines__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>The Discount Value to be applied on the Subtotal.</description>
        <inlineHelpText>The Discount Value to be applied on the Subtotal.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Rate Plan Charge</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Amount__c</fullName>
        <description>Quantity * Unit Price</description>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Job2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>Discount offered on this Order</description>
        <inlineHelpText>Discount offered on this Order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <description>Exchange Rate Applied</description>
        <inlineHelpText>If you are a multi currency org, this field will hold the Exchange Rate between the Order Currency and your Corporate Currency. 
Value in Corporate Currency = Value in Order Currency x Exchange Rate Applied</inlineHelpText>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary(Shipping) Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Shipping Contact)</relationshipLabel>
        <relationshipName>Job1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <description>Quantity * Unit Price</description>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Currency code for the order charge that will match to the currency code of the Order.</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Discount Value that has been applied to the order charge.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>The Quantity of Products/Services being sold</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewed_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewed From</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges (Renewed From)</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <inlineHelpText>Shows the Tax code that has been applied to this charge.</inlineHelpText>
        <label>Tax Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassforCalculatingTax.cls
global with sharing class ClassforCalculatingTax{

    //This method is used to get and commit the tax
    global static ClassTaxParameters getTaxForInvoice(Tax_Integration__c taxIntegration, string sObjectId){

        String sPrefix = CommonUtilClassForTaxation.getPrefix();
        string sObjectQuery = 'SELECT '+ CommonUtilClassForTaxation.getObjectFields(sPrefix+'Invoice__c')
                            + ', (SELECT Invoice__r.Amount__c,' + CommonUtilClassForTaxation.getObjectFields(sPrefix+'Invoice_Lines__c') +  'FROM Invoice_Lines__r ) '
                            + ',CurrencyL__r.Name '
                            + 'FROM Invoice__c '
                            + 'WHERE Id =' + '\'' + sObjectId + '\'';

        sObjectQuery = String.escapeSingleQuotes(sObjectQuery);
        sObjectQuery = sObjectQuery.replace('\\', '');
        Invoice__c invoice = Database.query(sObjectQuery);
        Account account;
        String sTaxCalculationBasedOn = Configuration__c.getValues(CommonUtilClassForTaxation.TAX_CALCULATION_BASED_ON).String_Value__c;
        if(sTaxCalculationBasedOn != null ||  sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_BILLING_ADDRESS || sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_SHIPPING_ADDRESS){ 
                account = (Account) CommonUtilClassForTaxation.getSobjectById(CommonUtilClassForTaxation.OBJECT_NAME_ACCOUNT, invoice.Account__c);
        }

        ClassforCalculatingTax.ClassTaxParameters objTaxation = new ClassforCalculatingTax.ClassTaxParameters();
        objTaxation.sDocType = 'SalesInvoice';
        objTaxation.sDocCode = invoice.Name;
        objTaxation.sCustomerCode = invoice.Name;
        objTaxation.sDocDate = string.valueof(invoice.Invoice_Date__c);
        objTaxation.dDiscount = invoice.Discount_Value__c;
        objTaxation.sOriginCode = '0';
        objTaxation.sDestinationCode = '1';
        objTaxation.sCurrencyCode = invoice.CurrencyL__r.Name;
        objTaxation.sPaymentDate = string.valueof(invoice.Target_Date__c);
        objTaxation.dExchangeRate = invoice.Exchange_Rate_Applied__c;

        objTaxation.listOfInvoiceLinesToUpdate = invoice.Invoice_Lines__r;
        //obj.sExchangeRateEffDate = d;
        list<ClassforCalculatingTax.ClassBaseAddress> listOfBaseAddress = new list<ClassforCalculatingTax.ClassBaseAddress>();
        ClassforCalculatingTax.ClassBaseAddress baseAddress = new ClassforCalculatingTax.ClassBaseAddress();
        list<ClassforCalculatingTax.ClassLines> listOfline = new list<ClassforCalculatingTax.ClassLines>();
        ClassforCalculatingTax.ClassLines lineAddress; 
        
        //Framing data
        if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_BILLING_ADDRESS){  
            if(account != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(account.BillingStreet);
                baseAddress.scity = string.valueof(account.BillingCity);
                baseAddress.sRegion = string.valueof(account.BillingState);
                baseAddress.sPostalCode = string.valueof(account.BillingPostalCode);
                baseAddress.sCountry = string.valueof(account.BillingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;
                
            }
        }else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_SHIPPING_ADDRESS){  
            if(account != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(account.ShippingStreet);
                baseAddress.scity = string.valueof(account.ShippingCity);
                baseAddress.sRegion = string.valueof(account.ShippingState);
                baseAddress.sPostalCode = string.valueof(account.ShippingPostalCode);
                baseAddress.sCountry = string.valueof(account.ShippingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;
            }
        }else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.CONTACT_TYPE_BILLING && invoice.Billing_Contact__c != null)
        {
            Contact contact = [SELECT MailingStreet,MailingCountry, MailingCity, MailingState, MailingPostalCode
                              FROM Contact
                              WHERE Id = :invoice.Billing_Contact__c];
            if(contact != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(contact.MailingStreet);
                baseAddress.scity = string.valueof(contact.MailingCity);
                baseAddress.sRegion = string.valueof(contact.MailingState);
                baseAddress.sPostalCode = string.valueof(contact.MailingPostalCode);
                baseAddress.sCountry = string.valueof(contact.MailingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;

            }
        }
        else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.CONTACT_TYPE_SHIPPING && invoice.Shipping_Contact__c != null)
        {
            Contact contact = [SELECT MailingStreet,MailingCountry, MailingCity, MailingState, MailingPostalCode
                                      FROM Contact
                                      WHERE Id = :invoice.Shipping_Contact__c];
            if(contact != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(contact.MailingStreet);
                baseAddress.scity = string.valueof(contact.MailingCity);
                baseAddress.sRegion = string.valueof(contact.MailingState);
                baseAddress.sPostalCode = string.valueof(contact.MailingPostalCode);
                baseAddress.sCountry = string.valueof(contact.MailingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;

            }
        }
        if(invoice != null){
            
            for(Invoice_Lines__c invoiceLines : invoice.Invoice_Lines__r){
                lineAddress = new ClassforCalculatingTax.ClassLines();
                lineAddress.sLineNo = string.valueof(invoiceLines.Name);
                lineAddress.sOriginCode = '0';
                lineAddress.sDestinationCode = '1';
                //lineAddress.sItemCode = 'N543'; 
                lineAddress.sTaxCode = invoiceLines.Tax_Code__c;
                lineAddress.dQty = invoiceLines.Quantity__c;
                lineAddress.dAmount = invoiceLines.Line_Amount__c;
                //lineAddress.bDiscounted = false; 
                //lineAddress.sDescription = 'Size 10 Green Running Shoe';
                listOfline.add(lineAddress);
                objTaxation.listofClassLines = listOfline;
            }
        }
        

        objTaxation.taxIntegrationObj = taxIntegration;
       
        ClassforCalculatingAvaTax objClassforCalculatingAvaTax = new ClassforCalculatingAvaTax();
        objTaxation = objClassforCalculatingAvaTax.getTax(objTaxation);
        
        return objTaxation;
    }

    //We are not using this method, as we are using 'getTaxForInvoice' method to get and commit the tax
    global static ClassTaxParameters postTaxForInvoice(Tax_Integration__c taxIntegration, Invoice__c invoice,Decimal taxamount){
        ClassforCalculatingTax.ClassTaxParameters objTaxation = new ClassforCalculatingTax.ClassTaxParameters();
        objTaxation.taxIntegrationObj = taxIntegration;
        //framing data for post tax
        objTaxation.sDocType = 'SalesInvoice';
        objTaxation.sDocCode = invoice.Name;
        objTaxation.sCustomerCode = invoice.Name;
        objTaxation.sDocDate = string.valueof(invoice.Invoice_Date__c);
        objTaxation.dTotalAmount = invoice.Amount__c;
        objTaxation.dTotalTax = taxamount;
        
        ClassforCalculatingAvaTax objClassforCalculatingAvaTax = new ClassforCalculatingAvaTax();
        objTaxation = objClassforCalculatingAvaTax.postTax(objTaxation);
    
        return objTaxation;
    }
    global static ClassTaxParameters cancelTaxForInvoice(Tax_Integration__c taxIntegration, Invoice__c invoice){
        
        ClassforCalculatingTax.ClassTaxParameters objTaxation = new ClassforCalculatingTax.ClassTaxParameters();
        objTaxation.taxIntegrationObj = taxIntegration;

        //framing data for cancel tax
        objTaxation.sDocType = 'SalesInvoice';
        objTaxation.sDocCode = invoice.Name;
        objTaxation.sCancelCode  = 'DocVoided';
   
        ClassforCalculatingAvaTax objClassforCalculatingAvaTax = new ClassforCalculatingAvaTax();
        objTaxation = objClassforCalculatingAvaTax.cancelTax(objTaxation);
       
        return objTaxation;
    }
    global static ClassTaxParameters getTaxForOrder(Tax_Integration__c taxIntegration, string sObjectId){

        String sPrefix = CommonUtilClassForTaxation.getPrefix();
        string sObjectQuery = 'SELECT '+ CommonUtilClassForTaxation.getObjectFields(sPrefix+'Job__c')
                            + ', (SELECT Order__r.Sub_Total__c,' + CommonUtilClassForTaxation.getObjectFields(sPrefix+'Job_Rate_Plan_Charge__c') +  'FROM Order_Rate_Plan_Charges__r ) '
                            + ',CurrencyL__r.Name '
                            + 'FROM Job__c '
                            + 'WHERE Id =' + '\'' + sObjectId + '\'';

        sObjectQuery = String.escapeSingleQuotes(sObjectQuery);
        sObjectQuery = sObjectQuery.replace('\\', '');
   
        Job__c order = Database.query(sObjectQuery);
        Account account;
        String sTaxCalculationBasedOn = Configuration__c.getValues(CommonUtilClassForTaxation.TAX_CALCULATION_BASED_ON).String_Value__c;
        if(sTaxCalculationBasedOn != null ||  sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_BILLING_ADDRESS || sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_SHIPPING_ADDRESS){ 
                account = (Account) CommonUtilClassForTaxation.getSobjectById(CommonUtilClassForTaxation.OBJECT_NAME_ACCOUNT, order.Account__c);
        }

        ClassforCalculatingTax.ClassTaxParameters objTaxation = new ClassforCalculatingTax.ClassTaxParameters();
        objTaxation.sDocType = 'SalesInvoice';
        objTaxation.sDocCode = order.Name;
        objTaxation.sCustomerCode = order.Name;
        objTaxation.sDocDate = string.valueof(order.Service_Activation_Date__c);
        objTaxation.dDiscount = order.Discount_Value__c;
        objTaxation.sOriginCode = '0';
        objTaxation.sDestinationCode = '1';
        objTaxation.sCurrencyCode = order.CurrencyL__r.Name;
        objTaxation.sPaymentDate = string.valueof(order.Service_Activation_Date__c);
        objTaxation.dExchangeRate = order.Exchange_Rate_Applied__c;

        objTaxation.listOfOrderLinesToUpdate = order.Order_Rate_Plan_Charges__r;
     
        list<ClassforCalculatingTax.ClassBaseAddress> listOfBaseAddress = new list<ClassforCalculatingTax.ClassBaseAddress>();
        ClassforCalculatingTax.ClassBaseAddress baseAddress = new ClassforCalculatingTax.ClassBaseAddress();
        list<ClassforCalculatingTax.ClassLines> listOfline = new list<ClassforCalculatingTax.ClassLines>();
        ClassforCalculatingTax.ClassLines lineAddress; 
        
        //Framing data
        if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_BILLING_ADDRESS){  
            if(account != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(account.BillingStreet);
                baseAddress.scity = string.valueof(account.BillingCity);
                baseAddress.sRegion = string.valueof(account.BillingState);
                baseAddress.sPostalCode = string.valueof(account.BillingPostalCode);
                baseAddress.sCountry = string.valueof(account.BillingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;
                
            }
        }else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.ACCOUNT_SHIPPING_ADDRESS){  
            if(account != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(account.ShippingStreet);
                baseAddress.scity = string.valueof(account.ShippingCity);
                baseAddress.sRegion = string.valueof(account.ShippingState);
                baseAddress.sPostalCode = string.valueof(account.ShippingPostalCode);
                baseAddress.sCountry = string.valueof(account.ShippingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;
            }
        }else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.CONTACT_TYPE_BILLING && order.Billing_Contact__c != null)
        {
            Contact contact = [SELECT MailingStreet,MailingCountry, MailingCity, MailingState, MailingPostalCode
                              FROM Contact
                              WHERE Id = :order.Billing_Contact__c];
            if(contact != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(contact.MailingStreet);
                baseAddress.scity = string.valueof(contact.MailingCity);
                baseAddress.sRegion = string.valueof(contact.MailingState);
                baseAddress.sPostalCode = string.valueof(contact.MailingPostalCode);
                baseAddress.sCountry = string.valueof(contact.MailingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;

            }
        }
        else if(sTaxCalculationBasedOn == CommonUtilClassForTaxation.CONTACT_TYPE_SHIPPING && order.Shipping_Contact__c != null)
        {
            Contact contact = [SELECT MailingStreet,MailingCountry, MailingCity, MailingState, MailingPostalCode
                                      FROM Contact
                                      WHERE Id = :order.Shipping_Contact__c];
            if(contact != null){
                baseAddress.sAddressCode = '0';
                baseAddress.sLine1 = string.valueof(contact.MailingStreet);
                baseAddress.scity = string.valueof(contact.MailingCity);
                baseAddress.sRegion = string.valueof(contact.MailingState);
                baseAddress.sPostalCode = string.valueof(contact.MailingPostalCode);
                baseAddress.sCountry = string.valueof(contact.MailingCountry);
                baseAddress.sTaxRegionId = '0';
                listOfBaseAddress.add(baseAddress);
                objTaxation.listofClassBaseAddress = listOfBaseAddress;

            }
        }
        if(order != null){
            
            for(Job_Rate_Plan_Charge__c orderRatePlanCharges : order.Order_Rate_Plan_Charges__r){
                lineAddress = new ClassforCalculatingTax.ClassLines();
                lineAddress.sLineNo = string.valueof(orderRatePlanCharges.Name);
                lineAddress.sOriginCode = '0';
                lineAddress.sDestinationCode = '1';
                //lineAddress.sItemCode = 'N543'; 
                lineAddress.sTaxCode = orderRatePlanCharges.Tax_Code__c;
                lineAddress.dQty = orderRatePlanCharges.Quantity__c;
                lineAddress.dAmount = orderRatePlanCharges.Price__c;
                //lineAddress.bDiscounted = false; 
                //lineAddress.sDescription = 'Size 10 Green Running Shoe';
                listOfline.add(lineAddress);
                objTaxation.listofClassLines = listOfline;
            }
        }
       
   
        objTaxation.taxIntegrationObj = taxIntegration;
       
        ClassforCalculatingAvaTax objClassforCalculatingAvaTax = new ClassforCalculatingAvaTax();
        objTaxation = objClassforCalculatingAvaTax.getTax(objTaxation);
        
        return objTaxation;
    }
    // Class to hold the baseaddress 
    global class ClassBaseAddress {
        global string sAddressCode;
        global string sLine1;
        global string sLine2;
        global string scity;
        global string sRegion;
        global string sPostalCode;
        global string sCountry;
        global string sTaxRegionId;
    }
    // Class to hold the line items.
    global class ClassLines {
        global string sLineNo; 
        global string sOriginCode;
        global string sDestinationCode;
        global string sItemCode;
        global string sTaxCode;
        global decimal dQty;
        global decimal dAmount;
        global boolean bDiscounted;
        global string sDescription;
    }

    global class ClassTaxParameters{
        //Variables to hold the document level values
        global string sTaxType;
        global string sDocType;
        global string sDocCode;
        global string sCustomerCode;
        global string sDocDate;
        global decimal dDiscount;
        global string sOriginCode;
        global string sDestinationCode;
        global string sCurrencyCode;
        global string sPaymentDate;
        global decimal dExchangeRate;
        global string sExchangeRateEffDate;
        global decimal dTotalAmount;
        global decimal dTotalTax;
        global string sCancelCode;
        global Tax_Integration__c taxIntegrationObj;
        //variables to hold the staus of requrest and while retuning values
        global string sMessage;
        global string sDocId;
        global string sDocStatus;
        global string sTransactionId;
        global string sSummary;
        global string sDetails;
        global boolean isSuccess;
        
        global decimal calculatedTax; 
        global list<ClassBaseAddress> listofClassBaseAddress;
        global list<ClassLines> listofClassLines;

        public list<Invoice_Lines__c> listOfInvoiceLinesToUpdate;
        public list<Job_Rate_Plan_Charge__c> listOfOrderLinesToUpdate;


    }
}