Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Processing_Date__c</fullName>
        <label>Last Processing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Tries__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment,allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment,allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.CurrencyL__c</field>
                <operation>equals</operation>
                <valueField>$Source.Currency__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.Invoice_State__c</field>
                <operation>notEqual</operation>
                <value>Proforma</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Description__c</fullName>
        <label>Payment Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment_Run__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Time__c</fullName>
        <description>Invoice run completed  time</description>
        <label>Completed Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Failed_Transactions__c</fullName>
        <label>Failed Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoices_Processed__c</fullName>
        <label>Invoices Processed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Scheduler</label>
        <referenceTo>Payment_Scheduler__c</referenceTo>
        <relationshipLabel>Payment Runs</relationshipLabel>
        <relationshipName>Payment_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Successful_Transactions__c</fullName>
        <label>Successful Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Payment_Value__c</fullName>
        <label>Total Payment Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Run</label>
    <nameField>
        <label>Payment_Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Payment_Scheduler__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <label>Payment Scheduler</label>
    <nameField>
        <label>Payment Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Transaction__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Run</label>
        <referenceTo>Payment_Run__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Status__c</fullName>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/BatchTransactions.cls
global with sharing class BatchTransactions implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
         
         global String query;
         global String errorLog = '';
         global Payment_Scheduler__c paymentScheduler;
         global Payment_Run__c paymentRun;   
         global integer noOfInvoicesProcessed = 0;
         global integer noOfSuccesfullTransaction = 0;
         global integer noOfFailedTransaction = 0;
         global Decimal noOfDaysBetweenRetries ;
         global list<Transaction__c> listOfTransactionsToUpdate;
         //Added by Siri:INVOICEIT-631:25-11-2015
         global list<Invoice__c> listOfInvoicesToUpdate = new list<Invoice__c>();
         global decimal totalTransactionsValue = 0.0;
           
         global BatchTransactions(String query, Payment_Scheduler__c paymentScheduler){
             this.query = query;
             this.paymentScheduler = paymentScheduler;
             listOfTransactionsToUpdate = new list<Transaction__c>();
             //Added by Siri:INVOICEIT-631:25-11-2015
             noOfDaysBetweenRetries = Configuration__c.getValues('PAYMENT_NO_OF_DAYS_BETWEEN_RETRIES').Number_Value__c;
             paymentRun = new Payment_Run__c(Payment_Scheduler__c = paymentScheduler.Id, Name = paymentScheduler.Name, 
                                             Status__c = CommonUtilClass.STATUS_PROCESSING, Start_Time__c = system.now());
         }
         
         global Database.QueryLocator start(Database.BatchableContext BC) {
            insert paymentRun;
            return Database.getQueryLocator(query);
         }
         
         global void execute(Database.BatchableContext BC, list<sObject> scope) {

            //Added by Siri: INVOICEIT-631:25-11-2015
            Date lastProcessingDate ;
            Decimal noOfDays = 0;
            Decimal noOfTries ;

            for(sObject sObj : scope) {
                 ++noOfInvoicesProcessed;
                 Invoice__c invoice = (Invoice__c) sObj;
                 // Added by Dev M: SUP-543
                 PaymentOperations.PaymentResult result;

                 //If conditions added by Siri: INVOICEIT-631: 25-11-2015
                 if(invoice.No_of_tries__c != null){
                    noOfTries = invoice.No_of_tries__c;
                 }
                 if(invoice.Last_Processing_Date__c != null){
                    lastProcessingDate = invoice.Last_Processing_Date__c;
                    noOfDays = lastProcessingDate.daysBetween(system.today());
                 }
                 if(noOfDaysBetweenRetries == null){
                    noOfDaysBetweenRetries = 0;
                 }

                 try {
                     //If condition added by Siri:INVOICEIT-631:25-11-2015
                     if( noOfDays >= noOfDaysBetweenRetries || lastProcessingDate == null){
                         result = PaymentOperations.authorizeAndCharge(invoice.Id, null, null);
                         if(result != null && result.transactionObj != null && result.transactionObj.Id != null) {
                            if(result.transactionObj.Response_Status__c == CommonUtilClass.TRANSACTION_RESPONSE_STATUS_APPROVED) {
                                ++noOfSuccesfullTransaction;
                                totalTransactionsValue = totalTransactionsValue + result.transactionObj.Amount__c;
                                
                                // we are not passing payment run parameters to the gateway class, to avoid passing params to gateway class follow below ones
                                // in order to update the payment description for the relavant payment, therefore we are querying the payment to update 
                                // execution of batch size also 1, so that no problem of qurying , releated to ticket INVOICEIT-246
                                list<payment__c> lstPayment = [Select id from payment__c where Transaction__c =: result.transactionObj.Id LIMIT 1];
                                if(lstPayment.size() > 0){
                                    payment__c paymentToUpdateDescription = new payment__c(id = lstPayment[0].id, Payment_Description__c = 'Payment Scheduler: '+DateTime.now().format('MMM dd,YYYY')+  ' Run');
                                    update paymentToUpdateDescription;
                                }

                                
                             } else {
                                //it many be error or declined or held for review 
                                ++noOfFailedTransaction;
                                //Added by Siri: INVOICEIT-631: 25-11-2015
                                Invoice__c invoicesToUpdateFields = new Invoice__c( Id = invoice.id ,No_of_tries__c = ++noOfTries, Last_Processing_Date__c= system.today());
                                listOfInvoicesToUpdate.add(invoicesToUpdateFields);

                             }
                             result.transactionObj.Payment_Run__c = paymentRun.Id;
                             listOfTransactionsToUpdate.add(result.transactionObj);
                             
                         } else {
                            //it many be error or declined or held for review
                            ++noOfFailedTransaction;
                            errorLog += result.message+ '\n';
                            errorLog += ' Invoice Id : ' + invoice.Id + '\n';
                            errorLog += ' Invoice Name : ' + invoice.Name + '\n';
                            // Added by Dev M: SUP-543
                            CommonUtilClass.createFailedtransaction(invoice.Id, paymentRun.Id, result.message);

                            //Added by Siri:INVOICEIT-631:25-11-2015
                             Invoice__c invoicesToUpdateFields = new Invoice__c( Id = invoice.id ,No_of_tries__c = ++noOfTries, Last_Processing_Date__c= system.today());
                             listOfInvoicesToUpdate.add(invoicesToUpdateFields);
                         }
                         
                     }
                 }
                 catch(Exception ex) {
                    ++noOfFailedTransaction;
                    errorLog +=  ex.getTypeName() + ':' + ex.getMessage() + ':'  + ex.getLineNumber() + ':' + ex.getStackTraceString() + '\n';
                    errorLog += ' Invoice Id : ' + invoice.Id + '\n';
                    errorLog += ' Invoice Name : ' + invoice.Name + '\n';
                    // Added by Dev M: SUP-543
                    CommonUtilClass.createFailedtransaction(invoice.Id, paymentRun.Id, ex.getTypeName() + ':' + ex.getMessage() + ':'  + ex.getLineNumber());
                    
                    //Added by Siri:INVOICEIT-631: 25-11-2015
                    Invoice__c invoicesToUpdateFields = new Invoice__c( Id = invoice.id ,No_of_tries__c = ++noOfTries, Last_Processing_Date__c= system.today());
                    listOfInvoicesToUpdate.add(invoicesToUpdateFields);             
                 }
            }
         }
         
         global void finish(Database.BatchableContext BC) {
             
            if(errorLog == '') {
                paymentRun.Status__c = CommonUtilClass.STATUS_COMPLETED;    
            } else {
                paymentRun.Status__c = CommonUtilClass.STATUS_COMPLETED_WITH_ERRORS;
                paymentRun.Exception_Log__c = errorLog;
            }
            paymentRun.Completed_Time__c = system.now();
            paymentRun.Invoices_Processed__c = noOfInvoicesProcessed;
            paymentRun.Successful_Transactions__c = noOfSuccesfullTransaction;
            paymentRun.Failed_Transactions__c = noOfFailedTransaction;
            paymentRun.Total_Payment_Value__c = totalTransactionsValue;

            update paymentRun;
            
            if(!listOfTransactionsToUpdate.isEmpty()) {
                upsert listOfTransactionsToUpdate;
            }
            
            //Added by Siri:INVOICEIT-631:25-11-2015
            if(!listOfInvoicesToUpdate.isEmpty()){
                 Update listOfInvoicesToUpdate;
            }
        
            //Added by Siri:INVOICEIT-661
            BatchChargePaymentPlanInstallmentProcess.paymentRunRef = paymentRun;
            BatchChargePaymentPlanInstallmentProcess.paymentSchedulerRef = paymentScheduler;
            //Added by Lopa: INVOICEIT-644: 04-12-2015
            if(!Test.isRunningTest()){
                BatchChargePaymentPlanInstallmentProcess batchinstallmentObj = new BatchChargePaymentPlanInstallmentProcess(system.today());  
                Database.executeBatch(batchinstallmentObj,1);
            }

         }
    }