Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Layout_Fields__c.object
<CustomObject>
    <description>This object is to store the selected fields - column width  for the particular object as a record</description>
    <fields>
        <fullName>Selected_Fields__c</fullName>
        <label>Selected Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Layout Fields</label>
    <nameField>
        <label>Layout Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Layout Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>It will have description of IT Product</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>It will have the product code value</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <description>This will  have the Family Names Of Product</description>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <description>This will have Valid From Date of Product</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <description>This will have the Valid To Date of the Product</description>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>Cost_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Unit Cost Price</description>
        <inlineHelpText>Unit Cost Price</inlineHelpText>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <description>This will specify whether price is default or tiered</description>
        <inlineHelpText>Please refer to the user documentation for detailed information on what the different pricing models mean.
Search for &quot;Pricing Model&quot; in the documentation.</inlineHelpText>
        <label>Pricing Model</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Fee Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Per Unit Pricing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume Pricing</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime, weekly, monthly etc or usage(metered) based.</description>
        <label>Price Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>ProductRatePlanCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Product_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This holds the tiered pricing details for the Charge.</description>
    <fields>
        <fullName>End_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge_Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>Start Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestCreateProductsControllerNew.cls
@isTest(SeeALLData = false)
private with sharing class TestCreateProductsControllerNew {   
    public static String sPrefix = CommonUtilClass.getPrefix();
    static testMethod void createProductsController() {
        ControllerInsertCustomSettings c = new ControllerInsertCustomSettings();
        c.insertValues();
        list<Configuration__c> objects = new list<Configuration__c>();
        Configuration__c c1 = new Configuration__c(Name = 'NAVIGATION_FOR_PRODUCTRATEPLAN', Field_Type__c = 'Number', Description__c = 'This is used for product rate plan navigation in product page', NUMBER_VALUE__C = 2);
        Configuration__c c2 = new Configuration__c(Name = 'NAVIGATION_FOR_PRODUCTCHARGE', Field_Type__c = 'Number', Description__c = 'This is used for product rate plan charge navigation in product page', NUMBER_VALUE__C = 2);
        
        objects.add(c1);
        objects.add(c2);
        upsert objects;
        
        Currency__c currencyObj = new Currency__c(name = 'GBP', Currency_Symbol__c = '£1');
        insert currencyObj;

        Product__c product1 = new Product__c(Name = 'Default');
        ApexPages.Standardcontroller controller = new Apexpages.Standardcontroller(product1);
        CreateProductsController createProductsController1 = new CreateProductsController(controller);
        createProductsController1.saveProduct();
    
        Layout_Fields__c layoutFieldsProduct = new  Layout_Fields__c(Name=sPrefix+'Product__c',Selected_Fields__c ='Name-115');
        Layout_Fields__c layoutFieldsProductRateplan = new  Layout_Fields__c(Name=sPrefix+'Product_Rate_Plan__c',Selected_Fields__c ='Name-115');
        Layout_Fields__c layoutFieldsProductCharge = new  Layout_Fields__c(Name=sPrefix+'Product_Rate_Plan_Charge__c',Selected_Fields__c ='Name-115');
        
        insert layoutFieldsProduct;
        insert layoutFieldsProductRateplan;
        insert layoutFieldsProductCharge;
        
        Product__c product = new  Product__c(Name = 'Test Product',Valid_From_Date__c = Date.today(),Valid_To_Date__c = Date.today()+90,
                                          Product_Family__c = 'Default',Product_Code__c = 'Code1', Description__c = 'Product');
        insert  product;

        Product__c productNew = [SELECT Name FROM Product__c WHERE id =: product.id];
        System.assertEquals('Test Product', productNew.Name);
        
        list<Product_Rate_Plan__c> listofProductRatePlan = new list<Product_Rate_Plan__c>();
        Product_Rate_Plan__c productRatePlan1 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 1',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan2 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 2',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan3 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 3',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan4 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 4',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        listofProductRatePlan.add(productRatePlan1);
        listofProductRatePlan.add(productRatePlan2);
        listofProductRatePlan.add(productRatePlan3);
        listofProductRatePlan.add(productRatePlan4);
        insert listofProductRatePlan;

        list<Product_Rate_Plan_Charge__c> listProductRatePlanCharges = new list<Product_Rate_Plan_Charge__c>();       
        Product_Rate_Plan_Charge__c productRatePlanCharge1 = new Product_Rate_Plan_Charge__c(Name = 'Setup Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'One Time'      
        );

        Product_Rate_Plan_Charge__c productRatePlanCharge2 = new Product_Rate_Plan_Charge__c(Name = 'Monthly Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'Monthly'       
        );
        Product_Rate_Plan_Charge__c productRatePlanCharge3 = new Product_Rate_Plan_Charge__c(Name = 'Setup Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'One Time'      
        );

        Product_Rate_Plan_Charge__c productRatePlanCharge4 = new Product_Rate_Plan_Charge__c(Name = 'Monthly Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'Monthly'       
        );
        listProductRatePlanCharges.add(productRatePlanCharge1);
        listProductRatePlanCharges.add(productRatePlanCharge2);
        listProductRatePlanCharges.add(productRatePlanCharge3);
        listProductRatePlanCharges.add(productRatePlanCharge4);
        insert listProductRatePlanCharges;

        list<Product_Rate_Plan_Charge_Tier__c> listProductRatePlanChargesTiers = new list<Product_Rate_Plan_Charge_Tier__c>(); 
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 10,Start_Unit__c= 1,Unit_Price__c = 100, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[0].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier1 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 20,Start_Unit__c= 11,Unit_Price__c = 50, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[0].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier2 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 30,Start_Unit__c= 21,Unit_Price__c = 90, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[1].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier4 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c =1 ,Start_Unit__c= 10,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[1].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier3 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 20,Start_Unit__c= -1,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[2].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier5 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c =1 ,Start_Unit__c= 10,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[2].Id);
        
        listProductRatePlanChargesTiers.add(productrateplanchargetier);
        listProductRatePlanChargesTiers.add(productrateplanchargetier1);
        listProductRatePlanChargesTiers.add(productrateplanchargetier2);
        listProductRatePlanChargesTiers.add(productrateplanchargetier3);
        listProductRatePlanChargesTiers.add(productrateplanchargetier4);
        listProductRatePlanChargesTiers.add(productrateplanchargetier5);
        insert listProductRatePlanChargesTiers;

        ApexPages.Standardcontroller controller1 = new Apexpages.Standardcontroller(product);
        CreateProductsController createProductsController = new CreateProductsController(controller1);
        createProductsController.newRatePlanCharge();

        system.currentPageReference().getParameters().put('productrateplanchargeCounterfortier','1');
        createProductsController.addTier();
        createProductsController.newTier(); 
        createProductsController.saveAndClosePopup();

        system.currentPageReference().getParameters().put('productrateplanidtodelete',listofProductRatePlan[3].id);
        system.currentPageReference().getParameters().put('productrateplancountertodelete','1');
        createProductsController.removeRatePlan();

        system.currentPageReference().getParameters().put('productrateplanchargeidtodelete',listProductRatePlanCharges[3].id);
        system.currentPageReference().getParameters().put('productrateplanchargecountertodelete','1');
        createProductsController.saveProduct();
        createProductsController.saveAndClosePopup();
        createProductsController1.newTier();     
        
        system.currentPageReference().getParameters().put('ratePlanCounter','1');
        createProductsController.onClickRatePlan();
        createProductsController.newRatePlan();
        createProductsController.newRatePlanCharge();
        createProductsController.newRatePlan();
        createProductsController.newRatePlanCharge();
        createProductsController.newRatePlan();
        system.currentPageReference().getParameters().put('rateplanchargecounterfromcharges','10');
        createProductsController.removeRatePlanCharges(); 

        system.currentPageReference().getParameters().put('tieridtodelete',listProductRatePlanChargesTiers[0].id);
        system.currentPageReference().getParameters().put('tiercountertodelete','1');
        system.currentPageReference().getParameters().put('productRatePlanChargeCounterfromtier','5');
        createProductsController.removeTiers();

        list<ProductRatePlanClass> listOfProductRatePlanClass = createProductsController.productClass.getProductRatePlans();
        createProductsController.saveProduct();
        createProductsController.closePopup();
        createProductsController.cloneProduct();
        createProductsController.saveAndClosePopup();
        
        ApexPages.Standardcontroller controller2 = new Apexpages.Standardcontroller(product);
        CreateProductsController createProductsController2 = new CreateProductsController(controller2);        
        createProductsController2.newTier(); 
        createProductsController2.viewProductNewScreen();
        createProductsController2.saveAndClosePopup();
        createProductsController2.deleteProduct();
             
    }

    static testMethod void createProductsControllerNew() {
        ControllerInsertCustomSettings c = new ControllerInsertCustomSettings();
        c.insertValues();
        list<Configuration__c> objects = new list<Configuration__c>();
        Configuration__c c1 = new Configuration__c(Name = 'NAVIGATION_FOR_PRODUCTRATEPLAN', Field_Type__c = 'Number', Description__c = 'This is used for product rate plan navigation in product page', NUMBER_VALUE__C = 2);
        Configuration__c c2 = new Configuration__c(Name = 'NAVIGATION_FOR_PRODUCTCHARGE', Field_Type__c = 'Number', Description__c = 'This is used for product rate plan charge navigation in product page', NUMBER_VALUE__C = 2);
        
        objects.add(c1);
        objects.add(c2);
        upsert objects;
        
        Currency__c currencyObj = new Currency__c(name = 'GBP', Currency_Symbol__c = '£1');
        insert currencyObj;
        
        Layout_Fields__c layoutFieldsProduct = new  Layout_Fields__c(Name=sPrefix+'Product__c',Selected_Fields__c ='Name-115');
        Layout_Fields__c layoutFieldsProductRateplan = new  Layout_Fields__c(Name=sPrefix+'Product_Rate_Plan__c',Selected_Fields__c ='Name-115');
        Layout_Fields__c layoutFieldsProductCharge = new  Layout_Fields__c(Name=sPrefix+'Product_Rate_Plan_Charge__c',Selected_Fields__c ='Name-115');
        
        insert layoutFieldsProduct;
        insert layoutFieldsProductRateplan;
        insert layoutFieldsProductCharge;
        
        Product__c product = new  Product__c(Name = 'Test Product',Valid_From_Date__c = Date.today(),Valid_To_Date__c = Date.today()+90,
                                          Product_Family__c = 'Default',Product_Code__c = 'Code1', Description__c = 'Product');
        insert  product;

        Product__c product2 = [SELECT Name FROM Product__c WHERE id=:product.id];
        System.assertEquals('Test Product', product2.Name);
        
        list<Product_Rate_Plan__c> listofProductRatePlan = new list<Product_Rate_Plan__c>();
        Product_Rate_Plan__c productRatePlan1 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 1',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan2 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 2',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan3 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 3',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        Product_Rate_Plan__c productRatePlan4 = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan 4',
                Product__c = product.Id,
                Valid_From_Date__c = Date.today(),
                Valid_To_Date__c = Date.today()+90
        );
        listofProductRatePlan.add(productRatePlan1);
        listofProductRatePlan.add(productRatePlan2);
        listofProductRatePlan.add(productRatePlan3);
        listofProductRatePlan.add(productRatePlan4);
        insert listofProductRatePlan;

        list<Product_Rate_Plan_Charge__c> listProductRatePlanCharges = new list<Product_Rate_Plan_Charge__c>();       
        Product_Rate_Plan_Charge__c productRatePlanCharge1 = new Product_Rate_Plan_Charge__c(Name = 'Setup Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'One Time',
                Price_Format__c = 'Flat Fee Pricing'       
        );

        Product_Rate_Plan_Charge__c productRatePlanCharge2 = new Product_Rate_Plan_Charge__c(Name = 'Monthly Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'Monthly' ,
                Price_Format__c = 'Flat Fee Pricing'      
        );
        Product_Rate_Plan_Charge__c productRatePlanCharge3 = new Product_Rate_Plan_Charge__c(Name = 'Setup Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'One Time',
                Price_Format__c = 'Flat Fee Pricing'     
        );

        Product_Rate_Plan_Charge__c productRatePlanCharge4 = new Product_Rate_Plan_Charge__c(Name = 'Monthly Charges',
                CurrencyL__c = currencyObj.Id,
                Product_Rate_Plan__c = listofProductRatePlan[0].Id,
                Unit_Price__c = 1000,
                Cost_Price__c = 500,                                                                  
                Price_Type__c = 'Monthly',
                Price_Format__c = 'Flat Fee Pricing'       
        );
        listProductRatePlanCharges.add(productRatePlanCharge1);
        listProductRatePlanCharges.add(productRatePlanCharge2);
        listProductRatePlanCharges.add(productRatePlanCharge3);
        listProductRatePlanCharges.add(productRatePlanCharge4);
        insert listProductRatePlanCharges;

        list<Product_Rate_Plan_Charge_Tier__c> listProductRatePlanChargesTiers = new list<Product_Rate_Plan_Charge_Tier__c>(); 
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 10,Start_Unit__c= 1,Unit_Price__c = 100, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[0].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier1 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 20,Start_Unit__c= 11,Unit_Price__c = 50, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[0].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier2 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 30,Start_Unit__c= 21,Unit_Price__c = 90, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[1].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier4 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c =1 ,Start_Unit__c= 10,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[1].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier3 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c = 20,Start_Unit__c= -1,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[2].Id);
        Product_Rate_Plan_Charge_Tier__c productrateplanchargetier5 = new Product_Rate_Plan_Charge_Tier__c(End_Unit__c =1 ,Start_Unit__c= 10,Unit_Price__c = 30, Product_Rate_Plan_Charge__c = listProductRatePlanCharges[2].Id);
        
        listProductRatePlanChargesTiers.add(productrateplanchargetier);
        listProductRatePlanChargesTiers.add(productrateplanchargetier1);
        listProductRatePlanChargesTiers.add(productrateplanchargetier2);
        listProductRatePlanChargesTiers.add(productrateplanchargetier3);
        listProductRatePlanChargesTiers.add(productrateplanchargetier4);
        listProductRatePlanChargesTiers.add(productrateplanchargetier5);
        insert listProductRatePlanChargesTiers;

        ApexPages.Standardcontroller stdController = new Apexpages.Standardcontroller(product);
        CreateProductsControllerNew createProductsController = new CreateProductsControllerNew(stdController); 
        
        createProductsController.firstCharges();
        createProductsController.nextCharges();
        createProductsController.previousCharges();
        createProductsController.lastCharges();
        
        createProductsController.first();
        createProductsController.next();
        createProductsController.previous();
        createProductsController.last(); 
        
        createProductsController.editProduct();
        createProductsController.closeProductPopup();
        createProductsController.updateProduct();
        createProductsController.saveProduct();

        createProductsController.newRatePlan();
        createProductsController.saveClonedRatePlan();
        
        system.currentPageReference().getParameters().put('ratePlanCounter', '1');
        createProductsController.editRatePlan();
        createProductsController.saveRatePlan();
        
        system.currentPageReference().getParameters().put('cloneRatePlan',ProductCreationUtil.CLONE_RATEPLAN);
        createProductsController.cloneRatePlan();
        createProductsController.cloneRatePlanPopup();
        createProductsController.saveClonedRatePlan();
        createProductsController.closeRatePlanPopup();
        system.currentPageReference().getParameters().put('cloneRatePlan',ProductCreationUtil.CLONE_WITH_CHARGES);
        createProductsController.cloneRatePlan();
        createProductsController.cloneProduct();
        createProductsController.saveClonedProduct();
        createProductsController.saveClonedRatePlan();
        
        createProductsController.newCharge();
        createProductsController.saveCharge();
        createProductsController.closeChargePopup();
        
        system.currentPageReference().getParameters().put('chargeCounter','15');
        createProductsController.editCharges();
        createProductsController.saveCharge();
        
        createProductsController.closeOptionPopup();
        createProductsController.closeChargeOptionPopup();
        createProductsController.updateRateplan();

        system.currentPageReference().getParameters().put('tieridtodelete',listProductRatePlanChargesTiers[1].id);
        system.currentPageReference().getParameters().put('tiercountertodelete','1');
        system.currentPageReference().getParameters().put('productRatePlanChargeCounterfromtier','5');
        createProductsController.removeTiers();
        
        Id productrateplanidtodelete;
        Id chargeidtodelete;
        ProductClass productClass = createProductsController.productClass ;
        for(ProductRatePlanClass prpclass : productClass.productRatePlans) {   
            if(prpclass.productRatePlanCounter == 1) {
                productrateplanidtodelete = prpclass.productRatePlan.Id;
            }
            for(ProductRatePlanChargeClass  prpChargeClass : prpclass.productRatePlanChargeClass) {
                   if(chargeidtodelete == null) {
                    chargeidtodelete = prpChargeClass.productRatePlancharge.Id;
                    break;
                   }
                }        
        } 
        
        system.currentPageReference().getParameters().put('cloneCharge','CloneCharge');
        createProductsController.cloneCharge();

        system.currentPageReference().getParameters().put('chargeName','Monthly Charges');
        system.currentPageReference().getParameters().put('chargeCloneCounter','15');
        createProductsController.cloneChargesPopup();
        createProductsController.newTier(); 
        createProductsController.cloneCharge();
        createProductsController.saveClonedCharge();

        system.currentPageReference().getParameters().put('cloneCharge','CloneWithTiers');
        createProductsController.cloneCharge();
        createProductsController.saveClonedCharge();
        
        createProductsController.closeCloneChargePopup();
        createProductsController.closeSelectedChargesPopup();
        system.currentPageReference().getParameters().put('editSelected','editSelected');
        createProductsController.editSelectedCharges();
        createProductsController.onChangePriceFormat();
        
         system.currentPageReference().getParameters().put('chargeCounter','1');
        createProductsController.editCharges();
        
        createProductsController.newTier();
        createProductsController.onSelectAll();
        
        system.currentPageReference().getParameters().put('chargeidtodelete',listProductRatePlanCharges[3].id);
        system.currentPageReference().getParameters().put('chargecountertodelete','1');
        system.currentPageReference().getParameters().put('rateplancountertodelete','3');
        createProductsController.removeRatePlanCharges();
           
        system.currentPageReference().getParameters().put('ratePlanId',productrateplanidtodelete);
        system.currentPageReference().getParameters().put('counterForRatePlan','1');
        createProductsController.onClickRatePlan();
        
        system.currentPageReference().getParameters().put('Name','Charge1');
        system.currentPageReference().getParameters().put('selectedCurrency','GBP');
        system.currentPageReference().getParameters().put('selectedPriceType',ProductCreationUtil.PRICE_FORMAT_VOLUME);
        createProductsController.filterCharges();
        
        system.currentPageReference().getParameters().put('Name','');
        createProductsController.filterCharges();
        
        system.currentPageReference().getParameters().put('RatePlanName','Charge1');
        createProductsController.filterRatePlan();
        
        system.currentPageReference().getParameters().put('RatePlanName','');
        createProductsController.filterRatePlan();
        
        createProductsController.saveProductLayout();
        createProductsController.saveRatePlanLayout();
        createProductsController.saveChargesLayout();
        
        system.Test.StartTest();
        
        ApexPages.Standardcontroller stdController1 = new Apexpages.Standardcontroller(product);
        CreateProductsControllerNew createProductsController1 = new CreateProductsControllerNew(stdController1);
        
        productClass = createProductsController1.productClass ;
        for(ProductRatePlanClass prpclass : productClass.productRatePlans) {   
            if(prpclass.productRatePlanCounter == 1) {
                productrateplanidtodelete = prpclass.productRatePlan.Id;
            } 
            for(ProductRatePlanChargeClass  prpChargeClass : prpclass.productRatePlanChargeClass) {
               if(chargeidtodelete == null) {
                chargeidtodelete = prpChargeClass.productRatePlancharge.Id;
                break;
               }
            }   
        }
        system.currentPageReference().getParameters().put('ratePlanId',productrateplanidtodelete);
        system.currentPageReference().getParameters().put('counterForRatePlan','1');
        createProductsController.onClickRatePlan();
        
        system.currentPageReference().getParameters().put('productrateplanidtodelete',productrateplanidtodelete);
        system.currentPageReference().getParameters().put('productrateplancountertodelete','1');
        createProductsController.removeRatePlan();
        
        Product__c productObj = new  Product__c(Name = 'Test Product',Valid_From_Date__c = Date.today(),Valid_To_Date__c = Date.today()+90,
                                          Product_Family__c = 'Default',Product_Code__c = 'Code1', Description__c = 'Product');
        insert  productObj;
        
        // exception coverage
        ApexPages.Standardcontroller stdController2 = new Apexpages.Standardcontroller(productObj);
        CreateProductsControllerNew createProductsController2 = new CreateProductsControllerNew(stdController1);
        
        createProductsController2.filterCharges();
        createProductsController2.filterRatePlan();
        createProductsController2.saveClonedRatePlan();
        createProductsController2.saveClonedProduct();
        createProductsController2.saveRatePlan();
        createProductsController2.saveCharge();
        createProductsController2.saveProductLayout();
        createProductsController2.saveRatePlanLayout();
        createProductsController2.saveChargesLayout();
        createProductsController2.saveClonedCharge();
        createProductsController2.intilizeRatePlans();
        createProductsController2.intilizeCharges();
        createProductsController2.editChargesLayout();
        createProductsController2.closeRatePlanLayout();
        createProductsController2.editRatePlanLayout();
        createProductsController2.closeChargesLayout();
        createProductsController2.closeProductLayout();
        createProductsController2.editProductLayout();
        
        system.Test.stopTest(); 
        
        createProductsController.deleteProduct();
        
        CreateProductsControllerNew.getProductDetails(product.id);
        CreateProductsControllerNew.getProductRatePlan(listofProductRatePlan.get(0).id);
        CreateProductsControllerNew.getChargeTiers(listProductRatePlanCharges.get(0).id);

    }
    
}