Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Indicator__c</fullName>
        <label>Picklist Indicator</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Custom_Mappings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This holds all the custom mappings between the product catalog and the quotes/orders. Say you create a custom field &apos;abc&apos; in product object that has to be mapped to custom field xyz in order product, this is the place to configure that.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <label>Destination Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Object__c</fullName>
        <label>Destination Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Invoice IT Custom Mappings</label>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corresponding Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Orders created from this Quote</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Job_Product__c.object
<CustomObject>
    <description>The tier 1 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Job_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Job_Rate_Plan__c.object
<CustomObject>
    <description>The tier 2 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Job_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Currency code for the order charge that will match to the currency code of the Order.</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>It will have the product code value</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY() &gt;= Valid_From_Date__c &amp;&amp; (TODAY() &lt;= Valid_To_Date__c || ISBLANK(Valid_To_Date__c)), &quot;Active&quot;, IF(Valid_From_Date__c &gt; TODAY(), &quot;Future&quot; , &quot;Expired&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product_Catalog_Filter_Criteria__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used for filtering criteria of products.Users may filter products by currency or any other chosen field in the wizard screens.</description>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <label>Destination Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Object__c</fullName>
        <label>Destination Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Invoice IT Product Filter Criteria</label>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY() &gt;= Valid_From_Date__c &amp;&amp; (TODAY() &lt;= Valid_To_Date__c || ISBLANK(Valid_To_Date__c)), &quot;Active&quot;, IF(Valid_From_Date__c &gt; TODAY(), &quot;Future&quot; , &quot;Expired&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Based on the Currency the Products will be generated</description>
        <inlineHelpText>This Currency field is used in price displays for products to generate a Order from Quote</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Based on the status user will check the Quote is Active/Converted  or not</description>
        <inlineHelpText>This field is used to check the status for the Quote if it is Active/Converted/Cancelled/Expired
based on that the Quote will be generated.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 3 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up to Currency object</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestInvoiceITSetupController.cls
@isTest
    private class TestInvoiceITSetupController {
       public static String sPrefix = CommonUtilClass.getPrefix();
        static testMethod void testInvoiceItSetup() {
            list<Custom_Mappings__c> listCustomMapping = new list<Custom_Mappings__c>();
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = 'Name',Destination_Object__c = 'Job_Rate_Plan_Charge__c',Source_Field__c = 'Name',Source_Object__c = 'Quote_Rate_Plan_Charge__c', Name = 'q1',Category__c = 'Quote2Order'));
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = sPrefix+'Product_Code__c',Destination_Object__c = 'Job_Product__c',Source_Field__c = sPrefix+'Status__c',Source_Object__c = 'Product__c', Name = 'q4',Category__c = 'General'));
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = 'Name',Destination_Object__c = 'Quote__c',Source_Field__c = 'Name',Source_Object__c = 'Opportunity', Name = 'a3',Category__c = 'Opp2Quote'));
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = 'Name',Destination_Object__c = 'job__c',Source_Field__c = 'Name',Source_Object__c = 'Opportunity', Name = 'a309',Category__c = 'Opp2Order'));
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = 'Name',Destination_Object__c = 'Opportunity',Source_Field__c = 'Name',Source_Object__c = 'Quote__c', Name = 'a31',Category__c = 'Quote2Opportunity'));
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = 'Name',Destination_Object__c = 'Opportunity',Source_Field__c = 'Name',Source_Object__c = 'job__c', Name = 'a3091',Category__c = 'Order2Opportunity'));
            insert listCustomMapping;

            Custom_Mappings__c customMappings = [select Destination_Field__c From Custom_Mappings__c where id=:listCustomMapping[0].id];
            System.assertEquals('Name', customMappings.Destination_Field__c);
            
            Configuration__c configuration = new Configuration__c(Field_Type__c = 'String',Name = 'testing12',Category__c = 'General',Picklist_Indicator__c = 'listAccountFields');
            Configuration__c configuration1 = new Configuration__c(Field_Type__c = 'String',Name = 'testing23',Category__c = 'Opportunity');
            Configuration__c configuration2 = new Configuration__c(Field_Type__c = 'String',Name = 'testing234',Category__c = 'Quote',Picklist_Indicator__c = 'listQuoteFields');
            Configuration__c configuration3 = new Configuration__c(Field_Type__c = 'String',Name = 'testing567',Category__c = 'Order',Picklist_Indicator__c = 'listOrderFields');
            Configuration__c configuration4 = new Configuration__c(Field_Type__c = 'String',Name = 'testing7654321',Category__c = 'Invoice',Picklist_Indicator__c = 'listInvoiceGeneration');
            
            list<Configuration__c> lstConfig = new list<Configuration__c>();
            lstConfig.add(configuration);
            lstConfig.add(configuration1);
            lstConfig.add(configuration2);
            lstConfig.add(configuration3);
            lstConfig.add(configuration4);
            
            insert lstConfig;
            
            list<Product_Catalog_Filter_Criteria__c> listFilters = new list<Product_Catalog_Filter_Criteria__c>();
            listFilters.add(new Product_Catalog_Filter_Criteria__c(Destination_Field__c = 'CurrencyL__c',Destination_Object__c = 'Product_Rate_Plan_Charge__c',Source_Field__c = 'CurrencyL__c',Source_Object__c = 'Job__c', Name = 'a1'));
            listFilters.add(new Product_Catalog_Filter_Criteria__c(Destination_Field__c = 'CurrencyL__c',Destination_Object__c = 'Product_Rate_Plan_Charge__c',Source_Field__c = 'CurrencyL__c',Source_Object__c = 'Quote__c', Name = 'a2'));
            listFilters.add(new Product_Catalog_Filter_Criteria__c(Destination_Field__c = 'Name',Destination_Object__c = 'Product__c',Source_Field__c = 'Name',Source_Object__c = 'Job__c', Name = 'a3'));
            listFilters.add(new Product_Catalog_Filter_Criteria__c(Destination_Field__c = 'Name',Destination_Object__c = 'Product__c',Source_Field__c = 'Name',Source_Object__c = 'Quote__c', Name = 'a4'));
            listFilters.add(new Product_Catalog_Filter_Criteria__c(Destination_Field__c = 'CurrencyL__c',Destination_Object__c = 'Product_Rate_Plan_Charge__c',Source_Field__c = 'CurrencyL__c',Source_Object__c = 'Job__c', Name = 'a19013'));
            insert listFilters; 
            
            System.URL.getCurrentRequestUrl().toExternalForm();
            InvoiceITSetupController invSetup = new InvoiceITSetupController();
            
            invSetup.configurations = lstConfig;
            invSetup.saveInvoiceITSettings();
            
            System.currentPageReference().getParameters().put('category', 'General');
            invSetup.getCategory();
            
            System.currentPageReference().getParameters().put('category','Opportunity');
            invSetup.getCategory();
            System.currentPageReference().getParameters().put('category','Quote');
            invSetup.getCategory();
            System.currentPageReference().getParameters().put('category','Order');
            invSetup.getCategory();
            System.currentPageReference().getParameters().put('category','Invoice');
            invSetup.getCategory();
            //invSetup.filters = listFilters;
            invSetup.saveProductFilter_old();
            System.currentPageReference().getParameters().put('id', listFilters.get(0).id);
            invSetup.deleteFilterRow_old();
            
            invSetup.mappings = listCustomMapping;
            invSetup.addMappingRow_old();
            Custom_Mappings__c mapping = new Custom_Mappings__c();
            listCustomMapping.add(new Custom_Mappings__c(Destination_Field__c = sPrefix+'Product_Code__c',Destination_Object__c = 'Job_Product__c',Source_Field__c = sPrefix+'Status__c',Source_Object__c = 'Product__c', Name = 'q409876',Category__c = 'General'));
            //invSetup.saveCustomMapping_old();
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(0).id);
            invSetup.deleteMappingRow_old();
            
            string s = 'Job_Product__c';
            List<SelectOption> selOpts = invSetup.ObjectFieldsGet(s);
            
            invSetup.initProductFilterObjNames();
            invSetup.initObjNames();
            
            List<SelectOption> selOpts1 = invSetup.ObjectFieldsGetCustomMapping(s,'');
            string s1 = 'Opportunity_Product__c';
            List<SelectOption> selOpts2 = invSetup.ObjectFieldsGetCustomMapping(s1,'');
            
            System.currentPageReference().getParameters().put('objectCounter', 'productFilter-0-Source-Job__c');
            invSetup.ObjectFields();
            System.currentPageReference().getParameters().put('objectCounter', 'productFilter-0-Destination-Job__c');
            invSetup.destinationFields();
            System.currentPageReference().getParameters().put('objectCounter', 'productFilter-0-Source-Opportunity');
            invSetup.ObjectFields();
            System.currentPageReference().getParameters().put('objectCounter', 'productFilter-0-Destination-Opportunity');
            invSetup.destinationFields();
            System.currentPageReference().getParameters().put('objectCounter', 'customMapping-1-Source-General-Product_Rate_Plan__c');
            invSetup.ObjectFields();
            System.currentPageReference().getParameters().put('objectCounter', 'customMapping-1-Destination-General-Job_Rate_Plan__c');
            invSetup.destinationFields(); 
            
            PageReference pageRef9 = invSetup.refreshProductFilter();
            PageReference pageRef8 = invSetup.refreshCustomMapping();
            PageReference pageRef7 = invSetup.editPicklistSetupRecord();
            PageReference pageRef5 = invSetup.saveSelectedSetupValues();
            PageReference pageRef6 = invSetup.cancelPicklistSetUp();
            
            invSetup.addNewFilter();
            
            invSetup.addMappingRowGeneral();
            invSetup.addMappingRowQuote2Order();
            invSetup.addMappingRowOpp2Order();
            invSetup.addMappingRowOpp2Quote();
            invSetup.addMappingRowQuote2Opportunity();
            invSetup.addMappingRowOrder2Opportunity();
            PageReference pageRef = invSetup.saveCustomMappingGeneral();
            PageReference pageRef1 = invSetup.saveCustomMappingQuote2Order();
            PageReference pageRef2 = invSetup.saveCustomMappingOpp2Order();
            PageReference pageRef3 = invSetup.saveCustomMappingOpp2Quote();
            PageReference pageRef4 = invSetup.saveProductFilter();
            PageReference pageRef51 = invSetup.saveCustomMappingQuote2Opportunity();
            PageReference pageRef61 = invSetup.saveCustomMappingOrder2Opportunity();

            
            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listFilters.get(1).id);
            
            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(2).id);
            PageReference pageRef11 = invSetup.deleteMappingRowOpp2Quote();
            
            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(1).id);
            PageReference pageRef12 = invSetup.deleteMappingRowGeneral();
            
            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(0).id);
            
            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(3).id);
            PageReference pageRef14 = invSetup.deleteMappingRowOpp2Order();

            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(4).id);
            PageReference pageRef15 = invSetup.deleteMappingRowQuote2Opportunity();

            System.currentPageReference().getParameters().put('counter', '0');
            System.currentPageReference().getParameters().put('id', listCustomMapping.get(5).id);
            PageReference pageRef16 = invSetup.deleteMappingRowOrder2Opportunity();

        } 
        
        static testMethod void testQuickStartWizardController() {
            Configuration__c configuration = new Configuration__c(Field_Type__c = 'String',String_Value__c = 'status__c',Name = 'testing12',Category__c = 'General',Picklist_Indicator__c = 'listAccountFields',Quick_Screen_Id__c ='1');
            Configuration__c configuration1 = new Configuration__c(Field_Type__c = 'String',Name = 'testing23',String_Value__c = 'status__c',Category__c = 'Opportunity',Quick_Screen_Id__c ='2');
            Configuration__c configuration2 = new Configuration__c(Field_Type__c = 'String',Name = 'testing234',String_Value__c = 'status__c',Category__c = 'Quote',Picklist_Indicator__c = 'listQuoteFields',Quick_Screen_Id__c ='3');
            Configuration__c configuration3 = new Configuration__c(Field_Type__c = 'String',Name = 'testing567',String_Value__c = 'status__c',Category__c = 'Order',Picklist_Indicator__c = 'listOrderFields',Quick_Screen_Id__c ='4');
            Configuration__c configuration4 = new Configuration__c(Field_Type__c = 'String',Name = 'testing7654321',String_Value__c = 'status__c',Category__c = 'Invoice',Picklist_Indicator__c = 'listInvoiceGeneration',Quick_Screen_Id__c ='5');
            Configuration__c configuration5 = new Configuration__c(Field_Type__c = 'String',Name = 'INVOICEIT_HOME_POPUP');
            list<Configuration__c> lstConfig = new list<Configuration__c>();
            lstConfig.add(configuration);
            lstConfig.add(configuration1);
            lstConfig.add(configuration2);
            lstConfig.add(configuration3);
            lstConfig.add(configuration4);
            lstConfig.add(configuration5);
            
            insert lstConfig;
            
            Configuration__c config = [select Field_Type__c, Name from Configuration__c where id=:lstConfig[0].id];
            System.assertEquals('testing12', config.Name);
            
            QuickStartWizardController startWizardController = new QuickStartWizardController();
            System.currentPageReference().getParameters().put('QuickScreenId', '1');
            System.currentPageReference().getParameters().put('picklistIndicator', '1');
            PageReference pageRef = startWizardController.editPicklistSetupRecord();
            
            //modified by lopa
            startWizardController.getQuickScreen();
            
            System.currentPageReference().getParameters().put('QuickScreenId', '2');
            System.currentPageReference().getParameters().put('picklistIndicator', '2');
            PageReference pageRef1 = startWizardController.editPicklistSetupRecord();
            
            System.currentPageReference().getParameters().put('QuickScreenId', '3');
            System.currentPageReference().getParameters().put('picklistIndicator', '3');
            PageReference pageRef2 = startWizardController.editPicklistSetupRecord();
            
            System.currentPageReference().getParameters().put('QuickScreenId', '4');
            System.currentPageReference().getParameters().put('picklistIndicator', '4');
            PageReference pageRef3 = startWizardController.editPicklistSetupRecord();
            
            System.currentPageReference().getParameters().put('QuickScreenId', '5');
            System.currentPageReference().getParameters().put('picklistIndicator', '5');
            //startWizardController.isInstalled = true;
            PageReference pageRef4 = startWizardController.editPicklistSetupRecord();
            
            PageReference pageRef5 = startWizardController.saveInvoiceITSettings();
            PageReference pageRef6 = startWizardController.quickSaveInvoiceITSettings();
            
            PageReference pageRef7 = startWizardController.saveSelectedSetupValues();
            
            PageReference pageRef8 = startWizardController.cancelPicklistSetUp();
            PageReference pageRef9 = startWizardController.refreshPrevious();
            PageReference pageRef11 = startWizardController.cancelQuickStartWizard(); 
            
            PageReference pageRef12 = startWizardController.quickSaveStep2();
            PageReference pageRef13 = startWizardController.quickSaveStep3();
            PageReference pageRef14 = startWizardController.quickSaveStep4();
            
            startWizardController.constructFinalPicklist(lstConfig);
            startWizardController.showingOpptMessage();
            startWizardController.onLoadQuickStartWizard();
            startWizardController.exitQuickStartWizard();
            
            startWizardController.sQuickScreenId = '1';
            PageReference pageRef15 = startWizardController.saveSelectedSetupValues();
            
            startWizardController.sQuickScreenId = '2';
            PageReference pageRef16 = startWizardController.saveSelectedSetupValues();
            
            startWizardController.sQuickScreenId = '3';
            PageReference pageRef17 = startWizardController.saveSelectedSetupValues();
            
            startWizardController.sQuickScreenId = '4';
            PageReference pageRef18 = startWizardController.saveSelectedSetupValues();
            
        }
    }