Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Optional_Extra__c.object
<CustomObject>
    <description>Holds data about extra products to include in the Quote.</description>
    <fields>
        <fullName>Invoice_IT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice IT Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost_Price__c</fullName>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Selling_Price2__c</fullName>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Optional Extra</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optional Extras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Default Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <description>This will specify whether price is default or tiered</description>
        <inlineHelpText>Please refer to the user documentation for detailed information on what the different pricing models mean.
Search for &quot;Pricing Model&quot; in the documentation.</inlineHelpText>
        <label>Pricing Model</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Fee Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Per Unit Pricing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume Pricing</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>ProductRatePlanCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Product_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This holds the tiered pricing details for the Charge.</description>
    <fields>
        <fullName>End_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge_Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>Start Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost_Price__c</fullName>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Based on the Currency the Products will be generated</description>
        <inlineHelpText>This Currency field is used in price displays for products to generate a Order from Quote</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Quantity*Unit Cost</description>
        <inlineHelpText>Quantity*Unit Cost</inlineHelpText>
        <label>Total Cost Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerInsertOptionalExtra.cls
public with sharing class ControllerInsertOptionalExtra {

    private map<String, Configuration__c> mapConfiguration;
    public String searchstring {get;set;}
    public String displayfields {get; set;}
    public String objectname {get; set;}
    public String orderfield {get; set;}
    public String searchfields {get; set;}
    public String sProductsLimit {get; set;}

    public List<Product_Rate_Plan__c> listProductRatePlans {get;set;}
    public List<Product_Rate_Plan_Charge__c> listProductRatePlanCharges {get;set;}
    public List<Product_Rate_Plan_Charge__c> listSelectedProductRatePlanCharges {get;set;}
    public String selectedProductId {get;set;}
    public String selectedProductName {get;set;} 
    public boolean isMultipleRatePlans {get; set;}
    public boolean isRatePlanChargesExists {get; set;}
    public Quote__c quote {get;set;}

    private Optional_Extra__c optionalExtra;
    private list<Optional_Extra__c> listoptionalExtra;

    public ControllerInsertOptionalExtra(ApexPages.StandardController controller) {
        this.quote = (Quote__c)controller.getRecord();      
        mapConfiguration = Configuration__c.getAll();
        listSelectedProductRatePlanCharges = new List<Product_Rate_Plan_Charge__c>();
        displayfields = mapConfiguration.get('PRODUCT_DISPLAYFIELDS').String_Value__c; 
        objectname = mapConfiguration.get('PRODUCT_OBJECTNAME').String_Value__c;
        orderfield = mapConfiguration.get('PRODUCT_ORDERFIELD').String_Value__c;
        searchfields = mapConfiguration.get('PRODUCT_SEARCHFIELDS').String_Value__c;
        sProductsLimit = '' + (mapConfiguration.get('PRODUCT_SEARCH_LIMIT').Number_Value__c).intValue(); 
    }

    /**
     * This method returns ProductRatePlans of the SelectedProduct
     * @return PageReference
     */
    public PageReference getRatePlansForProduct() {
        try{
            selectedProductId = System.currentPageReference().getParameters().get('productId');
            selectedProductName = System.currentPageReference().getParameters().get('productName');
            if(selectedProductId != null) {
                map<String,String> searchMap = new map<String,String>();              
                DateTime dt = DateTime.Now();
                listProductRatePlans = QuoteCreationUtil.getProductRatePlans(selectedProductId,dt.Date(),searchMap);
            }
            if(listProductRatePlans.size() == 1) {
                isMultipleRatePlans = false;
                string selectedRatePlanId = listProductRatePlans.get(0).id;
                System.currentPageReference().getParameters().put('ratePlanId',selectedRatePlanId);
                getRatePlanChargesForRatePlan();
            }
            else if(listProductRatePlans.size() > 1) {
                isMultipleRatePlans = true;
            }
            else {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.INFO,System.Label.Product_ProductRatePlan);
                Apexpages.addMessage(errorMessage);
            }            

        }catch(Exception ex) {
            Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
            Apexpages.addMessage(errorMessage);
        }

        return null;
    }

    /**
     * This method returns ProductRatePlanCharges of the SelectedRatePlan
     * @return PageReference
     */  
    public PageReference getRatePlanChargesForRatePlan() {
        try {
            string selectedRatePlanId = System.currentPageReference().getParameters().get('ratePlanId'); 
            map<String,String> searchMap = new map<String,String>();   
            listProductRatePlanCharges = JobCreationUtil.getProductRatePlanCharges(selectedRatePlanId, quote.CurrencyL__c, searchMap);
            if(listProductRatePlanCharges.size() > 0) {
                boolean isExists = true;   
                for(Product_Rate_Plan_Charge__c prpc : listSelectedProductRatePlanCharges) {
                    if(prpc.Product_Rate_Plan__c == selectedRatePlanId){
                        Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.WARNING,system.Label.ProductRatePlanExist);
                        Apexpages.addMessage(errorMessage); 
                        isExists = false;
                        break;
                    }
                }
                if(isExists) {
                    isRatePlanChargesExists = true;
                    listSelectedProductRatePlanCharges.addAll(listProductRatePlanCharges);
                }
            }          
            else {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.WARNING,System.Label.Product_ProductRatePlan);
                Apexpages.addMessage(errorMessage);
            }
        }
        catch(Exception ex) {
            Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,System.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
            Apexpages.addMessage(errorMessage);
        }
        return null;
    }

    public PageReference removeCharges(){  
        String sRatePlanChargeId = System.currentPageReference().getParameters().get('ratePlanChargeId');
        Integer iCount = 0;
        for(Product_Rate_Plan_Charge__c prpc: listSelectedProductRatePlanCharges) {
            if(prpc.Id == sRatePlanChargeId) {
                listSelectedProductRatePlanCharges.remove(iCount);
                break;
            }
            iCount++;
        }
        return null;
    }

    public PageReference InsertOptionalExtras(){
        listoptionalExtra = new  list<Optional_Extra__c>();
        if(listSelectedProductRatePlanCharges.size() == 0) {
            Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.INFO,system.Label.OptionalExtrasNotSelected);
            Apexpages.addMessage(errorMessage); 
            return null;
        }
        else {
            try { 
                for(Product_Rate_Plan_Charge__c prpc: listSelectedProductRatePlanCharges) {
                    //This adjustment was done for Touchmore 07 April 2013 by MG
                    //Get the unit price populated by checking the price type for tiered, flat pricing, volume pricing etc
                    optionalExtra = new Optional_Extra__c();
                    optionalExtra.Quantity__c = prpc.Default_Quantity__c;
                    optionalExtra.Invoice_IT_Product__c = prpc.Product_Rate_Plan__r.Product__r.Id;
                    optionalExtra.Product_Rate_Plan__c = prpc.Product_Rate_Plan__c;
                    optionalExtra.Product_Rate_Plan_Charge__c = prpc.Id;
                    optionalExtra.Quote__c = quote.Id;
                    optionalExtra.Name = prpc.Product_Rate_Plan__r.Product__r.Name;
                    
                    if(prpc.Price_Format__c == CommonUtilClass.PRICE_FORMAT_TIERED){
                        populateOptionalExtraForTieredPricing(prpc, optionalExtra);
                        //If the unit price is null then this could have been beyond the available tiers. So throw an exception
                        if(optionalExtra.Unit_Selling_Price2__c == null)
                        {
                            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING,system.Label.Tieredlimit + ' -- "' + prpc.Product_Rate_Plan__r.Product__r.Name + '"'));
                            return null;    
                        }
                    }
                    if(prpc.Price_Format__c == CommonUtilClass.PRICE_FORMAT_VOLUME || prpc.Price_Format__c == CommonUtilClass.PRICE_FORMAT_FLAT_FEE){
                        populateOptionalExtraForVolumeOrFlatFeePricing(prpc, optionalExtra);
                        if(optionalExtra.Unit_Selling_Price2__c == null)
                        {
                            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.Tieredlimit + ' -- "' + prpc.Product_Rate_Plan__r.Product__r.Name + '"'));
                            return null;    
                        }
                    }
        
                    listoptionalExtra.add(optionalExtra);          
                }
                insert listoptionalExtra;
                listSelectedProductRatePlanCharges.clear();
                isRatePlanChargesExists = false;
                return new PageReference('/' + quote.Id);
            } catch(DMLException dMlEx){
                // Added by Naveen M ticket : INVOICEIT-310 
                Apexpages.Message errorMessage; 
                for (Integer i = 0; i < dMlEx.getNumDml(); i++)
                { 
                      errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dMlEx.getDmlMessage(i));
                      Apexpages.addMessage(errorMessage);      
                } 
                return null; 
            } catch(Exception ex) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,System.Label.ExceptionMessage + ex.getTypeName() + ':'+ex.getMessage() + ':'  + ex.getLineNumber());
                Apexpages.addMessage(errorMessage);
                return null;
            }
        }
    }
    
    public static void populateOptionalExtraForVolumeOrFlatFeePricing(Product_Rate_Plan_Charge__c  prpc, Optional_Extra__c optionalExtra)
    {
        if(optionalExtra.Quantity__c > 0) {
            list<Product_Rate_Plan_Charge_Tier__c> tempTiers = prpc.Product_Rate_Plan_Charge_Tiers__r;
            
            Product_Rate_Plan_Charge_Tier__c productChargeTier;
            integer iSize = tempTiers.Size();
            
            for(integer i = 0; i < iSize; i++) {
                productChargeTier = tempTiers[i];
                
                if( (productChargeTier.Start_Unit__c < = optionalExtra.Quantity__c && productChargeTier.End_Unit__c > = optionalExtra.Quantity__c)
                    ||
                    (productChargeTier.Start_Unit__c < = optionalExtra.Quantity__c && productChargeTier.End_Unit__c == null))
                {
                    optionalExtra.Unit_Cost_Price__c = productChargeTier.Unit_Cost_Price__c;
                    optionalExtra.Unit_Selling_Price2__c = productChargeTier.Unit_Price__c;
                    
                    if(prpc.Price_Format__c == CommonUtilClass.PRICE_FORMAT_VOLUME){
                        optionalExtra.Subtotal__c = optionalExtra.Quantity__c * optionalExtra.Unit_Selling_Price2__c;
                        if(optionalExtra.Unit_Cost_Price__c != null){
                            optionalExtra.Total_Cost__c = optionalExtra.Quantity__c * optionalExtra.Unit_Cost_Price__c;                         
                        }
                    }
                    else if(prpc.Price_Format__c == CommonUtilClass.PRICE_FORMAT_FLAT_FEE)
                    {
                        optionalExtra.Subtotal__c = optionalExtra.Unit_Selling_Price2__c;
                        optionalExtra.Total_Cost__c = optionalExtra.Unit_Cost_Price__c;
                    }
                }
            }
        }
    }
    public static void populateOptionalExtraForTieredPricing(Product_Rate_Plan_Charge__c  prpc, Optional_Extra__c optionalExtra) 
    {
        if(optionalExtra.Quantity__c > 0) {
            
            decimal usageAmount = 0;
            decimal costPrice = 0;
            integer remaningUsage = integer.ValueOf(optionalExtra.Quantity__c);
            integer usageQuantity = integer.ValueOf(optionalExtra.Quantity__c);
            boolean isTierExists = false;
            integer iSize;
           
            list<Product_Rate_Plan_Charge_Tier__c> tempTiers = prpc.Product_Rate_Plan_Charge_Tiers__r;
            Product_Rate_Plan_Charge_Tier__c productChargeTier;
            iSize = tempTiers.Size();
            
            for(integer i = 0; i < iSize; i++) {
                productChargeTier = tempTiers[i];
                if(usageQuantity >=  productChargeTier.Start_Unit__c) {
                    isTierExists = true;
                    integer diff;
                    
                    if(productChargeTier.End_Unit__c != null){
                        diff = integer.ValueOf(productChargeTier.End_Unit__c - productChargeTier.Start_Unit__c + 1);
                    }else{
                        diff = remaningUsage;
                    }
                    
                    if(remaningUsage <= diff) {
                        //calculate the sp
                        usageAmount +=  (decimal) (remaningUsage * productChargeTier.Unit_Price__c);
                        //calculate the cp
                        if(productChargeTier.Unit_Cost_Price__c != null && productChargeTier.Unit_Cost_Price__c > 0) {
                            costPrice +=  (decimal) (remaningUsage * productChargeTier.Unit_Cost_Price__c);
                        }
                    } else {
                        //calculate the sp
                        usageAmount +=  (decimal) (diff * productChargeTier.Unit_Price__c); 
                        //calculate the cp
                        if(productChargeTier.Unit_Cost_Price__c != null && productChargeTier.Unit_Cost_Price__c > 0) {
                            costPrice +=  (decimal) (diff * productChargeTier.Unit_Cost_Price__c); 
                        }
                    }
                    remaningUsage = remaningUsage - diff;
    
                    //this means it has reached end tier and remaning Usage is still present
                    if(i == tempTiers.Size() - 1 && remaningUsage > 0) {
                        //calculate the sp
                        usageAmount += (remaningUsage * productChargeTier.Unit_Price__c);
                        //calculate the cp
                        if(productChargeTier.Unit_Cost_Price__c != null && productChargeTier.Unit_Cost_Price__c > 0) {
                            costPrice +=  (remaningUsage * productChargeTier.Unit_Cost_Price__c);
                        }
                    }
               }
               
               if(i == (iSize - 1) && !isTierExists) {
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING,system.Label.Tieredlimit));
               }
            }
            
            optionalExtra.Unit_Selling_Price2__c = usageAmount/optionalExtra.Quantity__c;
            optionalExtra.Unit_Cost_Price__c = costPrice/optionalExtra.Quantity__c;
            optionalExtra.Total_Cost__c = costPrice;
            optionalExtra.Subtotal__c = usageAmount;
        } else {
            optionalExtra.Unit_Selling_Price2__c = 0;
            optionalExtra.Unit_Cost_Price__c = 0;
            optionalExtra.Total_Cost__c = 0;
            optionalExtra.Subtotal__c = 0;
            optionalExtra.Total_Cost__c = 0;
        }
    }
}