Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Optional_Extra__c.object
<CustomObject>
    <description>Holds data about extra products to include in the Quote.</description>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Optional Extras</relationshipLabel>
        <relationshipName>Optional_Extras</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optional Extra</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optional Extras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime, weekly, monthly etc or usage(metered) based.</description>
        <label>Price Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Based on the Currency the Products will be generated</description>
        <inlineHelpText>This Currency field is used in price displays for products to generate a Order from Quote</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <description>Subtotal - Discount Value</description>
        <inlineHelpText>Subtotal - Discount Value</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Quote_Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 1 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Quote Product Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 2 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <label>Quote Product</label>
        <referenceTo>Quote_Product__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Quote RatePlan Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 3 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up to Currency object</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <label>Net Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is Onetime/Recurring.</description>
        <label>Price Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Its the Price of selected Quantities</description>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>RatePlanCharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <label>Quote Rate Plan</label>
        <referenceTo>Quote_Rate_Plan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>This holds the Sequence in which the charges are created and appears on the pdf files</description>
        <inlineHelpText>This holds the Sequence in which the charges are created and appears on the pdf files</inlineHelpText>
        <label>Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerSendQuote.cls
public with sharing class ControllerSendQuote {
      public Quote__c quote {get;set;}
      public List<Quote_Product__c> listQuoteProducts = new List<Quote_Product__c>();
      public list<Quote_Rate_Plan_Charge__c> listQuoteRatePlanCharge {get;set;}
      public list<Optional_Extra__c> listOptionalExtra {get;set;}
      public Integer iCountOfOptionalExtra {get;set;}
      public string sLogo {set; get;}
      private map<Id,QuoteProductClass> mapQuoteProducts = new  map<Id,QuoteProductClass>();
      public list<Quote_Rate_Plan__c> listQuoteRatePlans = new  list<Quote_Rate_Plan__c>();
      public Boolean isOtherCharge{get;set;}
      public Boolean isOneTimeCharge{get;set;}
      public Boolean isMonthlyCharge{get;set;}
      public QuoteClass quoteClass {get;set;}
      public QuoteProductClass quoteProductClass {get;set;}
      public QuoteRatePlanClass quoteRatePlanClass {get;set;}
      public QuoteRatePlanChargeClass quoteRatePlanChargeClass = new QuoteRatePlanChargeClass();
      public decimal sumOfNetTotalOneTime {get;set;}
      public decimal sumOfSubTotalOneTime {get;set;}
      public decimal sumOfNetTotalMonthly {get;set;}
      public decimal sumOfSubTotalMonthly {get;set;}
      public decimal sumOfNetTotalOther {get;set;}
      public decimal sumOfSubTotalOther {get;set;}
      public String sPrefix {get; set;}      
      public ControllerSendQuote(ApexPages.StandardController stdController) {
      sPrefix = CommonUtilClass.getPrefix();
          this.quote = (Quote__c)stdController.getRecord();
          isOtherCharge = false;
          isOneTimeCharge = false;
          isMonthlyCharge = false;
          quoteClass = new QuoteClass();
          quoteClass.quote = quote;
          if(quote.id != null) {
              this.quote = QuoteCreationUtil.getQuote(quote.id);           
              listQuoteProducts = QuoteCreationUtil.getListQuoteProducts(quote.id);
              //add listQuoteProducts to quoteProductClass
              for(Quote_Product__c qp : listQuoteProducts) {
                  quoteProductClass = new QuoteProductClass();
                  quoteProductClass.quoteproduct = qp;
                  quoteClass.quoteProducts.add(quoteProductClass);
              }
              //get the list of quoteProduct Ids in to Map
              mapQuoteProducts = QuoteCreationUtil.getMapQuoteProducts(listQuoteProducts);
              Set<Id> mapQuoteProductKeyset = new Set<Id>();
              mapQuoteProductKeyset = mapQuoteProducts.keySet();
              List<Id> quoteProductIds = new List<Id>();
              Integer mapQuoteProductKeysetSize = mapQuoteProductKeyset.size();
              quoteProductIds.addAll(mapQuoteProductKeyset);
              listQuoteRatePlans = QuoteCreationUtil.getListQuoteRatePlans(quoteProductIds);
              if(listQuoteRatePlans != null ){
                  for(Quote_Rate_Plan__c qr : listQuoteRatePlans ) {
                      quoteProductClass = mapQuoteProducts.get(qr.Quote_Product__c);
                      quoteRatePlanClass = new QuoteRatePlanClass();
                      quoteRatePlanClass.quoterateplan = qr;
                      for(Quote_Rate_Plan_Charge__c qrpc : qr.Quote_Rate_Plan_Charge__r) {
                          quoteRatePlanChargeClass = new QuoteRatePlanChargeClass();
                          quoteRatePlanChargeClass.quoterateplancharge = qrpc;
                          quoteRatePlanClass.quoteRatePlanCharges.add(quoteRatePlanChargeClass);
                      }
                      quoteProductClass.quoteRatePlans.add(quoteRatePlanClass);
                      mapQuoteProducts.remove(qr.Quote_Product__c);
                      mapQuoteProducts.put(qr.Quote_Product__c,quoteProductClass);
                  }
                  quoteClass = new QuoteClass();
                  quoteClass.quote = quote;
                  for(QuoteProductClass qpc : mapQuoteProducts.values()) {
                      quoteClass.quoteProducts.add(qpc);
                  }                
              } 
          }
          
          /* Modified By     : Asish Behera:  25 Sept 2013: INVOICEIT-229
              Comments     : to print logo.  
          */ 
          list<StaticResource> listOfStaticResources = [SELECT Id,SystemModstamp FROM StaticResource WHERE Name = 'logo'];
          if(!listOfStaticResources.isEmpty()) {
              
             sLogo = '/resource/'+listOfStaticResources[0].SystemModStamp.getTime()+'/logo';
          } else {
              sLogo = (Configuration__c.getValues('COMPANY_LOGO').String_Value__c);
          }

          listQuoteProducts = QuoteCreationUtil.getListQuoteProducts(quote.id);

          string sQuery = 'SELECT ' + CommonUtilClass.getObjectFields(sPrefix+'Quote_Rate_Plan_Charge__c') + ',' 
                          + 'Quote_Rate_Plan__r.Quote_Product__r.name,Quote_Rate_Plan__r.SequenceNumber__c,Quote_Rate_Plan__r.Quote_Product__r.SequenceNumber__c,Quote_Rate_Plan__r.Quote_Product__r.Product_Code__c'
                          + ' FROM Quote_Rate_Plan_Charge__c where Quote_Rate_Plan__r.Quote_Product__c IN : listQuoteProducts Order By Quote_Rate_Plan__r.Quote_Product__r.SequenceNumber__c,Sequence_No__c,Quote_Rate_Plan__r.SequenceNumber__c';                
          sQuery = String.escapeSingleQuotes(sQuery);
          listQuoteRatePlanCharge = Database.query(sQuery);
          string sQueryOptional = 'SELECT ' + CommonUtilClass.getObjectFields(sPrefix+'Optional_Extra__c')
                                  + ', Product_Rate_Plan_Charge__r.CurrencyL__r.Currency_Symbol__c'
                                  + ' From Optional_Extra__c'
                                  + ' Where Quote__c = ' + '\'' + String.escapeSingleQuotes(quote.id) + '\'';
          listOptionalExtra = Database.query(sQueryOptional);
          iCountOfOptionalExtra = listOptionalExtra.Size();
          
          //checking is there any other charge except one time or monthly
          list<Quote_Rate_Plan_Charge__c> listofOtherChargesExceptMonthandOne;
          listofOtherChargesExceptMonthandOne = [SELECT id,Name, Quote_Rate_Plan__c,Price_Type__c,Quote__c
                                                 FROM Quote_Rate_Plan_Charge__c
                                                 WHERE Quote__c = :quote.id AND (Price_Type__c !='One Time' AND Price_Type__c !='Monthly')];
         
          //checking for One time Charge
          list<Quote_Rate_Plan_Charge__c> listofOtherChargesOneTime;
          listofOtherChargesOneTime = [SELECT id,Name, Quote_Rate_Plan__c,Price_Type__c,Quote__c
                                                 FROM Quote_Rate_Plan_Charge__c
                                                 WHERE Quote__c = :quote.id AND Price_Type__c = 'One Time'];
          
          //checking for Monthly Charge
          list<Quote_Rate_Plan_Charge__c> listofOtherChargesExceptMonthly;
          listofOtherChargesExceptMonthly = [SELECT id,Name, Quote_Rate_Plan__c,Price_Type__c,Quote__c
                                                 FROM Quote_Rate_Plan_Charge__c
                                                 WHERE Quote__c = :quote.id AND Price_Type__c ='Monthly'];
                                                 
         AggregateResult[] groupedResultsOfChargeOneTime = [SELECT sum(Net_Total__c) priceSum,sum(Price__c) subtotalSum,Quote_Rate_Plan__r.Quote_Product__r.Quote__c QuoteId 
                                                            FROM Quote_Rate_Plan_Charge__c 
                                                            WHERE Quote_Rate_Plan__r.Quote_Product__r.Quote__c = :quote.id
                                                            AND Price_Type__c = 'One Time'
                                                            GROUP BY Quote_Rate_Plan__r.Quote_Product__r.Quote__c
                                                            ];
         AggregateResult[] groupedResultsOfChargeMonthly = [SELECT sum(Net_Total__c) priceSum,sum(Price__c) subtotalSum,Quote_Rate_Plan__r.Quote_Product__r.Quote__c QuoteId 
                                                            FROM Quote_Rate_Plan_Charge__c 
                                                            WHERE Quote_Rate_Plan__r.Quote_Product__r.Quote__c = :quote.id
                                                            AND Price_Type__c ='Monthly'
                                                            GROUP BY Quote_Rate_Plan__r.Quote_Product__r.Quote__c
                                                            ];
         AggregateResult[] groupedResultsOfChargeOthers = [SELECT sum(Net_Total__c) priceSum,sum(Price__c) subtotalSum,Quote_Rate_Plan__r.Quote_Product__r.Quote__c QuoteId 
                                                            FROM Quote_Rate_Plan_Charge__c 
                                                            WHERE Quote_Rate_Plan__r.Quote_Product__r.Quote__c = :quote.id
                                                            AND (Price_Type__c !='One Time' AND Price_Type__c !='Monthly')
                                                            GROUP BY Quote_Rate_Plan__r.Quote_Product__r.Quote__c
                                                            ];                                                                                                      
          
         for(AggregateResult aggResult : groupedResultsOfChargeOneTime) {
                  sumOfNetTotalOneTime = (decimal) aggResult.get('priceSum');
                  sumOfSubTotalOneTime = (decimal) aggResult.get('subtotalSum');
         }
         
         for(AggregateResult aggResult : groupedResultsOfChargeMonthly) {
                  sumOfNetTotalMonthly = (decimal) aggResult.get('priceSum');
                  sumOfSubTotalMonthly = (decimal) aggResult.get('subtotalSum');
         }
         
         for(AggregateResult aggResult : groupedResultsOfChargeOthers) {
                  sumOfNetTotalOther = (decimal) aggResult.get('priceSum');
                  sumOfSubTotalOther = (decimal) aggResult.get('subtotalSum');
         }
         
         if(listofOtherChargesExceptMonthandOne.size() == 0){
             isOtherCharge = true;
         }
         
         if(listofOtherChargesOneTime.size() > 0){
             isOneTimeCharge = true;
         }
         
         if(listofOtherChargesExceptMonthly.size() > 0){
             isMonthlyCharge = true;
         }
      }
      
  }