Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Quote_Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 1 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice IT Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Quote Product Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 2 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <label>Quote Product</label>
        <referenceTo>Quote_Product__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Quote RatePlan Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 3 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <label>Quote Rate Plan</label>
        <referenceTo>Quote_Rate_Plan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>This holds the Sequence in which the charges are created and appears on the pdf files</description>
        <inlineHelpText>This holds the Sequence in which the charges are created and appears on the pdf files</inlineHelpText>
        <label>Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <fields>
        <fullName>End_Unit__c</fullName>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>Quote_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge_Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <label>Start Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost_Price__c</fullName>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>Q-TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassQuoteProductsInlineAJS.cls
global with sharing class ClassQuoteProductsInlineAJS {
            public string sCharges {get; set;}
            public string sortingOrder{get; set;}
            public String sPrefix {get; set;}
            public ClassQuoteProductsInlineAJS(ApexPages.StandardController controller) {
                    sPrefix = CommonUtilClass.getPrefix();
                    Quote__c quoteObj = (Quote__c)controller.getRecord();
                    sCharges = getChargeFieldSetvalue(quoteObj.Id);
            }
            Global string getChargeFieldSetvalue(Id QuoteId) {
                    list<string> chargesFields = new list<string>();
                    map<string,string> mapOfChargeFieldandLabel =  new map<string,string>();
                    map<string,string> mapOfChargeFieldValues;
                    list<sobject> sObj = new list<sobject>();
                    list<Object> listofCharge = new list<Object>(); 
                    JSONGenerator generator = JSON.createGenerator(true);
                    if(QuoteId != null){
                            String query = 'SELECT ';
                            String apiName = '';
                            //Getting the parent fields from the field set i.e, QuoteProduct
                            for(Schema.FieldSetMember quoteProductFieldSet : SObjectType.Quote_Product__c.FieldSets.ProductFieldsInline.getFields()) {
                                    query += 'Quote_Rate_Plan__r.Quote_Product__r.'+quoteProductFieldSet.getFieldPath() + ', ';
                                    mapOfChargeFieldandLabel.put('Quote_Rate_Plan__r.Quote_Product__r.'+quoteProductFieldSet.getFieldPath(),quoteProductFieldSet.getLabel());
                                    chargesFields.add('Quote_Rate_Plan__r.Quote_Product__r.'+quoteProductFieldSet.getFieldPath());
                            }
                            //Getting the child fields from the field set i.e, Charges
                            for(Schema.FieldSetMember chargeFieldSet : SObjectType.Quote_Rate_Plan_Charge__c.FieldSets.Quote_Detail_Page.getFields()) {
                                    query += chargeFieldSet.getFieldPath() + ', ';
                                    mapOfChargeFieldandLabel.put(chargeFieldSet.getFieldPath(),chargeFieldSet.getLabel());
                                    chargesFields.add(chargeFieldSet.getFieldPath());
                            }
                            chargesFields.add('Id');
                            chargesFields.add('Quote_Rate_Plan__r.Quote_Product__r.Product__r.Name');
                            mapOfChargeFieldandLabel.put('Id','Id');
                            mapOfChargeFieldandLabel.put('Quote_Rate_Plan__r.Quote_Product__r.Product__r.Name','pName');
                            if(query.contains('Sequence_No__c'))
                                query += 'Id,Quote_Rate_Plan__r.Quote_Product__r.Product__r.Name FROM Quote_Rate_Plan_Charge__c WHERE Quote__c=:QuoteId ORDER BY  Quote_Rate_Plan__r.Quote_Product__r.SequenceNumber__c,Sequence_No__c';
                            else
                                query += 'Id,Sequence_No__c,Quote_Rate_Plan__r.Quote_Product__r.Product__r.Name FROM Quote_Rate_Plan_Charge__c WHERE Quote__c=:QuoteId ORDER BY  Quote_Rate_Plan__r.Quote_Product__r.SequenceNumber__c,Sequence_No__c';
                            sObj = Database.query(query);
                            generator.writeStartArray();
                            for(sobject obj : sObj) {
                                    generator.writeStartObject();   
                                    for(string api : chargesFields) {                       
                                            // If it contains the Quote_Rate_Plan__r in the API that means it is the parent fields
                                            if(api.contains('Quote_Rate_Plan__r')) {
                                                            apiName = api.replace('Quote_Rate_Plan__r.Quote_Product__r.', '');
                                                     
                                                            if(string.valueOf(obj.get('Sequence_No__c')) != null && string.valueOf(obj.get('Sequence_No__c')) == '1' && apiName.contains('Product__r') && string.valueOf(obj.getSobject('Quote_Rate_Plan__r').getSobject('Quote_Product__r').get('Product__c')) != null) {
                                                                generator.writeStringField(mapOfChargeFieldandLabel.get(api), string.valueOf(obj.getSobject('Quote_Rate_Plan__r').getSobject('Quote_Product__r').getSobject('Product__r').get('Name')));
                                                            } else if(!apiName.contains('Product__r') && string.valueOf(obj.get('Sequence_No__c')) != null && string.valueOf(obj.get('Sequence_No__c')) == '1' && string.valueOf(obj.getSobject('Quote_Rate_Plan__r').getSobject('Quote_Product__r').get(''+apiName)) != null) {
                                                                    generator.writeStringField(mapOfChargeFieldandLabel.get(api), string.valueOf(obj.getSobject('Quote_Rate_Plan__r').getSobject('Quote_Product__r').get(''+apiName)));
                                                            } else {
                                                                    generator.writeStringField(mapOfChargeFieldandLabel.get(api),'');
                                                            }  
                                                            
                                            } else {
                                                    if(string.valueOf(obj.get(api)) != null) 
                                                            generator.writeStringField(mapOfChargeFieldandLabel.get(api),string.valueOf(obj.get(api)));
                                                    else 
                                                            generator.writeStringField(mapOfChargeFieldandLabel.get(api),'');             
                                            }
                                    }
                                    generator.writeEndObject();
                            }
                            generator.writeEndArray(); 
                    }
                    String jsonString = generator.getAsString();
                    return jsonString;
            }
            @RemoteAction
            Global static list<Quote_Rate_Plan_Charge_Tier__c> getChargeTiers(String sChargeId) {
                    list<Quote_Rate_Plan_Charge_Tier__c> listOfProductRatePlanChargeTier = new list<Quote_Rate_Plan_Charge_Tier__c>();
                    if(sChargeId != null && sChargeId != '') {
                            listOfProductRatePlanChargeTier = [SELECT End_Unit__c,Start_Unit__c,Unit_Cost_Price__c,Unit_Price__c,Name FROM Quote_Rate_Plan_Charge_Tier__c WHERE Quote_Rate_Plan_Charge__c =: sChargeId];    
                    }
                    return listOfProductRatePlanChargeTier;
            } 
    }