src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Preferred_Billing_Day__c</fullName>
        <description>The preferred Billing Day for this Order.</description>
        <inlineHelpText>Some calendar months don&apos;t have the 30th or the 31st day. If you select 31 as the day for invoicing and the current month has only 30 days,30 will be used instead.</inlineHelpText>
        <label>Preferred Billing Day of the month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Symbol__c</fullName>
        <description>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Obsolete_Symbol</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Delivery Type like Print,Email or both.If it selected as email or both then the email is sent to the Billing Contact on invoice.</description>
        <label>Delivery Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email &amp; Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it checked means Email has been sent to the customer.</description>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to contact for Shipping Contact</description>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Shipping Contact)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target  Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestControllerSendInvoice.cls
@isTest(oninstall = false)
    public with sharing class TestControllerSendInvoice {
         public static testMethod void testBatchClassGroupByAccount() {
            ControllerInsertCustomSettings ControllerInsertCustomSettings = new ControllerInsertCustomSettings();
            ControllerInsertCustomSettings.insertValues();

            Currency__c currency2 = new Currency__c(name = 'GBP', Symbol__c = '£1',Currency_Symbol__c='£');
            insert currency2;
            
            integer m = system.today().day();
            string s = string.ValueOf(m);
            
            Account account = new Account(name = 'Test Account',Preferred_Billing_Day__c = s);
            insert account;
            
            Account account1 = [SELECT Name From Account WHERE id=: account.id];
            System.assertEquals('Test Account', account1.Name);

            Contact contact =  new Contact(LastName = 'Sandeep',accountId = account.Id,MailingCountry = 'UK',Email = 'abc@gmail.com');
            insert contact ;
            
            Currency__c currency1 = [SELECT Id, Name, Currency_Symbol__c
                                     FROM Currency__c
                                     WHERE Name = 'GBP' 
                                     AND Currency_Symbol__c = '£'
                                     LIMIT 1];
            

            Invoice__c invoiceObj = new Invoice__c(Account__c = account.Id,
                                                Billing_Contact__c = contact.Id,
                                                Shipping_Contact__c = contact.Id,
                                                CurrencyL__c = currency1.Id, 
                                                Target_Date__c = Date.today(),
                                                Delivery_Type__c = 'Both',
                                                Invoice_Status__c = CommonUtilClass.STATUS_DRAFT
                                               
                                                );
            insert invoiceObj;

            Invoice__c invoiceObj1 = new Invoice__c(Account__c = account.Id,
                                                Billing_Contact__c = contact.Id,
                                                Shipping_Contact__c = contact.Id,
                                                CurrencyL__c = currency1.Id, 
                                                Target_Date__c = Date.today(),
                                                Delivery_Type__c = 'Both',
                                                Email_Sent__c = true,
                                                Invoice_Status__c = CommonUtilClass.STATUS_DRAFT
                                               
                                                );
            insert invoiceObj1;

            ApexPages.Standardcontroller standardController = new Apexpages.Standardcontroller(invoiceObj);
            ControllerSendInvoice  controllerSendInvoice1 = new ControllerSendInvoice(standardController);
            controllerSendInvoice1.emailInvoice();
            
            Configuration__c configuration = Configuration__c.getValues('INVOICE_EMAIL_TEMPLATE');
            configuration.String_Value__c = '00XU0000000IXSF';
            update configuration;
            
            ApexPages.Standardcontroller standardController1 = new Apexpages.Standardcontroller(invoiceObj);
            ControllerSendInvoice  controllerSendInvoice = new ControllerSendInvoice(standardController1);
            controllerSendInvoice.emailInvoice();
            controllerSendInvoice.backToInvoice();

            ApexPages.Standardcontroller standardController2 = new Apexpages.Standardcontroller(invoiceObj1);
            ControllerSendInvoice  controllerSendInvoice2 = new ControllerSendInvoice(standardController2);
            controllerSendInvoice2.emailInvoice();
           
        }

    }