src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>When is the last date of invoice to be paid.</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_State__c</fullName>
        <label>Invoice State</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Proforma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Processing_Date__c</fullName>
        <label>Last Processing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_Tries__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Batch__c</fullName>
        <label>Payment Batch</label>
        <picklist>
            <picklistValues>
                <fullName>Batch 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Payment_Date__c</fullName>
        <label>Preferred Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Payment Plan. We will give the option to select the Payment Plan.</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment_Plan__c.object
<CustomObject>
    <description>This object acts as a place holder for defining the Payment Plan and acts as master table for configurations.</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Payment_Scheduler__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payment Schedulers</relationshipLabel>
        <relationshipName>Payment_Schedulers2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Apex Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Batch__c</fullName>
        <label>Payment Batch</label>
        <picklist>
            <picklistValues>
                <fullName>Batch 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Options__c</fullName>
        <label>Payment Options</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_date_and_time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</description>
        <inlineHelpText>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Once</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Scheduler</label>
    <nameField>
        <label>Payment Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/RunSchedulerPayment.cls
global with sharing class RunSchedulerPayment implements Schedulable {
        global void execute(SchedulableContext context) {
            String cronId = context.getTriggerId();
            
            if(cronId.Length() == 18) {
                cronId = cronId.substring(0,cronId.length()-3);
            } 
            
            Payment_Scheduler__c paymentScheduler = [SELECT Type__c, Name, Start_date_and_time__c, Currency__c, Payment_Options__c, Payment_Batch__c
                                                     FROM Payment_Scheduler__c 
                                                     WHERE JobId__c =: cronId];
            
            string todaysDate = '' + system.today();
            todaysDate = todaysDate.replace(' 00:00:00', '');

            //Added by Siri related to INVOICEIT-631 on 25-11-2015
            Decimal noOfMaximumRetries = Configuration__c.getValues('PAYMENT_NO_OF_RETRIES').Number_Value__c;
            if(noOfMaximumRetries == null){
              noOfMaximumRetries = 0; 
            }

            // modified by ram 27- 5-2013 jira-INVOICEIT-184, dded the where condition Invoice_State is not equals to proforma.

            // Added Order__r.Payment_Plan__c = null for INVOICEIT-630, by DL, we are not charging the payment plan invoices here AND condition added by Siri and "Last_Processing_Date__c, No_of_tries__c" fields in query for INVOICEIT-631 on 25-11-2015

            String query = 'SELECT Id, Name,Last_Processing_Date__c, No_of_tries__c From Invoice__c WHERE Invoice_Status__c = \'' + CommonUtilClass.STATUS_POSTED + '\''
                           + ' AND CurrencyL__c = \'' + paymentScheduler.Currency__c + '\''
                           + ' AND Invoice_State__c != \'' + CommonUtilClass.STATUS_PROFORMA + '\''
                           + ' AND Account__r.Payment_Method__c != null'
                           + ' AND Unpaid_Amount__c > 0 '
                           + ' AND Order__r.Payment_Plan__c = null '
                           + ' AND No_of_tries__c < '+noOfMaximumRetries;
            
            // modified by Laxman Rao M, jira-INVOICEIT-376, call the batch class only if the Payment_Options field is not null

            if(paymentScheduler.Payment_Options__c != null) {
                query = query + ' AND (';
                for(string option : paymentScheduler.Payment_Options__c.split(';') ) {
                    query = query + ' Account__r.Payment_Method__r.Payment_Method__c =\'' + option + '\' OR';
                }
                query = query.substring(0, query.length()-2);
                query = query + ' )';
                
                //Modified by Laxman 10 may 2013 Jira - INVOICEIT-171, If INVOICE_TO_BE_CHARGED_ON is due date then query by due date else if it is invoice date then query by inoice date

                string invoicedToBeChargedOn = Configuration__c.getValues('INVOICE_TO_BE_CHARGED_ON').String_Value__c;             
                if(invoicedToBeChargedOn != null && invoicedToBeChargedOn == CommonUtilClass.INVOICE_DATE) {
                    query += ' AND Invoice_Date__c <= ' + todaysDate;   
                }
                else if(invoicedToBeChargedOn != null && invoicedToBeChargedOn == CommonUtilClass.PREFERRED_PAYMENT_DATE){
                    query += ' AND Preferred_Payment_Date__c <= ' + todaysDate;
                }
                else {
                    query += ' AND Due_Date__c <= ' + todaysDate;
                }
                //Added by dhanalakshmi for INVOICEIT-612 to filter the invoices based on payment batch type
                if(paymentScheduler.Payment_Batch__c != null) {
                    query += ' AND Payment_Batch__c  = \'' + paymentScheduler.Payment_Batch__c + '\'';
                } else {
                    query += ' AND Payment_Batch__c  = ' + paymentScheduler.Payment_Batch__c + '';
                }          
        
                ID batchprocessid = Database.executeBatch(new BatchTransactions(query, paymentScheduler), 1);
            }
        }
    }