src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestClassAfterOnPaymentMethod.cls
// This class contains unit tests for validating the behavior of ClassAfterOnPaymentMethod classes 
     //Created By Asish
     
    @isTest
    private class TestClassAfterOnPaymentMethod {

        static testMethod void testMethodForClassAfterOnPaymentMethod() {
            
            
            try{
                Account account = new Account(Name = 'Test Account');
                insert account;
                
                system.assert(account.Name == 'Test Account');
                Payment_Method__c paymethod = new Payment_Method__c();
                paymethod.Account__c = account.Id;
                paymethod.Default__c = false;
                insert paymethod;
                 
                Payment_Method__c newPaymethod = new Payment_Method__c();
                newPaymethod.Account__c = account.Id;
                newPaymethod.Default__c = false;
                insert newPaymethod;
                
                map<Id,Payment_Method__c> mapOfPaymethod = new map<Id,Payment_Method__c>();
                mapOfPaymethod.put(paymethod.id,paymethod);
                
                map<Id,Payment_Method__c> newMapOfPaymethod = new map<Id,Payment_Method__c>();
                newMapOfPaymethod.put(newPaymethod.id,newPaymethod);
                
                ClassAfterOnPaymentMethod clsObj = new ClassAfterOnPaymentMethod();
                clsObj.map_AccountId_PaymentMethod = mapOfPaymethod;
               
                ClassAfterOnPaymentMethod.PAYMENTMETHOD_AFTER_PROCESSING_COMPLETE = false;
                paymethod.Default__c = true;
                upsert paymethod;
                 
                
                
                List<Account> listOfAccounts = new List<Account>();
                set<id> setOfAccountIds = new set<id>();
                setOfAccountIds.add(newPaymethod.Account__c);
                listOfAccounts.add(account);
                
                list<Payment_Method__c> listOfPaymentMethods = new list<Payment_Method__c>();
                listOfPaymentMethods.add(paymethod);
                listOfPaymentMethods.add(newPaymethod);
                
                
                ClassAfterOnPaymentMethod.PAYMENTMETHOD_AFTER_PROCESSING_COMPLETE = false;
                newPaymethod.Default__c = true;
                upsert newPaymethod;
                
            }   
            catch(Exception Ex){
            
            }
           
            
        }
    }