src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default payment Gateway proposed by the User</description>
        <inlineHelpText>This field will pick  the Default Payment Gateway at Account level</inlineHelpText>
        <label>Default Payment Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <description>Indicates the Name of the Currency</description>
        <inlineHelpText>Indicates the Name of the Currency</inlineHelpText>
        <label>Currency Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Gateway__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Configuration object. The administrator should create one Account for the appropriate Payment Gateway.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Delivery Type like Print,Email or both.If it selected as email or both then the email is sent to the Billing Contact on invoice.</description>
        <label>Delivery Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email &amp; Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>This is the total Discount provided on this Invoice.</description>
        <inlineHelpText>This is the total Discount provided on this Invoice.</inlineHelpText>
        <label>Discount Value</label>
        <summarizedField>Invoice_Lines__c.Discount_Value__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to contact for Shipping Contact</description>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Shipping Contact)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target  Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <description>Shows the total amount of VAT for all invoice lines that has been applied to the Invoice</description>
        <inlineHelpText>The total amount of VAT for all invoice lines</inlineHelpText>
        <label>VAT</label>
        <summarizedField>Invoice_Lines__c.VAT__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Invoice_Lines__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>The Discount Value to be applied on the Subtotal.</description>
        <inlineHelpText>The Discount Value to be applied on the Subtotal.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Amount__c</fullName>
        <description>Quantity * Unit Price</description>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Line_Name__c</fullName>
        <label>Line Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Job2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <formula>CurrencyL__r.Currency_Symbol__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency Symbol</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>Discount offered on this Order</description>
        <inlineHelpText>Discount offered on this Order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary(Shipping) Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Shipping Contact)</relationshipLabel>
        <relationshipName>Job1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <description>Quantity * Unit Price</description>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/TestControllerVirtualTerminal.cls
@isTest(oninstall = false)
    private with sharing class TestControllerVirtualTerminal {
        static testMethod void controllerVirtualTerminal() {
            ControllerInsertCustomSettings ControllerInsertCustomSettings = new ControllerInsertCustomSettings();
            ControllerInsertCustomSettings.insertValues();
            
            Configuration__c c13 = new Configuration__c(Name = 'DEFAULT_CURRENCY', STRING_VALUE__C = 'GBP', Field_Type__c = 'String', Description__c = 'Mention the ISO code of your default currency here. Say GBP');
            upsert c13;
            

            Account account = new Account(Name = 'Test Account');
            insert account;

            Account account1 = [Select Name From Account Where id=: account.id];
            System.assertEquals('Test Account', account1.Name);

            list<Contact> listContacts = new list<Contact>();
            listContacts.add(new Contact(LastName = 'Sandeep',accountId = account.Id,MailingCountry = 'UK',Email ='laxmanrao.564@gmail.com'));
            listContacts.add(new Contact(LastName = 'Vinod',accountId = account.Id, MailingCountry = 'USA',Email = 'laxmanrao.564@gmail.com'));
            insert listContacts;

            map<string,Currency__c> mapOfCurrencyValuesToInserted = new map<string,Currency__c>();
            mapOfCurrencyValuesToInserted.put('EUR', new Currency__c(Name = 'EUR',  Currency_Symbol__c = '€', Currency_Name__c = 'Euro'));
            mapOfCurrencyValuesToInserted.put('GBP', new Currency__c(Name = 'GBP',  Currency_Symbol__c = '£', Currency_Name__c = 'United Kingdom Pound'));
            mapOfCurrencyValuesToInserted.put('USD', new Currency__c(Name = 'USD',  Currency_Symbol__c = '$', Currency_Name__c = 'United States Dollar'));
            mapOfCurrencyValuesToInserted.put('AUD', new Currency__c(Name = 'AUD',  Currency_Symbol__c = '$', Currency_Name__c = 'Australia Dollar'));
            mapOfCurrencyValuesToInserted.put('CAD', new Currency__c(Name = 'CAD',  Currency_Symbol__c = '$', Currency_Name__c = 'Canada Dollar'));
            mapOfCurrencyValuesToInserted.put('JPY', new Currency__c(Name = 'JPY',  Currency_Symbol__c = '¥', Currency_Name__c = 'Japan Yen'));
            mapOfCurrencyValuesToInserted.put('INR', new Currency__c(Name = 'INR',  Currency_Symbol__c = 'Rs', Currency_Name__c = 'India Rupee'));
            mapOfCurrencyValuesToInserted.put('CHF', new Currency__c(Name = 'CHF',  Currency_Symbol__c = 'CHF', Currency_Name__c = 'Switzerland Franc'));
            mapOfCurrencyValuesToInserted.put('NZD', new Currency__c(Name = 'NZD',  Currency_Symbol__c = '$', Currency_Name__c = 'New Zealand Dollar'));
            mapOfCurrencyValuesToInserted.put('CNY', new Currency__c(Name = 'CNY',  Currency_Symbol__c = '¥', Currency_Name__c = 'Chinese Yuan'));
            insert mapOfCurrencyValuesToInserted.values();

            Job__c job = new Job__c(Account__c = account.id,Billing_Contact__c = listContacts.get(0).Id,Shipping_Contact__c = listContacts.get(1).Id, Sub_Total__c = 100, Discount_Value__c = 0, CurrencyL__c = mapOfCurrencyValuesToInserted.get('USD').Id);
          
            insert job;

            Invoice__c invoice1 = new Invoice__c(Account__c = account.id,Billing_Contact__c = listContacts.get(0).Id,Shipping_Contact__c = listContacts.get(1).Id,
            CurrencyL__c = mapOfCurrencyValuesToInserted.get('USD').Id, Target_Date__c = Date.today(),Delivery_Type__c = 'Both',Invoice_Status__c = CommonUtilClass.STATUS_POSTED);

            Invoice__c invoice2 = new Invoice__c(Account__c = account.id,Billing_Contact__c = listContacts.get(0).Id,Shipping_Contact__c = listContacts.get(1).Id,
            CurrencyL__c = mapOfCurrencyValuesToInserted.get('USD').Id, Target_Date__c = Date.today(),Delivery_Type__c = 'Both',Invoice_Status__c = CommonUtilClass.STATUS_POSTED);

            Invoice__c invoice3 = new Invoice__c(Account__c = account.id,Billing_Contact__c = listContacts.get(0).Id,Shipping_Contact__c = listContacts.get(1).Id,
            CurrencyL__c = mapOfCurrencyValuesToInserted.get('USD').Id, Target_Date__c = Date.today(),Delivery_Type__c = 'Both',Invoice_Status__c = CommonUtilClass.STATUS_POSTED);

            list<Invoice__c> invoices = new list<Invoice__c>();
            invoices.add(invoice1);
            invoices.add(invoice2);
            invoices.add(invoice3);
            insert invoices;

            list<Invoice_Lines__c> listInvoiceLines = new list<Invoice_Lines__c>();
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(0).id, Line_Name__c = 'Broadband Installation For L',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(0).id, Line_Name__c = 'Broadband Installation For X',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(0).id, Line_Name__c = 'Broadband Installation For M',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));

            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(1).id, Line_Name__c = 'Broadband Installation For L',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(1).id, Line_Name__c = 'Broadband Installation For X',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(1).id, Line_Name__c = 'Broadband Installation For M',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));

            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(2).id, Line_Name__c = 'Broadband Installation For L',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(2).id, Line_Name__c = 'Broadband Installation For X',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            listInvoiceLines.add(new Invoice_Lines__c(Invoice__c = invoices.get(2).id, Line_Name__c = 'Broadband Installation For M',Quantity__c = 1,Unit_Price__c = 40.00,VAT__c = 8.00,Line_Amount__c = 40.00,Job__c = job.Id));
            insert listInvoiceLines;

            ApexPages.Standardcontroller standardController = new Apexpages.Standardcontroller(account);
            system.currentPageReference().getParameters().put('Id', account.Id);
            ControllerVirtualTerminal controllerVirtualTerminal1 = new ControllerVirtualTerminal(standardController);

            //insert Gateway 
            Gateway__c gateway = new Gateway__c(Active__c = true, Default__c = true, Gateway_Type__c = 'PayPal', Test_Mode__c = true, Merchant_ID__c = '22LbQ9b7', Security_Key__c = '8Fh7VnPV3e6h4b4S', Merchant_Seal_User_Id__c = '8Fh7VnPV3e6h4b4S...');
            insert gateway;        

            Payment_Method__c paymentMethod = new Payment_Method__c(Card_Expiration_Month__c = '12', Card_Expiration_Year__c = '2016', Billing_First_Name__c = 'Sandeep', Billing_Last_Name__c = 'M', CVV__c = '123', Card_Type__c = 'Master',Card_Number__c = '420000000000000', Account__c = account.Id);
            insert paymentMethod;
            
            
            list<Payment_Method__c> paymentMethods = new list<Payment_Method__c>();
            Payment_Method__c paymentMethod1 = new Payment_Method__c(Card_Expiration_Month__c = '12', Card_Expiration_Year__c = '2016', Billing_First_Name__c = 'Sandeep', Billing_Last_Name__c = 'M', CVV__c = '123', Card_Type__c = 'Master',Card_Number__c = '420000000000000', Account__c = account.Id);
            paymentMethods.add(paymentMethod1);
            Payment_Method__c paymentMethod2 = new Payment_Method__c(Card_Expiration_Month__c = '12', Card_Expiration_Year__c = '2016', Billing_First_Name__c = 'Sandeep1', Billing_Last_Name__c = 'M', CVV__c = '123', Card_Type__c = 'Master',Card_Number__c = '420000000000000', Account__c = account.Id);
            paymentMethods.add(paymentMethod2);
            insert paymentMethods;
            
            ControllerVirtualTerminal controllerVirtualTerminal = new ControllerVirtualTerminal(standardController);

            controllerVirtualTerminal.processPaymentRedirect();  
            controllerVirtualTerminal.selectedValue = paymentMethod.Id;  
            controllerVirtualTerminal.isNone = false;               
            controllerVirtualTerminal.paymentMethod.Billing_First_Name__c = 'Sandeep';
            controllerVirtualTerminal.paymentMethod.Billing_Last_Name__c = 'M';
            controllerVirtualTerminal.paymentMethod.Card_Type__c = 'Master';
            controllerVirtualTerminal.paymentMethod.Card_Number__c = '420000000000000';
            controllerVirtualTerminal.paymentMethod.CVV__c = '123';
            controllerVirtualTerminal.paymentMethod.Card_Expiration_Month__c = '12';
            controllerVirtualTerminal.paymentMethod.Card_Expiration_Year__c = '2016';
            controllerVirtualTerminal.sSaveCardDetails = 'yes';
            controllerVirtualTerminal.paymentMethod.Account__c = account.Id;
            controllerVirtualTerminal.processPayment();

            gateway.Default__c = false;
            update gateway;
            Gateway__c gatewayWireCard = new Gateway__c(Active__c = true, Default__c = true, Gateway_Type__c = CommonUtilClass.GATEWAY_TYPE_WIRECARD, Test_Mode__c = true, Merchant_ID__c = '22LbQ9b7', Security_Key__c = '8Fh7VnPV3e6h4b4S');
            insert gatewayWireCard;
       
            // For Invoice
            ApexPages.Standardcontroller standardControllerInvoice = new Apexpages.Standardcontroller(invoices.get(0));
            system.currentPageReference().getParameters().put('Id', invoices.get(0).id);
            ControllerVirtualTerminal controllerVirtualTerminalInvoice = new ControllerVirtualTerminal(standardControllerInvoice);
            controllerVirtualTerminalInvoice.selectedValue = '';  
            controllerVirtualTerminalInvoice.isNone = true;    
            controllerVirtualTerminalInvoice.dAmount = 10.00;

            controllerVirtualTerminalInvoice.paymentMethod.Billing_First_Name__c = 'Sandeep';
            controllerVirtualTerminalInvoice.paymentMethod.Billing_Last_Name__c = 'M';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Type__c = 'Master';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Number__c = '420000000000000';
            controllerVirtualTerminalInvoice.paymentMethod.CVV__c = '123';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Expiration_Month__c = null;
            controllerVirtualTerminalInvoice.paymentMethod.Card_Expiration_Year__c = null;
            controllerVirtualTerminalInvoice.sSaveCardDetails = 'yes';
            controllerVirtualTerminal.paymentMethod.Account__c = account.Id;
            controllerVirtualTerminalInvoice.processPayment();

            controllerVirtualTerminalInvoice.paymentMethod.Billing_First_Name__c = 'Sandeep';
            controllerVirtualTerminalInvoice.paymentMethod.Billing_Last_Name__c = 'M';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Type__c = 'Master';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Number__c = '420000000000000';
            controllerVirtualTerminalInvoice.paymentMethod.CVV__c = '123';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Expiration_Month__c = '12';
            controllerVirtualTerminalInvoice.paymentMethod.Card_Expiration_Year__c = '2016';
            controllerVirtualTerminalInvoice.sSaveCardDetails = 'yes';
            controllerVirtualTerminal.paymentMethod.Account__c = account.Id;
            controllerVirtualTerminalInvoice.processPayment();

            system.currentPageReference().getParameters().put('Id', account.Id);
            ControllerVirtualTerminal controllerVirtualTerminalAccount = new ControllerVirtualTerminal(standardController);
            c13.STRING_VALUE__C ='';
            upsert c13;
            ControllerVirtualTerminal controllerVirtualTerminalAccount1 = new ControllerVirtualTerminal(standardController);
            
            // cover catch blocks
            Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(invoices.get(0));
            ControllerVirtualTerminal controllerVirtualTerminalObj = new ControllerVirtualTerminal(stdController);
            controllerVirtualTerminalObj.processPaymentRedirect();
            controllerVirtualTerminalObj.processPayment();
            ControllerSitePaymentProcess controllerSitePaymentProcessObj = new ControllerSitePaymentProcess();
             
        }
       
    }