src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BrainTree_Customer_ID__c</fullName>
        <description>On first creation of token Customer ID will populate</description>
        <inlineHelpText>This field will auto populate when ever the token is generated for the first time</inlineHelpText>
        <label>BrainTree Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default payment Gateway proposed by the User</description>
        <inlineHelpText>This field will pick  the Default Payment Gateway at Account level</inlineHelpText>
        <label>Default Payment Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src- Version 4.19/objects/Gateway__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Configuration object. The administrator should create one Account for the appropriate Payment Gateway.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exact_ID_Security_Key__c</fullName>
        <description>Required for first data and Authorize.net CIM Payment Gateway</description>
        <inlineHelpText>Required for first data and Authorize.net CIM Payment Gateway</inlineHelpText>
        <label>Exact ID Security Key</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Gateway_Type__c</fullName>
        <label>Gateway Type</label>
        <picklist>
            <picklistValues>
                <fullName>Authorize.net</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WireCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FirstData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize.net CIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stripe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SagePay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BrainTree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource_CC_Token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <description>Also know as:
&quot;API Login&quot; on Authorize.net
&quot;Merchant Login&quot; on PayPal(Pay Flow Pro)</description>
        <inlineHelpText>Also know as:
&quot;API Login&quot; on Authorize.net
&quot;Merchant Login&quot; on PayPal(Pay Flow Pro)</inlineHelpText>
        <label>Merchant ID</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Security_Key__c</fullName>
        <description>Also known as:
&quot;Transaction Key&quot; on Authorize.net
&quot;Password&quot; on PayPal(Payflow Pro)
&quot;Secret Key&quot; on Stripe</description>
        <inlineHelpText>Also known as:
&quot;Transaction Key&quot; on Authorize.net
&quot;Password&quot; on PayPal(Payflow Pro)
&quot;Secret Key&quot; on Stripe</inlineHelpText>
        <label>Merchant Security Key</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Test_Mode__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Test Mode</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CVV__c</fullName>
        <label>CVV</label>
        <length>5</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Month__c</fullName>
        <label>Card Expiration Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Year__c</fullName>
        <label>Card Expiration Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Encrypted_Card_Number__c</fullName>
        <description>Holds the generated encrypt card value, especially used for the Eway Gateway.</description>
        <inlineHelpText>System use only</inlineHelpText>
        <label>Encrypted Card Number</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name_on_Card__c</fullName>
        <label>Name on Card</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_ID__c</fullName>
        <label>Payment Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>BrainTree Token</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerForGenerateTokenForBrainTree.cls
public with sharing class ControllerForGenerateTokenForBrainTree {
         
        public Account account {get;set;}
        public Payment_Method__c paymentMethod {get;set;}
        public boolean isRender{get;set;}
        private string sHttpEndPoint = '';
        private string MERCHANT_KEY = '';
        private string PUBLIC_KEY = '';
        private string PRIVATE_KEY = '';
        Gateway__c gateway;
        
        public ControllerForGenerateTokenForBrainTree(ApexPages.StandardController stdController){
            this.account = (Account)stdController.getRecord();
            account = [Select Name, Id, BrainTree_Customer_ID__c, Gateway__c,BillingStreet, BillingState, BillingPostalCode, BillingCountry, BillingCity, Website, Phone From Account WHERE Id =: this.account.Id];
            paymentMethod = new Payment_Method__c();
            isRender = true;
            
            paymentMethod.Account__c = account.id;
            
            list<Gateway__c> listOfGateway = new list<Gateway__c>();
               if(account.Gateway__c == null) {
                    listOfGateway = InvoicingUtilClass.getDefaultGateway();
                    if(!listOfGateway.isEmpty()){
                        gateway = listOfGateway.get(0);   
                    }else{
                        Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING, system.Label.Gateway_Warning));
                        isRender = false;
                        return;
                    }
                 
               } else {
                   gateway = InvoicingUtilClass.getGateway(account.Gateway__c);
               }
              
           if(gateway.Gateway_Type__c != CommonUtilClass.GATEWAY_TYPE_BRAINTREE) {
              Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.label.BT_GatewayInfo));
              isRender = false;
           } 
        }
        
        public pagereference generateToken(){
             try {
                  this.MERCHANT_KEY = gateway.Merchant_ID__c;
                  this.PUBLIC_KEY = gateway.Security_Key__c;
                  this.PRIVATE_KEY = gateway.Exact_ID_Security_Key__c;
                  
                // sandbox and live, using common endpoint Url
                //this determines is it sandbox or live
                if(gateway.Test_Mode__c) {
                    sHttpEndPoint = CommonUtilClass.ENDPOINT_BRAINTREE_SANDBOX;
                }else{
                    sHttpEndPoint = CommonUtilClass.ENDPOINT_BRAINTREE_PRODUCTION;
                }

                if(account.BrainTree_Customer_ID__c == null){
                    sHttpEndPoint = sHttpEndPoint + '/token/create';
                }else{
                    sHttpEndPoint = sHttpEndPoint + '/customer/token';
                }
                
                //Framing request body
                string sRequestBody = frameHttpRequestData();
                //call the exteernal system  
                sendHttpRequest(sRequestBody,sHttpEndPoint);  
                    
                if(parameters.get(system.Label.success) == system.Label.true && parameters.get(system.Label.success) != null){
                    Payment_Method__c paymentMethodTocheck;
                    if(paymentMethod.Default__c == true){
                        list<Payment_Method__c> paymentMethods = InvoicingUtilClass.getDefaultMethodForAccount(account.id);
                        if(!paymentMethods.isEmpty()) {
                            paymentMethodTocheck = paymentMethods.get(0);    
                            paymentMethodTocheck.Default__c = false;
                            paymentMethodTocheck.Active__c = false;
                            update paymentMethodTocheck;    
                        }                                      
                    }
                    
                    paymentMethod.Payment_Profile_ID__c = parameters.get(system.Label.customerId);
                    paymentMethod.Token__c = parameters.get(system.Label.token);
                    paymentMethod.Encrypted_Card_Number__c = parameters.get(system.Label.uniqueNumberIdentifier);

                    paymentMethod.Name_on_Card__c = null;
                    paymentMethod.Card_Type__c = null;
                    paymentMethod.CVV__c = null;
                    if(paymentMethod.Card_Number__c != null){
                        paymentMethod.Card_Number__c = paymentMethod.Card_Number__c.substring((paymentMethod.Card_Number__c.Length() - 4));
                    }
                    
                    paymentMethod.Card_Expiration_Month__c = null;
                    paymentMethod.Card_Expiration_Year__c = null;

                    insert paymentMethod;
                    
                    if(account.BrainTree_Customer_ID__c == null){
                        Account accountObj = new Account(Id = account.Id, BrainTree_Customer_ID__c = parameters.get(system.Label.customerId));
                        upsert accountObj;
                    }
                    
                    pagereference ref = new pagereference('/'+account.id);
                    return ref;
                }else{
                    Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.GATEWAY_ERROR + parameters.get(system.Label.message)));
                    return null;
                }
             }catch(Exception ex) {
                 Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                 return null;
            }    
             
           return null;
        }
        
        private map<string, string> parameters;
        public void sendHttpRequest(string requestBody,String endpoint){
            parameters = new map<string, string>();
            if(!system.test.isRunningTest()) {
                HttpRequest req = new HttpRequest();
                req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                req.setEndpoint(endpoint);
                req.setMethod('POST');
                req.setBody(requestBody);
                req.setTimeout(20*1000);
                Http h = new Http();
                HttpResponse res = h.send(req);
                string sHttpResponseBody = res.getBody();
                if((sHttpResponseBody.contains(system.Label.token) 
                        || sHttpResponseBody.contains(system.Label.success) 
                        || sHttpResponseBody.contains(system.Label.creditCard) 
                        || sHttpResponseBody.contains(system.Label.uniqueNumberIdentifier) 
                         ) && sHttpResponseBody != null
                        ){
                   
               Map<String, Object> map_JsonString  = (Map<String, Object>)JSON.deserializeUntyped(sHttpResponseBody);
               Map<String, Object>  mapchildObject = (Map<String, Object>)map_JsonString.get(system.Label.token);
                
                for(String s : mapchildObject.keyset()){
                    Map<String, Object>  mapchildObjectNew = (Map<String, Object>)mapchildObject.get(system.Label.creditCard);
                    parameters.put(system.Label.success,string.valueof((boolean)mapchildObject.get(system.Label.success)));
                    if(parameters.get(system.Label.success) == system.Label.true){
                         for(String s1 : mapchildObjectNew.keyset()){
                            parameters.put(system.Label.token,string.valueof((string)mapchildObjectNew.get(system.Label.token)));
                            parameters.put(system.Label.uniqueNumberIdentifier,string.valueof((string)mapchildObjectNew.get(system.Label.uniqueNumberIdentifier)));
                            parameters.put(system.Label.customerId,string.valueof((string)mapchildObjectNew.get(system.Label.customerId)));
                      }
                    }else{
                        parameters.put(system.Label.message,string.valueof((string)mapchildObject.get(system.Label.message)));
                    }
                } 
                }else{
                    Map<String, Object> map_JsonString = (Map<String, Object>)JSON.deserializeUntyped(sHttpResponseBody);
                    parameters.put(system.Label.message,(string)map_JsonString.get(System.Label.Error));

                } 
            } else {
                 parameters.put(string.valueof(system.Label.success),system.Label.true);
                 parameters.put(System.Label.processorResponseCode,'1000');
                 parameters.put(System.Label.processorAuthorizationCode,'000000');
                 parameters.put(System.Label.processorResponseText,System.Label.Approved);
                 parameters.put(System.Label.id,'3g278y');
            }
        } 
        
        public string frameHttpRequestData(){
            string sRequestBody = 'merchant=' + MERCHANT_KEY +'&publickey='+PUBLIC_KEY+'&privatekey='+PRIVATE_KEY;
            if(paymentMethod.Card_Number__c != null){
                sRequestBody += '&cardno='+paymentMethod.Card_Number__c;
            }
            if(paymentMethod.CVV__c != null){
                sRequestBody += '&cvv='+paymentMethod.CVV__c;
            }
            if(paymentMethod.Name_on_Card__c != null){
                sRequestBody += '&cardholdername='+ paymentMethod.Name_on_Card__c;
            }
            if(paymentMethod.Card_Expiration_Month__c != null){
                sRequestBody += '&mm='+paymentMethod.Card_Expiration_Month__c;
            }
            if(paymentMethod.Card_Expiration_Year__c != null){
                sRequestBody += '&yy='+paymentMethod.Card_Expiration_Year__c;
            }
            //Check whether it is pointing to production or sandbox
            if(gateway.Test_Mode__c) {
                sRequestBody += '&environment=Sandbox';
            } else {
                sRequestBody += '&environment=Production';
            }
            //starting of payment method basic info
            if(account.Name != null) 
               sRequestBody += '&c_fname='+account.Name;
            if(account.Name != null) 
                sRequestBody += '&c_company='+account.Name;
            if(account.website != null) 
                sRequestBody += '&c_website='+account.website;
            if(account.Phone != null) 
               sRequestBody += '&c_phone='+account.Phone; 
            // ending of payment details
            
            // this is to identify the customer id to store the details
            if(account.BrainTree_Customer_ID__c != null)
                sRequestBody += '&customerId='+account.BrainTree_Customer_ID__c; 
            // starting of customer details    
            if(account.Name != null)
                sRequestBody += '&b_fname='+account.Name; 
            if(account.BillingStreet != null)
               sRequestBody += '&b_street='+account.BillingStreet; 
            if(account.BillingCity != null)
                sRequestBody += '&b_city='+account.BillingCity; 
            if(account.BillingState != null)
                sRequestBody += '&b_state='+account.BillingState; 
            if(account.BillingPostalCode != null)
                sRequestBody += '&b_postal='+account.BillingPostalCode; 
            if(account.BillingCountry != null)
               sRequestBody += '&b_country='+account.BillingCountry; 
            // ending of customer details

            return sRequestBody;
        }
    }