src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Profile_ID__c</fullName>
        <description>Payment Profile id is generated for Authorize.net CIM</description>
        <inlineHelpText>This filed will auto populate when Payment Profile is created for Authorize.net CIM</inlineHelpText>
        <label>Customer Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default payment Gateway proposed by the User</description>
        <inlineHelpText>This field will pick  the Default Payment Gateway at Account level</inlineHelpText>
        <label>Default Payment Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src- Version 4.19/objects/Gateway__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Configuration object. The administrator should create one Account for the appropriate Payment Gateway.</description>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gateway_Type__c</fullName>
        <label>Gateway Type</label>
        <picklist>
            <picklistValues>
                <fullName>Authorize.net</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WireCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FirstData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize.net CIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stripe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SagePay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BrainTree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource_CC_Token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Month__c</fullName>
        <label>Card Expiration Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Year__c</fullName>
        <label>Card Expiration Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/ControllerForPaymentMethod.cls
public with sharing class ControllerForPaymentMethod {
    
    public string currentPageId{get;set;}
    public Payment_Method__c paymentMethod{set;get;}
    public list<Gateway__c> listOfGateway;
    public list<Payment_Method__c> listOfPaymentMethod;
    public Gateway__c gateWayToUse;
    public Account account;    
    public ProfileResult innerClsObj;
    public boolean isDisable{set;get;}
    public boolean isVisible{set;get;}
    public boolean isShow{set;get;}
    public list<String> listOfCardTypes {get;set;}
    public string slistOfCardTypes  {get;set;}
       
    public ControllerForPaymentMethod(ApexPages.StandardController controller) {
        listOfCardTypes = new list<String>(); 
        Schema.DescribeFieldResult fieldResult = Payment_Method__c.Card_Type__c.getDescribe();
        List<Schema.PicklistEntry> CreditCardPickListValue = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListValue : CreditCardPickListValue)
        {
           listOfCardTypes.add(pickListValue.getValue());
        } 
        slistOfCardTypes = JSON.serialize(listOfCardTypes);
        paymentMethod = new Payment_Method__c();
        // We are using the currentPageId Id as AccountId
        currentPageId = apexPages.currentPage().getParameters().get('Id');
        account = [SELECT Gateway__c, Name, Customer_Profile_ID__c FROM Account WHERE Id=:currentPageId];
        //check default payment method is present for particular account.
        listOfPaymentMethod = [SELECT Name FROM Payment_Method__c WHERE Account__c =: currentPageId AND Default__c = true];        
        //check default gateway is present at Gateway and Account Level
        if(account.Customer_Profile_ID__c  != null){
            isVisible = true;
        }
        
        listOfGateway = new list<Gateway__c>();
        if(account.Gateway__c == null) {
            listOfGateway = InvoicingUtilClass.getDefaultGateway();
            if(listOfGateway.isEmpty()) {               
               Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING, system.Label.Gateway_Warning));
            }else if(listOfGateway.get(0).Gateway_Type__c != CommonUtilClass.GATEWAY_TYPE_AUTHORIZEDOTNETCIM){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING, system.Label.Authorize_net_CIMisMandatory));  
            }else if(!listOfGateway.isEmpty()){                        
                gateWayToUse = listOfGateway.get(0);
                isDisable = true;
            }               
        } else {
            gateWayToUse = InvoicingUtilClass.getGateway(account.Gateway__c);
            
            if(gateWayToUse.Gateway_Type__c != CommonUtilClass.GATEWAY_TYPE_AUTHORIZEDOTNETCIM){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.WARNING, system.Label.Authorize_net_CIMisMandatory));  
            } else{
                isDisable = true;
            }
       } 
    }
    
     public PageReference processProfileCreation() {
        
        if(!listOfPaymentMethod.isEmpty() && paymentMethod.Default__c == true){         
            //Added by Shruthi related to INVOICEIT-200
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.DefaultPaymentMethod));
            return null;   
        }
        
         if(paymentMethod.Card_Expiration_Month__c == null || paymentMethod.Card_Expiration_Year__c == null){         
            //Added by Shruthi related to INVOICEIT-200
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.EnterCardexpiryDate));
            return null;   
        }
               
        ClassForHandlingAuthorizeDotNetCIM classForHandlingAuthorizeDotNetCIM = new ClassForHandlingAuthorizeDotNetCIM(gateWayToUse, paymentMethod,account,null);
        if(account.Customer_Profile_ID__c == null){ 
                // call for customer profile and payment profile creation            
            innerClsObj = classForHandlingAuthorizeDotNetCIM.handleCustomerProfileCreation();                                                       
        }else{
                // call for payment profile creation             
            innerClsObj = classForHandlingAuthorizeDotNetCIM.handlePaymentProfileCreation(account.Customer_Profile_ID__c);    
        }
        
        if(innerClsObj.messageCode == 'I00001' && innerClsObj.resultCode == 'Ok'){
            //Added by Shruthi related to INVOICEIT-200
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.CONFIRM, system.Label.PaymentProfileCreated));            
        }else {
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, innerClsObj.messageText));
            return null;
        }
        // display second panel       
        isDisable = false;
        isShow = true;                          
        return null;                                                        
    }
    
    public class ProfileResult {
      public String resultCode;
      public String messageCode;
      public String messageText;
   }

}