src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Advance_Request_Status__c</fullName>
        <description>Automatically the status is populated</description>
        <inlineHelpText>The status will auto populate as Requested or Paid in the Advance Request Status</inlineHelpText>
        <label>Advance Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default payment Gateway proposed by the User</description>
        <inlineHelpText>This field will pick  the Default Payment Gateway at Account level</inlineHelpText>
        <label>Default Payment Gateway</label>
        <referenceTo>Gateway__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Metadata/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for Invoice IT</description>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice IT Configuration</label>
</CustomObject>

src- Version 4.19/objects/Gateway__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Configuration object. The administrator should create one Account for the appropriate Payment Gateway.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gateway_Type__c</fullName>
        <label>Gateway Type</label>
        <picklist>
            <picklistValues>
                <fullName>Authorize.net</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WireCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FirstData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorize.net CIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stripe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SagePay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BrainTree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CyberSource_CC_Token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Merchant_Seal_User_Id__c</fullName>
        <description>Not used by Paypal and Wirecard
&quot;Merchant Seal&quot; in Authorize.net</description>
        <inlineHelpText>Not used by Paypal and Wirecard
&quot;Merchant Seal&quot; in Authorize.net</inlineHelpText>
        <label>Merchant Seal User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Mode__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Test Mode</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_State__c</fullName>
        <label>Invoice State</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Proforma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Request_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Use this field if you want to process partial payments for the Inovice</description>
        <label>Payment Request Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <infoMessage>You can pick a contact that belongs to the selected Account or Partner. This can be overridden.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Job2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Payment Plan. We will give the option to select the Payment Plan.</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Address__c</fullName>
        <label>Billing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_First_Name__c</fullName>
        <label>Billing First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Last_Name__c</fullName>
        <label>Billing Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State_Province__c</fullName>
        <inlineHelpText>Used by ePDQ Gateway (text input vs US state picklist)</inlineHelpText>
        <label>Billing State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal__c</fullName>
        <label>Billing Zip/Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag indicates if the customer has used their Credit Card to pay but don&apos;t want the card details to be on the file. There should be a maximum of 1 such Dummy record per customer.</inlineHelpText>
        <label>Is Dummy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/ControllerSitePaymentProcess.cls
public with sharing class ControllerSitePaymentProcess {  
        Id invoiceId;
        public Invoice__c invoice {get;set;}
        public Account account {get;set;}
        public Payment_Method__c paymentMethod {get;set;}
        public boolean isSaveCardDetails {get;set;}
        public boolean isCybersource {get;set;}
        public boolean isInvoiceExists {get;set;}
        public boolean isPaymentSucessfull {get;set;}
        public boolean isSavePaymentDetails {get;set;}
        public boolean isFooterExist {get;set;}
        public boolean isLogoExist {get;set;}
        Payment_Method__c dummyPaymentMethod;
        public string sSaveCardDetails {get;set;}
        public string sPaymentCss {get;set;}
        public string sBaseURL {get;set;}

        public string sMerchantSealId {get;set;}
        public string sMerchantURL {get;set;}
        public Gateway__c gateWayToUse {get;set;}
        public decimal amountToBeProcessed {get;set;}
        
        public Contact contactRef{get;set;}   
        public boolean isCountryPickListEnable {get;set;}
        public boolean isStateCountryPickListEnable;
        public string sCountryAPIName {get;set;}
        public string sStateAPIName {get;set;}
        map<string,string> mapOfCountry;
        public string paramValue{get;set;} 
        public list<String> listOfCardTypes {get;set;}
        public string slistOfCardTypes  {get;set;}
        Id accountId;
        public boolean isAcountPayment{get;set;}

        public ControllerSitePaymentProcess() {
            amountToBeProcessed = 0;
            try {
                
                listOfCardTypes = new list<String>(); 
                Schema.DescribeFieldResult fieldResult = Payment_Method__c.Card_Type__c.getDescribe();
                List<Schema.PicklistEntry> CreditCardPickListValue = fieldResult.getPicklistValues();
                for( Schema.PicklistEntry pickListValue : CreditCardPickListValue)
                {
                   listOfCardTypes.add(pickListValue.getValue());
                } 
                slistOfCardTypes = JSON.serialize(listOfCardTypes);
                
                contactRef = new Contact();
                mapOfCountry = new map<string,string>();            
                isCountryPickListEnable = false;           
                isFooterExist = false;
                isLogoExist = false;

                list<StaticResource> staticresources = [SELECT Name 
                                                        FROM StaticResource 
                                                        WHERE Name = 'payment_footer' OR Name = 'logo'];

                for(StaticResource staticresource : staticresources) {
                    if(staticresource.Name == 'payment_footer') {
                        isFooterExist = true;
                    } else if(staticresource.Name == 'logo') {
                        isLogoExist = true;
                    }
                }   

                isSavePaymentDetails = Configuration__c.getValues('SAVE_CREDIT_CARD_ON_PAYMENT_PAGE').Boolean_Value__c;
                isStateCountryPickListEnable = Configuration__c.getValues('ENABLE_STATE_AND_COUNTRY_PICKLIST').Boolean_Value__c;
                
                if(isSavePaymentDetails == null) {
                    isSavePaymentDetails = false;
                } 

                sSaveCardDetails = 'none';
                isSaveCardDetails = false;
                sBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
                list<StaticResource> listOfStaticResources = [SELECT Name 
                                                              FROM StaticResource 
                                                              WHERE Name In (:CommonUtilClass.STATICRESOURCE_PAYMENTCSS)
                                                              AND
                                                              (NamespacePrefix = null OR NamespacePrefix = '')];

                for(StaticResource sr : listOfStaticResources) {
                    if(sr.Name == CommonUtilClass.STATICRESOURCE_PAYMENTCSS) {
                        sPaymentCss = CommonUtilClass.STATICRESOURCE_PAYMENTCSS;
                    }
                }
                
                
                
               // Modified By     : Rama Krishna, INVOICEIT-194, Modified Date   : 19 june 2013,
               //Comments :  to allocate the Advance payments without an Invoice for Account.
                                               
                  string recordId = system.currentPageReference().getParameters().get('Id');
                if(recordId.startsWith('001')) {
                    //it is a account payment
                   accountId = recordId; 
                    list<Currency__c> currencys = [SELECT Name FROM Currency__c WHERE Name = 'USD'];
                    if(currencys.isEmpty()) {
                         //Added by Shruthi related to INVOICEIT-200
                         Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.CurrencyIsNotConfigured));
                    } else {
                        account = InvoicingUtilClass.getAccountById(accountId); 
                        isAcountPayment = true;
                        if(account.Gateway__c == null) 
                        {
                            list<Gateway__c> listOfGateway = InvoicingUtilClass.getDefaultGateway();
                            if(listOfGateway.isEmpty()) 
                                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Gateway_does_not_exists_Please_contact_your_service_provider));  
                            else
                                gateWayToUse = listOfGateway.get(0);  
                        } 
                        else
                        {
                            gateWayToUse = InvoicingUtilClass.getGateway(account.Gateway__c);
                            
                        }
                        
                        if(account.Advance_Request_Status__c == CommonUtilClass.STATUS_PAID){
                            isAcountPayment = false;
                            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.RequestedAdvancePayment));
                        }
                     }
                }
                else {        
                    //it is a invoice payment
                    isAcountPayment = false;
                    invoiceId = recordId;
                    if(invoiceId == null) {
                        Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Invoice_details_could_not_be_found));
                    } else {
                        // query the invoice details from db
                        invoice = InvoicingUtilClass.getInvoiceById(invoiceId);

                        if(invoice.Invoice_Status__c != CommonUtilClass.STATUS_POSTED && (invoice.Invoice_State__c != CommonUtilClass.STATUS_PROFORMA || invoice.Invoice_Status__c == CommonUtilClass.STATUS_CANCELLED))
                        {
                            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Payment_Invoice_status_is_draft));
                        } 
                        //Added by DL, INVOICEIT-630, We are not allowing to pay paymentplan invoice through site
                        else if(invoice.Order__r.Payment_Plan__c != null){
                            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.paymentPlanInvoice));
                        }
                        else 
                        {
                            if(invoice.Payment_Request_Amount__c != null && invoice.Payment_Request_Amount__c > 0 && invoice.Payment_Request_Amount__c < invoice.Unpaid_Amount__c) {
                                amountToBeProcessed = invoice.Payment_Request_Amount__c;
                            } else {
                                invoice.Payment_Request_Amount__c = invoice.Unpaid_Amount__c;
                                amountToBeProcessed = invoice.Unpaid_Amount__c;
                            }

                            // query the account details from db
                            account = InvoicingUtilClass.getAccountById(invoice.Account__c);

                            if(amountToBeProcessed <= 0) 
                            {
                                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Payment_Invoice_is_already_paid));
                            } 
                            else 
                            {
                                if(invoice.Account__r.Gateway__c == null) 
                                {
                                    list<Gateway__c> listOfGateway = InvoicingUtilClass.getDefaultGateway();
                                    if(listOfGateway.isEmpty()) 
                                        Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Gateway_does_not_exists_Please_contact_your_service_provider));
                                    else
                                        gateWayToUse = listOfGateway.get(0);
                                        if(gateWayToUse.Gateway_Type__c == 'CyberSource_CC_Token'){
                                        isCybersource = true;}else{
                                        isCybersource = false;}               
                                } 
                                else
                                {
                                    gateWayToUse = InvoicingUtilClass.getGateway(invoice.Account__r.Gateway__c);
                                    if(gateWayToUse.Gateway_Type__c == 'CyberSource_CC_Token'){
                                    isCybersource = true;}else{
                                    isCybersource = false;}
                                }

                                if(gateWayToUse != null && gateWayToUse.Merchant_Seal_User_Id__c != null && gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_AUTHORIZEDOTNET)
                                {
                                    // we should able to genrate the below url
                                    sMerchantSealId = gateWayToUse.Merchant_Seal_User_Id__c;
                                    if(gateWayToUse.Test_Mode__c)
                                    {
                                        sMerchantURL = 'https://testverify.authorize.net/anetseal/?pid=' + sMerchantSealId + '&rurl=' + URL.getCurrentRequestUrl().toExternalForm();
                                    }
                                    else
                                    {
                                        sMerchantURL = 'https://verify.authorize.net/anetseal/?pid=' + sMerchantSealId + '&rurl=' + URL.getCurrentRequestUrl().toExternalForm();
                                    }
                                } 
                            }    
                        }
                    }
                }
            } catch(Exception ex) {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Invoice_details_could_not_be_found));
            }
        }
        
             
        //this method is used for invoice payment for moving 1st page to next page
        public PageReference checkOut() {
            list<Payment_Method__c> listOfPaymentMethods;
            
           //Modified By        : Rama Krishna, INVOICEIT-194, Modified Date   : 19 june 2013,  
           //Comments       : querying the payment method for account.
                          
            if(account.Id != null) {
                listOfPaymentMethods = InvoicingUtilClass.getDummyPaymentMethodForAccount(account.Id);
            } else {
                listOfPaymentMethods = InvoicingUtilClass.getDummyPaymentMethodForAccount(invoice.Account__c);
            }

            if(listOfPaymentMethods.isEmpty()) {
                dummyPaymentMethod = new Payment_Method__c(Is_Dummy__c = true, Active__c = false, Payment_Method__c = 'Credit Card');
                dummyPaymentMethod.Account__c = invoice != null ? invoice.Account__c : account.Id;
                insert dummyPaymentMethod;
            } else {
                dummyPaymentMethod = listOfPaymentMethods.get(0);
            }  

            paymentMethod = new Payment_Method__c(Payment_Method__c = 'Credit Card');

            if(invoice != null){
                paymentMethod.Billing_First_Name__c = invoice.Billing_Contact__r.FirstName;
                paymentMethod.Billing_Last_Name__c = invoice.Billing_Contact__r.LastName;
                paymentMethod.Billing_Address__c = invoice.Billing_Contact__r.MailingStreet;
                paymentMethod.Billing_City__c = invoice.Billing_Contact__r.MailingCity;            
                paymentMethod.Billing_Zip_Postal__c = invoice.Billing_Contact__r.MailingPostalCode;
                
                if(isStateCountryPickListEnable != null && isStateCountryPickListEnable && Schema.SObjectType.Contact.fields.getMap().containsKey('MailingCountryCode')){
                   try{
                    if(invoice.Billing_Contact__c != null){
                        string contactId = invoice.Billing_Contact__c;
                        string contactInfo = 'select MailingCountry,MailingState, MailingCountryCode, MailingStateCode from Contact where id =:contactId';
                        list<Contact> contactObj = Database.query(contactInfo);  
                        if(!contactObj.isEmpty())
                            contactRef = contactObj[0].clone(false);  
                    }  
                    sCountryAPIName = Schema.getGlobalDescribe().get('Contact').getDescribe().fields.getMap().get('MailingCountryCode').getDescribe().getName();
                    sStateAPIName = Schema.getGlobalDescribe().get('Contact').getDescribe().fields.getMap().get('MailingStateCode').getDescribe().getName();
                                    
                    List<Schema.PicklistEntry> countryListValue = Schema.SObjectType.Contact.fields.getMap().get('MailingCountryCode').getDescribe().getPicklistValues();
                    for( Schema.PicklistEntry countryName : countryListValue)
                    {
                       mapOfCountry.put(countryName.getValue(),countryName.getLabel());                                     
                    }
                    isCountryPickListEnable = true;
                    
                   } catch(Exception ex) {
                        ApexPages.addMessages(ex) ; 
                   }                        
                } else{
                    paymentMethod.Billing_State_Province__c = invoice.Billing_Contact__r.MailingState;
                    paymentMethod.Billing_Country__c = invoice.Billing_Contact__r.MailingCountry;   
                }            
                paymentMethod.Account__c = invoice.Account__c;
            } else{
                paymentMethod.Account__c = account.id;
            }

            return Page.payment_CheckOut;
        }
        
        // as per Jira INVOICEIT-194, modified below code
        public PageReference processPayment() {
        
            if(isStateCountryPickListEnable != null && isStateCountryPickListEnable && isCountryPickListEnable){
                if(mapOfCountry.containsKey((String)contactRef.get('MailingCountryCode'))){
                    paymentMethod.Billing_Country__c = mapOfCountry.get((String)contactRef.get('MailingCountryCode'));              
                } else {
                    paymentMethod.Billing_Country__c = '';  
                }

                if((string)contactRef.get('MailingStateCode') != null) {
                    paymentMethod.Billing_State_Province__c = paramValue;
                    //paymentMethod.Billing_State_Province__c = (string)contactRef.get('MailingStateCode');
                } else if((string)contactRef.get('MailingStateCode') == null){              
                    paymentMethod.Billing_State_Province__c = '';
                } else {                
                    paymentMethod.Billing_State_Province__c = invoice.Billing_Contact__r.MailingState;  
                }         
            }
            if(!validateInformation()) {
                return null;
            }

            if(sSaveCardDetails == 'yes') {
                isSaveCardDetails = true;
            }else {
                isSaveCardDetails = false;
            }

            PaymentOperations.PaymentResult paymentResult;
                
                //Modified By     : Rama Krishna, INVOICEIT-194, Comments        : Account id, requested advanced amount passing to the all Gateway constructors.
                      
            if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_AUTHORIZEDOTNET) {
                ClassForHandlingAuthorizeDotNet classForHandlingAuthorizeDotNet = new ClassForHandlingAuthorizeDotNet(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id,account.Advance_Requested_Amount__c, account); 
                paymentResult = classForHandlingAuthorizeDotNet.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_PAYPAL) {
                ClassForHandlingPaypal classForHandlingPaypal = new ClassForHandlingPaypal(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id,account.Advance_Requested_Amount__c, account); 
                paymentResult = classForHandlingPaypal.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_WIRECARD) {
                ClassForHandlingWireCard classForHandlingWireCard = new ClassForHandlingWireCard(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id,account.Advance_Requested_Amount__c, account); 
                paymentResult = classForHandlingWireCard.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_FIRSTDATA) {
                ClassForHandlingFirstdataCard classForHandlingFirstdataCard = new ClassForHandlingFirstdataCard(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingFirstdataCard.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_AUTHORIZEDOTNETCIM) {
                ClassForHandlingAuthorizeDotNetCIM classForHandlingAuthorizeDotNetCIM = new ClassForHandlingAuthorizeDotNetCIM(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id,account.Advance_Requested_Amount__c, account, null); 
                paymentResult = classForHandlingAuthorizeDotNetCIM.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_STRIPE) {
                ClassForHandlingStripeCard classForHandlingStripeCard = new ClassForHandlingStripeCard(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingStripeCard.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            }else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_SAGEPAY) {
                ClassForHandlingSagePay classForHandlingSagePay = new ClassForHandlingSagePay(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingSagePay.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_EWAY) {
                ClassForHandlingEway classForHandlingEway = new ClassForHandlingEway(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingEway.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            }else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_BRAINTREE) {
                ClassForHandlingBrainTree classForHandlingBrainTree = new ClassForHandlingBrainTree(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingBrainTree.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } else if(gateWayToUse.Gateway_Type__c == CommonUtilClass.GATEWAY_TYPE_CyberSource_CC_Token) {
                ClassForHandlingCyberSourceForCreditCard classForHandlingCyberSourceForCreditCard = new ClassForHandlingCyberSourceForCreditCard(gateWayToUse, invoice, paymentMethod, dummyPaymentMethod.Id, account.Advance_Requested_Amount__c, account, null ); 
                paymentResult = classForHandlingCyberSourceForCreditCard.handleAuthorizeAndCharge_Site(isSaveCardDetails); 
            } 

            if(paymentResult.transactionObj.Response_Status__c == CommonUtilClass.TRANSACTION_RESPONSE_STATUS_APPROVED) {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Payment_Success_message));
                isPaymentSucessfull = true;
                paymentMethod.CVV__c = null;
                paymentMethod.Card_Expiration_Month__c = null;
                paymentMethod.Card_Expiration_Year__c = null;
                return page.payment_CheckOut;
                //return null;
            } else {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, paymentResult.message));
            }
           
            return null;
        }

        public boolean validateInformation() {
            if(paymentMethod == null) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, system.Label.Payment_You_have_entered_wrong_page));
                return false;
            }

            String[] listOfMissingFields = new list<string>();
            boolean isMissingFields = false;
            if(paymentMethod.Billing_First_Name__c == null) {
                listOfMissingFields.add('First Name');
                isMissingFields = true;
            }
            if(paymentMethod.Billing_Last_Name__c == null) {
                listOfMissingFields.add('Last Name');
                isMissingFields = true;
            }
            if(paymentMethod.Card_Type__c == null) {
                listOfMissingFields.add('Card Type');
                isMissingFields = true;
            }
            if(paymentMethod.Card_Number__c == null) {
                listOfMissingFields.add('Card Number');
                isMissingFields = true;
            }
            if(isCybersource == false){
            if(paymentMethod.CVV__c == null || paymentMethod.CVV__c.trim().length() <= 0 ) {
                listOfMissingFields.add('CVV');
                isMissingFields = true;
            }}
            if(paymentMethod.Card_Expiration_Month__c == null || paymentMethod.Card_Expiration_Year__c == null) {
                listOfMissingFields.add('Card Expiration Date');
                isMissingFields = true;
            }
            if(isSavePaymentDetails && (sSaveCardDetails == null || sSaveCardDetails == 'none')) {
                listOfMissingFields.add('Save Card Information');
                isMissingFields = true;
            }

            if(isMissingFields) {
                String errMsg = system.Label.Thefollowingfieldsarerequired + listOfMissingFields[0];
                for (Integer i = 1; i < listOfMissingFields.size(); i++) 
                    errMsg = errMsg + ', ' + listOfMissingFields[i]; 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errMsg));     
                return false;             
            }
            return true;
        }
    }