src- Version 4.19/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Payment Method proposed by the User</description>
        <inlineHelpText>This field will populate when ever the Payment Method is created and set as default</inlineHelpText>
        <label>Default Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(
AND(Unpaid_Amount__c &gt; 0, Paid_Amount__c &gt; 0),
&apos;Partially Paid&apos;, IF(Unpaid_Amount__c &gt; 0, &apos;Unpaid&apos;, &apos;Paid&apos;)
)</formula>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Payment Plan. We will give the option to select the Payment Plan.</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>Subtotal - Discount + VAT + Tax</description>
        <inlineHelpText>Subtotal - Discount + VAT + Tax</inlineHelpText>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime/recurring.</description>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewed_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewed From</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges (Renewed From)</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment,allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment,allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.CurrencyL__c</field>
                <operation>equals</operation>
                <valueField>$Source.Currency__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.Invoice_State__c</field>
                <operation>notEqual</operation>
                <value>Proforma</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The Date on which  this Payment was made.</description>
        <inlineHelpText>The Date on which  this Payment was made.</inlineHelpText>
        <label>Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment_Plan__c.object
<CustomObject>
    <description>This object acts as a place holder for defining the Payment Plan and acts as master table for configurations.</description>
    <fields>
        <fullName>Down_Payment_Amount__c</fullName>
        <label>Down Payment (Amount)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Down_Payment__c</fullName>
        <label>Down Payment (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Installment_Start_Date__c</fullName>
        <label>Installment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Plan_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>At order level, you can adjust no of installments according to your need when this field is set as true otherwise you need to stick with this plan without any change</description>
        <inlineHelpText>At order level, you can adjust no of installments according to your need when this field is set as true otherwise you need to stick with this plan without any change</inlineHelpText>
        <label>Is Plan Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_Installments__c</fullName>
        <label>Maximum Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Installments__c</fullName>
        <label>Minimum Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No of Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Installments__c</fullName>
        <label>Type of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Plan_Installment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Payment_Method__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Payment_Method__c.Payment_Method__c</field>
                <operation>equals</operation>
                <valueField>$Source.Payment_Type__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>TEXT( Payment__r.Status__c )</formula>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan Installment</label>
    <nameField>
        <displayFormat>PPI-{0000}</displayFormat>
        <label>Payment Plan Installment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plan Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerHandlingForPaymentPlanAtOrder.cls
public with sharing class ControllerHandlingForPaymentPlanAtOrder {
            
            public Job__c orderObj{get;set;}
            public list<InstallmentWrapper> listOFInstallmentWrapper{get;set;}
            public Payment_Plan__c paymentPlan{get;set;}
            public integer InstllCount;
            public boolean isRender{get;set;}
            public list<Payment_Plan_Installment__c> listOfpaymentPlanInstallment;
            public boolean isAddedPID{get;set;}
            public boolean isPaymentPlan{get;set;}
            
            public ControllerHandlingForPaymentPlanAtOrder(ApexPages.StandardController controller) {
                    orderObj = (Job__c)controller.getRecord();
                    isRender = true;
                    orderObj = [select id,Name,Payment_Plan__c,Account__c,Account__r.Payment_Method__c,Total__c,
                                (SELECT Name  
                                FROM Order_Rate_Plan_Charges__r where Price_Type__c = 'One Time')
                                FROM Job__c where id=: orderObj.id];
                    listOFInstallmentWrapper = new list<InstallmentWrapper>();
                    InstllCount = 0;
                    
                    if(orderObj.Payment_Plan__c != null){
                       isAddedPID = false;
                    } else{
                       isAddedPID = true;
                    }

                    integer iCountOFCharges = [SELECT count() FROM Job_Rate_Plan_Charge__c
                                                WHERE Order__c =: orderObj.id]; 

                    String query3 = orderObj.id;
                    string paymentplaninstallment = 'SELECT id,Payment_Status__c FROM Payment_Plan_Installment__c WHERE Order__c = \'' + query3 + '\'' + ' AND Payment__c = null'; 

                    listOfpaymentPlanInstallment = Database.query(paymentplaninstallment);
                                                    
                    if(listOfpaymentPlanInstallment.size() > 0 ){
                       isPaymentPlan = true;
                    }else{
                       isPaymentPlan = false;
                    }                                   
                                                                          
                    if(iCountOFCharges == orderObj.Order_Rate_Plan_Charges__r.size()){
                          if(orderObj.Payment_Plan__c != null){
                           string query1 = 'SELECT Down_Payment__c,Down_Payment_Amount__c,Name,Installment_Start_Date__c,No_of_Installments__c,Type_of_Installments__c,Is_Plan_Editable__c,Maximum_Installments__c,Minimum_Installments__c '+
                                         'FROM Payment_Plan__c WHERE ID = \'' + orderObj.Payment_Plan__c + '\''; 
                           paymentPlan = Database.query(query1);
                           
                            String query2 = orderObj.id;
                            String strorderid = 'SELECT Account__c,Name,Description__c, Order__c,Payment_Date__c,Payment_Status__c,Payment_Method__c,Invoice__c,Payment__c,Payment_Amount__c,Payment_Type__c '+
                                                                                      'FROM Payment_Plan_Installment__c WHERE Order__c = \'' + query2 + '\''; 
                            list<Payment_Plan_Installment__c> lstInstallment = Database.query(strorderid);                                                            
                            
                            InstallmentWrapper installmentWrapperLocal;
                            for(Payment_Plan_Installment__c insPlan : lstInstallment){
                            installmentWrapperLocal = new InstallmentWrapper();
                            installmentWrapperLocal.paymetnInstallment = insPlan;                        
                            installmentWrapperLocal.iCount = InstllCount;
                            listOFInstallmentWrapper.add(installmentWrapperLocal);       
                            ++InstllCount;
                            isRender = true;
                            
                           }                                                 

                        }else{
                            paymentPlan = new Payment_Plan__c();
                            paymentPlan.Type_of_Installments__c = null;
                        }  
                    }else{
                        isRender = false;
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.PaymentPlan_Supports_OnetimeCharges);
                        Apexpages.addMessage(infoMessage);
                    }                           
            }

           Public void showPlanDetails(){
                string query4 = 'SELECT Down_Payment__c,Down_Payment_Amount__c,Name,Installment_Start_Date__c,No_of_Installments__c,Type_of_Installments__c,Is_Plan_Editable__c,Maximum_Installments__c,Minimum_Installments__c FROM Payment_Plan__c WHERE ID = \'' + orderObj.Payment_Plan__c + '\'';
                paymentPlan = Database.query(query4);
               
            }
            
            
            Public void modifyPlanDetails(){
                if(!listOfpaymentPlanInstallment.isEmpty()){
                    orderObj.Payment_Plan__c = null;
                    update orderObj;
                    delete listOfpaymentPlanInstallment;
                    isAddedPID = true;
                    isPaymentPlan = false;
                    listOFInstallmentWrapper.clear();
                    paymentPlan = new Payment_Plan__c();
                }
            }
            
            public PageReference processpaymentPlan(){
                    listOFInstallmentWrapper = new list<InstallmentWrapper>();
                    if(orderObj.Payment_Plan__c != null){                   
                            integer iCountOfInstallment = integer.valueof(paymentPlan.No_of_Installments__c);
                            Payment_Plan_Installment__c paymetnInstallment;
                            
                            
                            InstallmentWrapper installmentWrapperLocal;

                            paymetnInstallment = new Payment_Plan_Installment__c();
                            if(paymentPlan.Down_Payment_Amount__c != null){
                                 paymetnInstallment.Payment_Amount__c =  paymentPlan.Down_Payment_Amount__c;   
                            }else if(paymentPlan.Down_Payment__c != null){
                                paymetnInstallment.Payment_Amount__c = (paymentPlan.Down_Payment__c * orderObj.Total__c )/ 100 ;
                            } else{
                                paymetnInstallment.Payment_Amount__c = 0;
                            }

                            if(paymetnInstallment.Payment_Amount__c >= orderObj.Total__c){
                                Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Down_Payment_Is_More);
                                Apexpages.addMessage(infoMessage);
                                return null;
                            }
                            
                            paymetnInstallment.Payment_Date__c = paymentPlan.Installment_Start_Date__c;                     

                        if(iCountOfInstallment > 0){
                            decimal iAmount = (orderObj.Total__c - paymetnInstallment.Payment_Amount__c) / iCountOfInstallment;

                            paymetnInstallment.Description__c = 'Down Payment';
                            paymetnInstallment.Order__c = orderObj.id;
                            paymetnInstallment.Account__c = orderObj.Account__c;
                            installmentWrapperLocal = new InstallmentWrapper();
                            installmentWrapperLocal.paymetnInstallment = paymetnInstallment;                        
                            installmentWrapperLocal.iCount = 0;
                            listOFInstallmentWrapper.add(installmentWrapperLocal); 

                            ++InstllCount;
                            
                               for(integer i=1; i<=iCountOfInstallment;i++){
                                    paymetnInstallment = new Payment_Plan_Installment__c();
                                    paymetnInstallment.Order__c = orderObj.id;
                                    if(paymentPlan.Type_of_Installments__c == 'Monthly'){
                                        if(paymentPlan.Installment_Start_Date__c != null){
                                            paymetnInstallment.Payment_Date__c = paymentPlan.Installment_Start_Date__c.addMonths(i);
                                        }
                                     }
                                paymetnInstallment.Payment_Amount__c =  iAmount;
                                paymetnInstallment.Account__c = orderObj.Account__c;
                                paymetnInstallment.Description__c = 'Installment  ' + i +'/'+iCountOfInstallment ;
                                installmentWrapperLocal = new InstallmentWrapper();
                                installmentWrapperLocal.paymetnInstallment = paymetnInstallment;                        
                                installmentWrapperLocal.iCount = i;
                                listOFInstallmentWrapper.add(installmentWrapperLocal);       
                                ++InstllCount;
                            } 
                        } 
                    }else{
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Please_Select_Payment_Plan);
                        Apexpages.addMessage(infoMessage);
                        return null;
                    } 

                    return null;
            }


            public PageReference addInstallment(){
                
                integer iWrapperListCout = listOFInstallmentWrapper.size() -1 ;
                if(paymentPlan.Maximum_Installments__c != null && iWrapperListCout == integer.valueof(paymentPlan.Maximum_Installments__c)){
                    Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.Limit_Exceeded);
                    Apexpages.addMessage(infoMessage);
                    return null;
                }
                InstallmentWrapper installmentWrapperLocal;
                Payment_Plan_Installment__c paymetnInstallment = new Payment_Plan_Installment__c();
                paymetnInstallment.Order__c = orderObj.id;
                installmentWrapperLocal = new InstallmentWrapper();
                installmentWrapperLocal.paymetnInstallment = paymetnInstallment;
                installmentWrapperLocal.iCount = InstllCount + 1;
                listOFInstallmentWrapper.add(installmentWrapperLocal);      
                ++InstllCount;

                return null;
            }

            public PageReference removeInstallment(){
                integer iWrapperListCout = listOFInstallmentWrapper.size() - 1 ;
                if(paymentPlan.Minimum_Installments__c != null && iWrapperListCout == integer.valueof(paymentPlan.Minimum_Installments__c)){
                    Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.You_Cannot_Remove);
                    Apexpages.addMessage(infoMessage);
                    return null;
                }
                string  sParamCount = system.currentPageReference().getParameters().get('unWantedInstallmentCount');
                Payment_Plan_Installment__c paymetnInstallmentToDelete = new Payment_Plan_Installment__c();
                for(integer i = 0; i< listOFInstallmentWrapper.size();i++){
                    InstallmentWrapper installmentWrapperLocal = listOFInstallmentWrapper[i];
                    if(installmentWrapperLocal.iCount == integer.valueof(sParamCount)){
                             if(installmentWrapperLocal.paymetnInstallment.id != null){
                                paymetnInstallmentToDelete.id = installmentWrapperLocal.paymetnInstallment.id;
                             }
                            listOFInstallmentWrapper.remove(i);     
                            break;
                    }
                }
                
                for(integer i = 0; i< listOfpaymentPlanInstallment.size();i++){
                    if(listOfpaymentPlanInstallment[i].id == paymetnInstallmentToDelete.id){
                        listOfpaymentPlanInstallment.remove(i);
                    }
                
                }
                    
                if(paymetnInstallmentToDelete.id != null){
                    delete paymetnInstallmentToDelete;
                }
                
                for(integer i=0;i<listOFInstallmentWrapper.size();i++){
                    if(i > 0){
                        listOFInstallmentWrapper[i].paymetnInstallment.Description__c = 'Installment  ' + i +'/'+(listOFInstallmentWrapper.size()-1);
                    }
                }
                
            return null;
            }

            public PageReference save(){
                try{
                list<Payment_Plan_Installment__c> listOfInsUpdate = new list<Payment_Plan_Installment__c>();
                
                for(InstallmentWrapper installmentWrapperLocal : listOFInstallmentWrapper){

                    listOfInsUpdate.add(installmentWrapperLocal.paymetnInstallment);
                    if(installmentWrapperLocal.paymetnInstallment.Payment_Amount__c <0|| installmentWrapperLocal.paymetnInstallment.Payment_Amount__c == null){
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Amount_should_be_greater_than_zero);
                        Apexpages.addMessage(infoMessage);
                        return null;
                    }
                    if(installmentWrapperLocal.paymetnInstallment.Account__c == null){
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Please_select_Account);
                        Apexpages.addMessage(infoMessage);
                        return null;
                    }
                    if(installmentWrapperLocal.paymetnInstallment.Payment_Date__c < paymentPlan.Installment_Start_Date__c){
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Payment_Date_Cannot_be_less_than_the_Installment_Start_Date);
                        Apexpages.addMessage(infoMessage);
                        return null;
                    }
                    if(installmentWrapperLocal.paymetnInstallment.Payment_Date__c == null ){
                        Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.Please_Select_the_Payment_Date);
                        Apexpages.addMessage(infoMessage);
                        return null;
                    }
                }
                //Added by DL, INVOICEIT-635, Update order only if we genarate Installments.
                if(listOfInsUpdate.size() > 0){
                    update orderObj;
                }
                
                upsert listOfInsUpdate;

                return new PageReference('/'+orderObj.id);
                }catch(DMLException dMlEx) {
                    Apexpages.Message errorMessage; 
                    for (Integer i = 0; i < dMlEx.getNumDml(); i++)
                    { 
                            errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dMlEx.getDmlMessage(i));
                            Apexpages.addMessage(errorMessage);      
                    } 
                    
                }catch(Exception ex) {
                   CustomException.populateApexMessage(CustomException.handleError('ControllerHandlingForPaymentPlanAtOrder', '', null, ex), 'ERROR');
                }
               return null; 
            } 

            public class InstallmentWrapper{
                    public Payment_Plan_Installment__c paymetnInstallment{get;set;}
                    public integer iCount{get;set;}

                    public InstallmentWrapper(){
                            paymetnInstallment =  new Payment_Plan_Installment__c();
                            iCount = 0;
                    }
            } 

    }