src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <description>Indicates the Name of the Currency</description>
        <inlineHelpText>Indicates the Name of the Currency</inlineHelpText>
        <label>Currency Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/CreateCurrecyController.cls
public with sharing class CreateCurrecyController {

        public Currency__c currencyObject {get; set;}
        public boolean isViewMode {get; set;}
        public CreateCurrecyController(ApexPages.StandardController stdController) {
            this.currencyObject = (Currency__c)stdController.getRecord();
            if(currencyObject.Id == null) {
                currencyObject.Currency_Symbol__c = '';
                isViewMode = true;
            }
            else {
                currencyObject = [  SELECT Name,Currency_Symbol__c,Currency_Name__c 
                                    FROM Currency__c 
                                    WHERE Id =: currencyObject.Id]; 
            }
        }

        public void edit() {
            isViewMode = true;
        }
        
        public PageReference save() {
            upsert currencyObject;
            return new PageReference('/' + currencyObject.Id);
        }
    }