src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Payment_Scheduler__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payment Schedulers</relationshipLabel>
        <relationshipName>Payment_Schedulers2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Apex Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_date_and_time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</description>
        <inlineHelpText>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</inlineHelpText>
        <label>Target Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Day_Of_Month__c</fullName>
        <description>If you use Invoice Day as 15 &amp; Target Day as 25.Every month billing will run on 15th and the charges will be calculated up to the 25th of the same month.If you pick 31 and the running month doesn&apos;t have 31 days, it will default to last day of that month.</description>
        <inlineHelpText>If you use Invoice Day as 15 &amp; Target Day as 25.Every month billing will run on 15th and the charges will be calculated up to the 25th of the same month.If you pick 31 and the running month doesn&apos;t have 31 days, it will default to last day of that month.</inlineHelpText>
        <label>Target Day Of Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Day_of_Week__c</fullName>
        <description>Target Day of week</description>
        <inlineHelpText>Target Day of week like 1 for sunday</inlineHelpText>
        <label>Target Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</description>
        <inlineHelpText>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Once</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Scheduler</label>
    <nameField>
        <label>Payment Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/ControllerForSchedulingPayments.cls
public with sharing class ControllerForSchedulingPayments {

        public Payment_Scheduler__c paymentScheduler {get; set;}
        public Boolean isEditMode {get; set;}
        
        public ControllerForSchedulingPayments(ApexPages.StandardController stdController) {
            this.paymentScheduler = (Payment_Scheduler__c) stdController.getRecord();
             
            if(paymentScheduler.Id != null) {
                paymentScheduler = CommonUtilClass.getPaymentScheduler(paymentScheduler.Id);   
                isEditMode = true;
            }
            else {
                paymentScheduler.Type__c = System.Label.OptionOnce; 
            }
        }
        
        public PageReference onChangeOfType() {
            if(paymentScheduler.Type__c == System.Label.OptionDaily) {
                paymentScheduler.Start_date_and_time__c = system.Now();
                paymentScheduler.Target_Date__c = paymentScheduler.Start_date_and_time__c.Date();
                Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO,System.Label.DailyDateMessage);
                Apexpages.addMessage(infoMessage);
            }
            return null;
        }

        public void onChangeStartDate() {
            if(paymentScheduler.Type__c == System.Label.OptionDaily) {
                paymentScheduler.Target_Date__c = paymentScheduler.Start_date_and_time__c.Date();
            }
        }
        
        public PageReference savePaymentScheduler() {
            SavePoint sp;
            boolean isValidations = validations();
            if(!isValidations) {
                try {            
                    sp = DataBase.setSavePoint();
                    if(isEditMode == true) {
                        System.abortJob(paymentScheduler.JobId__c);
                    }

                    String cronExpr = null;
                    String jobId  = null;           
                    Date startDate =  paymentScheduler.Start_date_and_time__c.Date();
                    Integer hours =  paymentScheduler.Start_date_and_time__c.Hour();
                    Integer minutes = paymentScheduler.Start_date_and_time__c.Minute();            
                    String schedulerType  = paymentScheduler.Type__c;
                    Integer seconds = 0;
                    Integer dayOfMonth = startDate.day();
                    Integer month =  startDate.month(); 
                    Integer year =  startDate.year();
                    Date weekStart = startDate.toStartofWeek();
                    Integer dayOfWeek = weekStart.daysBetween(startDate);
                    String space = ' ';
                    String questionMark = '?';
                    String repeat  = '*';
                    String comma = ',';
                    dayOfWeek = dayOfWeek + 2;
                    if(System.Label.OptionOnce == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ space +month +space+ questionMark + space+  year;              
                    }  
                    else if(System.Label.OptionWeekly == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space + questionMark + space + repeat +space+ dayOfWeek + space+  repeat;
                    }
                    else if(System.Label.OptionMonthly == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ space +month + comma + repeat +space+  questionMark + space+  year + comma + repeat;
                    }
                    else if(System.Label.OptionDaily == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ comma +repeat + space + repeat +space+ questionMark  + space+  repeat;
                    }

                    jobId = System.schedule(paymentScheduler.Name, cronExpr, new RunSchedulerPayment());
                    paymentScheduler.JobId__c = jobId;
                    upsert paymentScheduler;
                }
                catch(DMLException dMlEx){
                // Added by Mani ticket : INVOICEIT-310
                    Apexpages.Message errorMessage; 
                    for (Integer i = 0; i < dMlEx.getNumDml(); i++)
                    { 
                        errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dMlEx.getDmlMessage(i));
                        Apexpages.addMessage(errorMessage);      
                    } 
                    return null; 
                }
                catch(system.Exception ex) {
                    Database.rollback(sp);
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,ex.getMessage());
                    Apexpages.addMessage(errorMessage);  
                    return null;
                }
                return new PageReference('/' + paymentScheduler.Id);
            }
            else {
                return null;
            }
        }

        public boolean validations() {
            if(paymentScheduler.Start_date_and_time__c == null) {
                paymentScheduler.Start_date_and_time__c.addError(system.Label.Thisfieldisrequired);  
                return true;    
            } else if(paymentScheduler.Name == null) {
                paymentScheduler.Name.addError(system.Label.Thisfieldisrequired);    
                return true;
            } else if(paymentScheduler.Currency__c == null) {
                paymentScheduler.Currency__c.addError(system.Label.Thisfieldisrequired); 
                return true;
            } else if(paymentScheduler.Type__c == System.Label.OptionWeekly && paymentScheduler.Target_Day_of_week__c == null) {
                paymentScheduler.Target_Day_of_week__c.addError(system.Label.Thisfieldisrequired);
                return true;
            } else if(paymentScheduler.Type__c == System.Label.OptionMonthly && paymentScheduler.Target_Day_Of_Month__c == null) {
                paymentScheduler.Target_Day_Of_Month__c.addError(system.Label.Thisfieldisrequired);
                return true;
            } else if(paymentScheduler.Start_date_and_time__c <= system.Now()) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.Startdatehaspassed);
                Apexpages.addMessage(errorMessage);
                return true;
            }

            return false;
        }
        
    }