src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The payment Currency</description>
        <inlineHelpText>The payment Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unallocated_Amount__c</fullName>
        <description>The amount that is un-allocated and can be used.</description>
        <formula>IF( ISPICKVAL(Status__c, &apos;Cancelled&apos;), 0, Amount__c  -  Allocated_Amount__c -  Refunded_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The amount that is un-allocated and can be used.</inlineHelpText>
        <label>Unallocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Applied__c</fullName>
        <label>Exchange Rate Applied</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <summarizedField>Refund_Line__c.Refund_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Refund_Line__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Refund_Line__c.Refund__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Refund_Date__c</fullName>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refund_Description__c</fullName>
        <label>Refund Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Refund_Line__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refund Lines</relationshipLabel>
        <relationshipName>Refund_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Refund Lines</relationshipLabel>
        <relationshipName>Refund_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund Line</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Refund Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerPaymentRefundForAccount.cls
public with sharing class ControllerPaymentRefundForAccount {
    public Account account{get;set;}
    public Refund__c refund{get;set;}
    public boolean isDisplay{get;set;}
    public list<Payment__c> listOfPayments{get;set;}
    public list<ControllerPaymentRefundForAccount.payments> listOfPaymentsClass{get;set;}
    public map<Integer, ControllerPaymentRefundForAccount.payments> map_Counter_paymentClass {set; get;}
    public  String sPrefix {get; set;}
    
    public ControllerPaymentRefundForAccount(ApexPages.StandardController controller) {
        account = (Account)controller.getRecord(); 
        sPrefix = CommonUtilClass.getPrefix();
        isDisplay = false;
        refund = new Refund__c();
        listOfPayments = new list<Payment__c>();
    }
    public void displayPayments(){
        isDisplay = true;
        listOfPayments = new list<Payment__c>();
        string sQuery = 'SELECT ' + CommonUtilClass.getObjectFields(sPrefix+'Payment__c')
                        + ' FROM Payment__c '
                        + ' WHERE Account__c =' + '\'' + account.id+ '\''
                        + ' AND Unallocated_Amount__c > 0' 
                        + ' AND Status__c = \'Completed\''
                        +' AND Currency__c =' + '\'' + refund.Currency__c+ '\'';
                        
        sQuery = String.escapeSingleQuotes(sQuery);
        sQuery = sQuery.replace('\\', '');
        listOfPayments = Database.query(sQuery);
        listOfPaymentsClass = new list<ControllerPaymentRefundForAccount.payments>();
        map_Counter_paymentClass = new map<Integer, ControllerPaymentRefundForAccount.payments>();
        ControllerPaymentRefundForAccount.payments paymentsClass;
        integer counter = 0;
        if(!listOfPayments.isEmpty()){
            for(Payment__c payment: listOfPayments){
                paymentsClass = new ControllerPaymentRefundForAccount.payments();
                paymentsClass.counter = ++counter;
                paymentsClass.payment = payment;
                paymentsClass.refundAmount = 0;
                paymentsClass.isChecked = false;
                listOfPaymentsClass.add(paymentsClass);
                map_Counter_paymentClass.put(counter,paymentsClass);
            }
        }
        else{
            Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, System.Label.Payment_Records);
            Apexpages.addMessage(infoMessage);
        }

    }
    public pagereference createRefunds() {
        boolean isExecute = false;
        boolean isExecuteNew = false;
        for(ControllerPaymentRefundForAccount.payments paymentClass: listOfPaymentsClass){
            if(paymentClass.isChecked){
                isExecuteNew = true;
            }
            if(paymentClass.isChecked && paymentClass.refundAmount <=  0){
                isExecute = true;
            }
        }
        if(isExecute){
            Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, System.Label.Refund_Amount);
            Apexpages.addMessage(infoMessage);
            return null;
        }
        if(!isExecuteNew){
            Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, System.Label.Payment_To_Refund);
            Apexpages.addMessage(infoMessage);
            return null;
        }
        refund.Account__c = account.id;
        if(refund.Refund_Date__c != null){
            refund.Refund_Date__c = refund.Refund_Date__c;
        }
        if(refund.Refund_Description__c != null){
            refund.Refund_Description__c = refund.Refund_Description__c;
        }
        decimal conversionRate = 1;
        if(UserInfo.isMultiCurrencyOrganization()){
            string sQuery =   'SELECT ISOCode, ConversionRate, StartDate, NextStartDate FROM DatedConversionRate '
                        + 'WHERE ISOCode = \'' + refund.Currency__r.Name + '\''
                        + ' AND StartDate <= ' + refund.Refund_Date__c + ' LIMIT 1';
            sQuery = String.escapeSingleQuotes(sQuery); 
            list<sobject> sobjectDatedConversionRates = Database.query(sQuery);
            list<sobject> listofCurrencyType = Database.query('SELECT IsoCode FROM CurrencyType WHERE IsCorporate = true');
            if(sobjectDatedConversionRates.size() > 0) {
                if(listofCurrencyType[0].get('IsoCode') == refund.Currency__r.Name) {
                    conversionRate = (decimal) sobjectDatedConversionRates[0].get('ConversionRate');
                    refund.Exchange_Rate_Applied__c = conversionRate;
                }
            }
        }else{
            refund.Exchange_Rate_Applied__c = conversionRate;
        }
        insert refund;
        list<Refund_Line__c> listOfRefundLinesToInsert = new list<Refund_Line__c>();
        for(ControllerPaymentRefundForAccount.payments paymentClass: listOfPaymentsClass){
            Refund_Line__c refundLine = new Refund_Line__c();
            if(paymentClass.isChecked){
                refundLine.Payment__c = paymentClass.payment.id;
                refundLine.Refund__c = refund.id;
                refundLine.Refund_Amount__c = paymentClass.refundAmount;
                listOfRefundLinesToInsert.add(refundLine);
            }
        }
        if(!listOfRefundLinesToInsert.isEmpty()){
            insert listOfRefundLinesToInsert;
        }
        return new PageReference('/' + account.Id);
    }
    public class payments{
        public boolean isChecked {get;set;}
        public decimal refundAmount {get;set;}
        public integer counter {get;set;}      
        public Payment__c payment {get;set;}
    }
}