src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_State__c</fullName>
        <label>Invoice State</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Proforma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(
AND(Unpaid_Amount__c &gt; 0, Paid_Amount__c &gt; 0),
&apos;Partially Paid&apos;, IF(Unpaid_Amount__c &gt; 0, &apos;Unpaid&apos;, &apos;Paid&apos;)
)</formula>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Payment Plan. We will give the option to select the Payment Plan.</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The payment Currency</description>
        <inlineHelpText>The payment Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment,allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment,allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.CurrencyL__c</field>
                <operation>equals</operation>
                <valueField>$Source.Currency__c</valueField>
            </filterItems>
            <filterItems>
                <field>Invoice__c.Invoice_State__c</field>
                <operation>notEqual</operation>
                <value>Proforma</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unallocated_Amount__c</fullName>
        <description>The amount that is un-allocated and can be used.</description>
        <formula>IF( ISPICKVAL(Status__c, &apos;Cancelled&apos;), 0, Amount__c  -  Allocated_Amount__c -  Refunded_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The amount that is un-allocated and can be used.</inlineHelpText>
        <label>Unallocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Payment_Allocation__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Holds the Payment Allocation details which essentially splits the Payment among invoices.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <description>The Invoice against which this Payment is made.</description>
        <inlineHelpText>The Invoice against which this Payment is made.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Payment_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#78C953</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Payment_Plan__c.object
<CustomObject>
    <description>This object acts as a place holder for defining the Payment Plan and acts as master table for configurations.</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Payment_Plan_Installment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>TEXT( Payment__r.Status__c )</formula>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payment Plan Installments</relationshipLabel>
        <relationshipName>Payment_Plan_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan Installment</label>
    <nameField>
        <displayFormat>PPI-{0000}</displayFormat>
        <label>Payment Plan Installment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plan Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/ControllerAllocatePayments.cls
public with sharing class ControllerAllocatePayments {

        public Payment__c payment {set; get;}
        public String sPrefix {get; set;}
        public list<ControllerAllocatePayments.PaymentAllocation> listOfallocationClass {set; get;}
        public map<Integer, ControllerAllocatePayments.PaymentAllocation> map_Counter_allocationClass {set; get;}
        list<Payment_Allocation__c> listOfPaymentAllocationsToInsert;
        public list<Payment_Allocation__c> listOfPaymentAllocationsInDb {set; get;}
        public boolean isPaymentAllocationsExists {set; get;}
        public boolean isUnpaidInvoicesExists {set; get;}
        //Done by Manigandan.SA on Dec 9, 2015 for INVOICEIT-638
        public boolean isPPInstallmentExists {set; get;}
        list<Payment_Allocation__c> listOfPPIPaymentAllocationsToInsert;
        list<Payment_Plan_Installment__c> listOfPPIChecked;
        public list<Payment_Plan_Installment__c> listOfPaymentPlanInstallment{get; set;}
        public Payment_Plan_Installment__c paymentplaninstallment {set; get;}
        public map<Integer, ControllerAllocatePayments.PaymentPlanInstallment> map_Counter_ppiallocationClass {set; get;}
        public list<ControllerAllocatePayments.PaymentPlanInstallment> listOfppiallocationClass {set; get;}
        
        public ControllerAllocatePayments(ApexPages.StandardController stdController) {
            this.payment = (Payment__c)stdController.getRecord();
            sPrefix = CommonUtilClass.getPrefix();
            initalize();
            if(payment.Payment_Allocations__r.size() > 0) {
                isPaymentAllocationsExists = true;
                listOfPaymentAllocationsInDb = new list<Payment_Allocation__c>();
                listOfPaymentAllocationsInDb.addAll(payment.Payment_Allocations__r);
            }
        }

        public void initalize() {
            try {
                string sQuery = 'SELECT '+ CommonUtilClass.getObjectFields(sPrefix+'Payment__c')
                                + ',(SELECT '+ CommonUtilClass.getObjectFields(sPrefix+'Payment_Allocation__c') 
                                + ' FROM Payment_Allocations__r) '
                                + 'FROM Payment__c '
                                + ' WHERE Id =' + '\'' + String.escapeSingleQuotes(payment.id) + '\'';
                payment = Database.query(sQuery);

                if(payment.Unallocated_Amount__c != 0 && ( payment.Status__c == 'completed' || payment.Status__c == 'Completed') ) { 
                    list<Invoice__c> listOfInvoices = ControllerAllocatePayments.getInvoicesForPayment(payment);
                   
                   
                    if(listOfInvoices.size() > 0) {
                        isUnpaidInvoicesExists = true;
                    }                                                                  
                    listOfallocationClass = new list<ControllerAllocatePayments.PaymentAllocation>();  
                    
                    map_Counter_allocationClass = new map<Integer, ControllerAllocatePayments.PaymentAllocation>(); 
                                                                          
                    ControllerAllocatePayments.PaymentAllocation allocationClass;
                    integer counter = 0;
                    Payment_Allocation__c paymentAllocation;
                    for(Invoice__c invoice : listOfInvoices) {
                        allocationClass = new ControllerAllocatePayments.paymentAllocation();
                        allocationClass.counter = ++counter;
                        allocationClass.isChecked = false;
                        allocationClass.invoice = invoice;
                        paymentAllocation = new Payment_Allocation__c(Invoice__c = invoice.Id, Payment__c = payment.Id);
                        allocationClass.paymentAllocation = paymentAllocation;
                        listOfallocationClass.add(allocationClass);
                        map_Counter_allocationClass.put(counter, allocationClass);
                    }
                    //Done by Manigandan.SA on Dec 9, 2015 for INVOICEIT-638
                    // Comments: To display all the payment plan installments during initiallization
                    
                    list<Payment_Plan_Installment__c> listOfPaymentPlanInstallment = ControllerAllocatePayments.getPaymentPlanInstallmentsForPayment(payment);
                    map_Counter_ppiallocationClass = new map<Integer, ControllerAllocatePayments.PaymentPlanInstallment>(); 
                    if(listOfPaymentPlanInstallment.size() > 0){
                        isPPInstallmentExists = true;
                    }
                    listOfppiallocationClass = new list<ControllerAllocatePayments.PaymentPlanInstallment>();
                    ControllerAllocatePayments.PaymentPlanInstallment ppInstallmentClass;
                    integer counter1 = 0;
                    Payment_Allocation__c ppIpaymentAllocation;
                     for(Payment_Plan_Installment__c pPInstallments : listOfPaymentPlanInstallment) {
                         ppInstallmentClass = new ControllerAllocatePayments.PaymentPlanInstallment();
                         ppInstallmentClass.counter1 = ++counter1;
                         ppInstallmentClass.isChecked1 = false;
                         ppInstallmentClass.paymentPlanInstallment = pPInstallments;
                         
                         paymentAllocation = new Payment_Allocation__c(Invoice__c = pPInstallments.Invoice__c, Payment__c = payment.Id, Amount__c = pPInstallments.Payment_Amount__c);
                         ppInstallmentClass.ppIpaymentAllocation = paymentAllocation;
                         
                         if(pPInstallments.Payment_Amount__c > payment.Unallocated_Amount__c){
                         ppInstallmentClass.isVisible1 = true;
                         }
                         if(pPInstallments.Payment_Status__c == 'Completed'){
                         ppInstallmentClass.isVisible1 = true;
                         }
                         
                         listOfppiallocationClass.add(ppInstallmentClass);
                         map_Counter_ppiallocationClass.put(counter1, ppInstallmentClass);
                         
                        
                     }
                   
                }//Added by dhanalakshmi, INVOICEIT-442, when payment status != 'Completed' do not add PaymentAllocations to Payment
                else{
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.INFO,system.Label.Payment_Status);
                    Apexpages.addMessage(errorMessage);
                }
  
            } catch(Exception ex) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
                Apexpages.addMessage(errorMessage);
            }  
        }

        public void getSelectedInvoice() {
            integer selectedInoiceCounter = integer.ValueOf(system.currentPageReference().getParameters().get('selectedCounter'));
            ControllerAllocatePayments.paymentAllocation allocationClass = map_Counter_allocationClass.get(selectedInoiceCounter);
            if(allocationClass.isChecked) {
                allocationClass.paymentAllocation.Amount__c = 0;
            } else {
                allocationClass.paymentAllocation.Amount__c = null;
            }
        }
        
        public void getSelectedPaymentPlanInstallment() {
            integer selectedPPICounter = integer.ValueOf(system.currentPageReference().getParameters().get('selectedCounter'));
            ControllerAllocatePayments.paymentPlanInstallment ppiallocationClass = map_Counter_ppiallocationClass.get(selectedPPICounter);
            if(ppiallocationClass.isChecked1) {
                ppiallocationClass.ppIpaymentAllocation.Amount__c = 0;
            } else {
                ppiallocationClass.ppIpaymentAllocation.Amount__c = null;
            }
        }

        public PageReference savePaymentAllocations() {
            
            if(validateAmount()) {
                try {

                    insert listOfPaymentAllocationsToInsert;

                    if(!listOfPPIPaymentAllocationsToInsert.isempty())
                    insert listOfPPIPaymentAllocationsToInsert;
                    update listOfPPIchecked;

                    //Done by Manigandan.SA on Dec 9, 2015 for INVOICEIT-638
                    return new PageReference('/' + payment.Id);
                } catch(DMLException dMlEx){
                    // Added by Mani ticket : INVOICEIT-310
                    Apexpages.Message errorMessage; 
                    for (Integer i = 0; i < dMlEx.getNumDml(); i++)
                    { 
                        errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dMlEx.getDmlMessage(i));
                        Apexpages.addMessage(errorMessage);      
                    } 
                    return null; 
                }catch(Exception ex) {
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
                    Apexpages.addMessage(errorMessage);
                }  
            }  
            return null;    
        }

        public PageReference backToPayment() {
            return new PageReference('/' + payment.Id);
        }
        public PageReference cancelPayment() {
            return new PageReference('/' + payment.Id);
        }

        public boolean validateAmount() {
            decimal calculatedSum = 0.0;
            listOfPaymentAllocationsToInsert = new list<Payment_Allocation__c>();
            listOfPPIPaymentAllocationsToInsert = new list<Payment_Allocation__c>();
            listOfPPIchecked = new list<Payment_Plan_Installment__c>();
            //1. We have to check whether it is checked
            //2. if it is checked and payment allocation amount is less than zero,show an error message
            //3. if it is checked and payment allocation amount is greathet than invoice un-paid amount,show an error message
            for(ControllerAllocatePayments.paymentAllocation allocationClass : listOfallocationClass) {
                if(allocationClass.isChecked) {
                    if(allocationClass.paymentAllocation.Amount__c <= 0) {
                        Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.PaymentPageNoZeroValues);
                        Apexpages.addMessage(errorMessage);
                        return false;
                    } else if(allocationClass.paymentAllocation.Amount__c > allocationClass.invoice.Unpaid_Amount__c) {
                        Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.PaymentPageAllocationIsGreater);
                        Apexpages.addMessage(errorMessage);
                        return false;
                    } else {
                        calculatedSum += allocationClass.paymentAllocation.Amount__c;
                        listOfPaymentAllocationsToInsert.add(allocationClass.paymentAllocation);
                    }
                }
            }

            // To validate the equality of Installment amount with the Payment Amount
            for(ControllerAllocatePayments.PaymentPlanInstallment ppInstallmentClass : listOfppiallocationClass) {
                if(ppInstallmentClass.isChecked1) {
                     //isExecute = true;
                     listOfPPIchecked.add(new Payment_Plan_Installment__c(Id = ppInstallmentClass.paymentPlanInstallment.id, Payment__c = payment.Id));
                    if(ppInstallmentClass.paymentPlanInstallment.Payment_Amount__c == ppInstallmentClass.ppIpaymentAllocation.Amount__c) {
                         calculatedSum += ppInstallmentClass.ppIpaymentAllocation.Amount__c;
                        listOfPPIPaymentAllocationsToInsert.add(ppInstallmentClass.ppIpaymentAllocation);
                    } else  {
                        Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.PaymentPageAllocationIsGreater);
                        Apexpages.addMessage(errorMessage);
                        return false;
                    } 
                }
            }
            if(calculatedSum <= payment.Unallocated_Amount__c) {
                return true;
            } else {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.PaymentPageTotalPaymentIsGreater);
                Apexpages.addMessage(errorMessage);
                return false;
            }
        }
        
        public PageReference cancelPaymentAllocation() {
            string selectedPaymentAllocationId = system.currentPageReference().getParameters().get('paymentAllocationId');
            for(Payment_Allocation__c pA : listOfPaymentAllocationsInDb) {
                if(pA.Id == selectedPaymentAllocationId) {
                    //make payment allocation amount to zero and status to CANCELLED
                    pA.Amount__c = 0.0;
                    pA.Status__c = CommonUtilClass.STATUS_CANCELLED;
                    //once the payAllocation is CANCELLED make invoice status from paid to active

                    Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO, system.Label.PaymentPageCancelledSuccessfully);
                    Apexpages.addMessage(infoMessage);
                    break;
                }
            }

            try {
                update listOfPaymentAllocationsInDb;
            }  catch(DMLException dMlEx){
                // Added by Mani ticket : INVOICEIT-310
                Apexpages.Message errorMessage; 
                for (Integer i = 0; i < dMlEx.getNumDml(); i++)
                { 
                    errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dMlEx.getDmlMessage(i));
                    Apexpages.addMessage(errorMessage);      
                } 
                return null; 
            }catch(Exception ex) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
                Apexpages.addMessage(errorMessage);
            }
            initalize();
            return null;
        }

        public class PaymentAllocation {
            public integer counter {get;set;}        
            public boolean isChecked {get;set;}
            public Invoice__c invoice {get;set;}
            public Payment_Allocation__c paymentAllocation {get;set;}
        }
        //Done by Manigandan.SA on Dec 9, 2015 for INVOICEIT-638
        //Comment: This inner class meant for payment plan installment
        public class PaymentPlanInstallment {
            public integer counter1 {get;set;}        
            public boolean isChecked1 {get;set;}
            public Invoice__c invoice1 {get;set;}
            public Payment_Plan_Installment__c paymentPlanInstallment {get;set;}
            public Payment_Allocation__c ppIpaymentAllocation {get;set;}
            public boolean isVisible1 {get;set;}
            
            public PaymentPlanInstallment(){
                isVisible1 = false;
            }

        }
        
        // Added 'Order__r.Payment_Plan__c = null' , INVOICEIT-630, Restricting automatic payment allocation if Invoice's order has payment plan.
        public static list<Invoice__c> getInvoicesForPayment(Payment__c payment) {
            string sPrefix = CommonUtilClass.getPrefix();
            string sQuery = 'SELECT ' + CommonUtilClass.getObjectFields(sPrefix+'Invoice__c')
                                      + 'FROM Invoice__c'
                                      + ' WHERE CurrencyL__c =' + '\'' +  String.escapeSingleQuotes(payment.Currency__c) + '\'' 
                                      + 'AND Account__c =' + '\'' +  String.escapeSingleQuotes(payment.Account__c) + '\''
                                      + 'AND Unpaid_Amount__c > 0'
                                      + ' AND Order__r.Payment_Plan__c = null'
                                      + ' AND '
                                      + '(Invoice_Status__c ='  + '\'' + CommonUtilClass.STATUS_POSTED+ '\'' 
                                      + ' OR'
                                      + '(Invoice_State__c =' + '\'' + CommonUtilClass.STATUS_PROFORMA + '\'' 
                                      + ' AND Invoice_Status__c !=' + '\'' + CommonUtilClass.STATUS_CANCELLED + '\')'
                                      + ')';
            list<Invoice__c> listOfInvoices = Database.query(sQuery);
            return listOfInvoices;                                            
        }
         //Done by Manigandan.SA on Dec 9, 2015 for INVOICEIT-638
         //Comment:  Lists all the payment plan installment for the posted invoices
         public static list<Payment_Plan_Installment__c> getPaymentPlanInstallmentsForPayment(Payment__c payment) {
             string sPrefix = CommonUtilClass.getPrefix();
             string sQuery = 'SELECT ' + CommonUtilClass.getObjectFields(sPrefix+'Payment_Plan_Installment__c')
                                       +'FROM Payment_Plan_Installment__c'
                                       + ' WHERE Invoice__r.Invoice_Status__c =' + '\'Posted\'' 
                                       + ' AND Account__c=' + '\'' + String.escapeSingleQuotes(payment.Account__c) + '\'' ;
             list<Payment_Plan_Installment__c> listOfPaymentPlanInstallment = Database.query(sQuery);
             return listOfPaymentPlanInstallment;
         }
    }