src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <defaultValue>$Label.ButtonNew</defaultValue>
        <description>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the Symbol of one particular Currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Currency Symbol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Symbol__c</fullName>
        <description>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Obsolete_Symbol</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>It will have description of IT Product</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>It will have the product code value</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <description>This will  have the Family Names Of Product</description>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <description>This will have Valid From Date of Product</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <description>This will have the Valid To Date of the Product</description>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>Cost_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Unit Cost Price</description>
        <inlineHelpText>Unit Cost Price</inlineHelpText>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages for different categories.</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <picklist>
            <picklistValues>
                <fullName>Taxable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non Taxable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>ProductRatePlanCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestControllerForExportImportTemplate.cls
/**
 * This class contains unit tests for validating the behavior of controllerForExportImportTemplate classes
 * created By Asish
 */
@isTest
private class TestControllerForExportImportTemplate {

    static testMethod void controllerForExportImportTemplate() {
        
        //poplulate the data
        Date validtodate = Date.today();   
        list<Product__c> listProducts = new list<Product__c>();
        Product__c product;
        for(Integer x = 0;x < 2;x++){
          product = new  Product__c(Name = 'Test Product' + x,Valid_From_Date__c = validtodate,Valid_To_Date__c = validtodate,Product_Family__c = 'Default',Product_Code__c = 'AC001',Description__c = 'Product');
          listProducts.add(product);
        }    
        insert listProducts;
        
        list<Product_Rate_Plan__c> listProductRatePlans = new list<Product_Rate_Plan__c>();
        Product_Rate_Plan__c productRatePlan;
        for(Integer x = 0;x< 2;x++){
          productRatePlan = new  Product_Rate_Plan__c(Name = 'Test ProductRatePlan' + x,
                                                      Product__c = listProducts.get(0).Id,Valid_From_Date__c = validtodate,Valid_To_Date__c = validtodate);
          listProductRatePlans.add(productRatePlan);
        }
        insert listProductRatePlans;
            
        list<Currency__c> listCurrencys = new list<Currency__c>();
        listCurrencys.add(new Currency__c(Name = 'GBP', Currency_Symbol__c = 'sss',Symbol__c = 's'));
        insert listCurrencys;
        
        list< Product_Rate_Plan_Charge__c> listProductRatePlanCharges = new list< Product_Rate_Plan_Charge__c>();
        Product_Rate_Plan_Charge__c productRatePlanCharge;
        for(Integer x = 0;x < 5;x++){
          productRatePlanCharge = new  Product_Rate_Plan_Charge__c(Name = 'Test ProductRatePlan Charge' + x,CurrencyL__c = listCurrencys.get(0).Id,
                                                                   Product_Rate_Plan__c = listProductRatePlans.get(0).Id,
                                                                   Unit_price__c = 200,Cost_Price__c = 160,Product_Charge_Category__c = 'Taxable');
          listProductRatePlanCharges.add(productRatePlanCharge);
        }
        insert listProductRatePlanCharges;
        
        //import the data
        ControllerForExportImportTemplate controllerForExportImportTemplate = new ControllerForExportImportTemplate();
        controllerForExportImportTemplate.exportProductsToCsvForSample();
        string csvBuild = controllerForExportImportTemplate.recStr;
        system.assert(csvBuild.contains('Test Product'));
        //export the dat
        string str = '"';
        controllerForExportImportTemplate.uploadCSV();
        controllerForExportImportTemplate.parseCSV(str);
        
        str += 'Product Family,Valid From Date,Product Code,Valid To Date,Description,Product Name,Valid To Date,Description,Product Rate Plan Name,Valid From Date,Accounting Code,Unit Cost Price,Charge Sequence Number,Price Type,Currency,UOM,Unit Selling Price,Charge Name,Product Charge Category,Price Format,Is Price Editable In Quote/Order Wizards';
        str += '\n';
        str += '13-12-2011,13-12-2021,13-12-2021 00:00,13-12-2011 00:00,13-12-2011,13-12-2021,13-12-2021 00:00,13-12-2011 00:00';
        str +='"';
        blob b = blob.valueOf(str);
        controllerForExportImportTemplate.contentFile = b;
        controllerForExportImportTemplate.uploadCSV();
        controllerForExportImportTemplate.parseCSV(str);
        controllerForExportImportTemplate.exportCsv();
        controllerForExportImportTemplate.downloadTemplateCsv();
        
    }
    
}