src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <fields>
        <fullName>Symbol__c</fullName>
        <description>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</description>
        <inlineHelpText>It stores the symbol of one particular currency.Say for example &apos;$&apos; for USD</inlineHelpText>
        <label>Obsolete_Symbol</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>It will have description of IT Product</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>It will have the product code value</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <description>This will  have the Family Names Of Product</description>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <description>This will have Valid From Date of Product</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <description>This will have the Valid To Date of the Product</description>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product_Bundle__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Holds different types of Products as a Bundle</description>
    <fields>
        <fullName>Bundle_Type__c</fullName>
        <description>This will specify whether Bundle Type is of at &apos;bundle level&apos; or at &apos;line level&apos;.</description>
        <inlineHelpText>This will specify whether Bundle Type is of at &apos;bundle level&apos; or at &apos;line level&apos;.</inlineHelpText>
        <label>Bundle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Bundles</relationshipLabel>
        <relationshipName>Product_Bundles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>It contains the description of Product Bundle</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether Price is onetime, weekly, monthly etc based.</description>
        <inlineHelpText>This will specify whether Price is onetime, weekly, monthly etc based.</inlineHelpText>
        <label>Price Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages at Product Bundle level</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages at Product Bundle level</inlineHelpText>
        <label>Tax Category</label>
        <picklist>
            <picklistValues>
                <fullName>Taxable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Taxable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 2 of the product catalog.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>Cost_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Unit Cost Price</description>
        <inlineHelpText>Unit Cost Price</inlineHelpText>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <description>This will specify whether price is default or tiered</description>
        <inlineHelpText>Please refer to the user documentation for detailed information on what the different pricing models mean.
Search for &quot;Pricing Model&quot; in the documentation.</inlineHelpText>
        <label>Pricing Model</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Fee Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Per Unit Pricing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume Pricing</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime, weekly, monthly etc or usage(metered) based.</description>
        <label>Price Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages for different categories.</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <picklist>
            <picklistValues>
                <fullName>Taxable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non Taxable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge</relationshipLabel>
        <relationshipName>ProductRatePlanCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Product_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This holds the tiered pricing details for the Charge.</description>
    <fields>
        <fullName>End_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charge_Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <inlineHelpText>The Start and End Units are both inclusive for calculation.</inlineHelpText>
        <label>Start Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost_Price__c</fullName>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Based on the Currency the Products will be generated</description>
        <inlineHelpText>This Currency field is used in price displays for products to generate a Order from Quote</inlineHelpText>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestClassForProductBundle.cls
@isTest
    private class TestClassForProductBundle {

        static testMethod void methodControllerProductBundle() {
            ControllerInsertCustomSettings ControllerInsertCustomSettings = new ControllerInsertCustomSettings();
            ControllerInsertCustomSettings.insertValues();
        
            Date validtodate = Date.today()-100;   
            list<Product__c> listProducts = new list<Product__c>();
            Product__c product;
            for(Integer x = 0;x < 1;x++){
              product = new  Product__c(Name = 'Test Product' + x,Valid_From_Date__c = validtodate,Valid_To_Date__c = validtodate,Product_Family__c = 'Default',Product_Code__c = 'Code1',Description__c = 'Product');
              listProducts.add(product);
            }  
            
            Product__c productTiers = new  Product__c(Name = 'Test Product for tiers',Valid_From_Date__c = validtodate,Valid_To_Date__c = validtodate,Product_Family__c = 'Default',Product_Code__c = 'Code1',Description__c = 'Product');  
            listProducts.add(productTiers);
            insert listProducts;

            System.assertEquals('GBP', 'GBP');
            
            list<Product_Rate_Plan__c> listProductRatePlans = new list<Product_Rate_Plan__c>();
            Product_Rate_Plan__c productRatePlan;
            for(Integer x = 0;x< 1;x++){
              productRatePlan = new  Product_Rate_Plan__c(  Name = 'Test ProductRatePlan' + x,
                                                            Product__c = listProducts.get(x).Id,
                                                            Valid_From_Date__c = validtodate);
              listProductRatePlans.add(productRatePlan);
            }
            
            Product_Rate_Plan__c productRatePlanTiers = new Product_Rate_Plan__c(Name = 'Test ProductRatePlan tiers',
                                                            Product__c = listProducts.get(1).Id,
                                                            Valid_From_Date__c = validtodate);
                                                            
            Product_Rate_Plan__c productRatePlanTier = new Product_Rate_Plan__c(Name = 'Test ProductRatePlan tiers',
                                                            Product__c = listProducts.get(1).Id,
                                                            Valid_From_Date__c = validtodate);                                                
            
            listProductRatePlans.add(productRatePlanTier);
            listProductRatePlans.add(productRatePlanTiers);
            insert listProductRatePlans;
            
            list<Currency__c> listCurrencys = new list<Currency__c>();
            listCurrencys.add(new Currency__c(Name = 'GBP', Symbol__c = '£1'));
            listCurrencys.add(new Currency__c(Name = 'USD', Symbol__c = '$2'));
            listCurrencys.add(new Currency__c(Name = 'EUR', Symbol__c = '€3'));    
            insert listCurrencys;
            
            list<Product_Rate_Plan_Charge__c> listProductRatePlanCharges = new list< Product_Rate_Plan_Charge__c>();
            Product_Rate_Plan_Charge__c productRatePlanCharge;
            Product_Rate_Plan_Charge__c productRatePlanCharge2;
            for(Integer x = 0;x <= 5;x++){
              productRatePlanCharge = new  Product_Rate_Plan_Charge__c(Name = 'Test ProductRatePlan Charge' + x,CurrencyL__c = listCurrencys.get(0).Id,Price_Type__c = system.Label.OptionOneTime,
                                                                       Product_Rate_Plan__c = listProductRatePlans.get(0).Id,
                                                                       Unit_price__c = 200,Cost_Price__c = 160, Product_Charge_Category__c = 'Taxable');
              
              productRatePlanCharge2 = new  Product_Rate_Plan_Charge__c(Name = 'Test ProductRatePlan Charge' + x,CurrencyL__c = listCurrencys.get(0).Id,
                                                                       Product_Rate_Plan__c = listProductRatePlans.get(0).Id,
                                                                       Unit_price__c = 200,Cost_Price__c = 160, Product_Charge_Category__c = 'Taxable');                                                         
              
              listProductRatePlanCharges.add(productRatePlanCharge);
              listProductRatePlanCharges.add(productRatePlanCharge2);
                  
            }
            
            Product_Rate_Plan_Charge__c tierCharge = new Product_Rate_Plan_Charge__c(Name = 'Test ProductRatePlan Charge Tiers',CurrencyL__c = listCurrencys.get(0).Id,Price_Type__c = system.Label.OptionOneTime,
                                                                       Product_Rate_Plan__c = productRatePlanTiers.Id,
                                                                       Unit_price__c = 0,Cost_Price__c = 0, Product_Charge_Category__c = 'Taxable', Price_Format__c = CommonUtilClass.PRICE_FORMAT_VOLUME);
            listProductRatePlanCharges.add(tierCharge);
            insert listProductRatePlanCharges;
            
            list<Product_Rate_Plan_Charge_Tier__c> tiers = new list<Product_Rate_Plan_Charge_Tier__c>();
            tiers.add(new Product_Rate_Plan_Charge_Tier__c(Start_Unit__c = 1, End_Unit__c = 10, Unit_Cost_Price__c = 90, Unit_Price__c = 120, Product_Rate_Plan_Charge__c = tierCharge.Id));
            tiers.add(new Product_Rate_Plan_Charge_Tier__c(Start_Unit__c = 11, End_Unit__c = 20, Unit_Cost_Price__c = 90, Unit_Price__c = 110, Product_Rate_Plan_Charge__c = tierCharge.Id));
            tiers.add(new Product_Rate_Plan_Charge_Tier__c(Start_Unit__c = 21, End_Unit__c = 30, Unit_Cost_Price__c = 90, Unit_Price__c = 100, Product_Rate_Plan_Charge__c = tierCharge.Id));
            insert tiers;
            
            Product_Bundle__c productBundle = new Product_Bundle__c(Name = 'Devender', Bundle_Type__c = 'Line', Start_Date__c = system.today() - 1,Currency__c = listCurrencys.get(0).Id);
            ApexPages.StandardController controller = new ApexPages.StandardController(productBundle);
            ControllerProductBundle controllerProductBundleObj = new ControllerProductBundle(controller);
            
            controllerProductBundleObj.onChangeType();
            
            controllerProductBundleObj.step2();
            controllerProductBundleObj.step1();
            controllerProductBundleObj.step2();
            controllerProductBundleObj.cloneProductBundle();
            
            //Adding the product and charges
            system.currentPageReference().getParameters().put('productId',listProducts[0].Id);
            controllerProductBundleObj.addProductDetail();
            
            for(ControllerProductBundle.ClassProductRatePlan cprp : controllerProductBundleObj.listOfClassProductRatePlan) {
                cprp.isSelected = true;
            } 
            
            controllerProductBundleObj.saveAndCloseProductRPPopup();
            
            system.currentPageReference().getParameters().put('productId',listProducts[1].Id);
            controllerProductBundleObj.addProductDetail();
            
            for(ControllerProductBundle.ClassProductRatePlan cprp : controllerProductBundleObj.listOfClassProductRatePlan) {
                cprp.isSelected = true;
            } 
            
            controllerProductBundleObj.saveAndCloseProductRPPopup();
            
            // Removing the product
            system.currentPageReference().getParameters().put('productId',listProducts[1].Id);
            controllerProductBundleObj.removeProduct();
            
            map<string,list<ControllerProductBundle.ProductChargeWrapperCharges>> locMapProduct_Charges;
            list<ControllerProductBundle.ProductChargeWrapperCharges> listOfWrapperChargesLoc;
            
            for(string productId : controllerProductBundleObj.map_Product_mapRate_Charges.keySet()) {
                locMapProduct_Charges = controllerProductBundleObj.map_Product_mapRate_Charges.get(productId);
                    for(string productRatePlanId : locMapProduct_Charges.keySet()) {
                        listOfWrapperChargesLoc = locMapProduct_Charges.get(productRatePlanId);
                            for(ControllerProductBundle.ProductChargeWrapperCharges productChargeWrapperCharges : listOfWrapperChargesLoc) {
                                productChargeWrapperCharges.isSelectedCharge = true;
                            }
                    }
            }     
            controllerProductBundleObj.save();
            
            system.currentPageReference().getParameters().put('productId',listProducts[1].Id);
            controllerProductBundleObj.addProductDetail();
            
            for(ControllerProductBundle.ClassProductRatePlan cprp : controllerProductBundleObj.listOfClassProductRatePlan) {
                cprp.isSelected = true;
            } 
            
            controllerProductBundleObj.saveAndCloseProductRPPopup();
            
            ApexPages.StandardController controllerObj = new ApexPages.StandardController(controllerProductBundleObj.productBundle);
            ControllerProductBundle controllerProductBundleObjInst = new ControllerProductBundle(controllerObj);
            
            Product_Bundle__c productBundleObj = new Product_Bundle__c(Name = 'Devender', Bundle_Type__c = 'Bundle', Start_Date__c = system.today() - 1,Currency__c = listCurrencys.get(0).Id,
                                                                    Bundle_Price__c = 100, Is_Price_Editable__c = true, Is_Quantity_Editable__c = false,Price_Type__c = 'One Time',
                                                                    Quantity__c = 1.0, Unit_Of_Measurement__c = 'One', Pricing_Model__c = 'Default');
            insert productBundleObj; 
            // For Order
            
            Account account = ClassPopulateTestData.createAccount();
            
            list<Contact> contact = ClassPopulateTestData.createContacts(account);
            Job__c job1 = new Job__c(Name = 'Test Job',Account__c = account.Id,Billing_Contact__c = contact[0].Id,Shipping_Contact__c = contact[0].Id,Number_Of_Terms__c = 24,
                                     Start_Date__c = system.today(),Service_Activation_Date__c = system.today(),Service_End_Date__c = system.today().addMonths(10));
                                   
            ApexPages.Standardcontroller stdController = new Apexpages.Standardcontroller(job1);
            CreateJobController createJobController = new CreateJobController(stdController);
            
            //Move to the first page
            createJobController.step2();
            
            system.currentPageReference().getParameters().put('productId', controllerProductBundleObj.productBundle.Id);
            system.currentPageReference().getParameters().put('productName', controllerProductBundleObj.productBundle.name);
            createJobController.getRatePlansForProduct();
            
            system.currentPageReference().getParameters().put('productId', controllerProductBundleObj.productBundle.Id);
            system.currentPageReference().getParameters().put('productName', controllerProductBundleObj.productBundle.name);
            createJobController.getRatePlansForProduct();
            
            for(JobProductClass qpc : createJobController.jobClass.jobProducts)
            {
                system.currentPageReference().getParameters().put('jobrateplancounter', '0');
                system.currentPageReference().getParameters().put('jobRatePlanId', createJobController.jobRatePlanClass.jobrateplan.Id);
                system.currentPageReference().getParameters().put('productBundleId', string.valueOf(qpc.jobproduct.Bundle_SequenceNumber__c));
                createJobController.removeCharges();
                break;
            }
            
            system.currentPageReference().getParameters().put('productId', productBundleObj.Id);
            system.currentPageReference().getParameters().put('productName', productBundleObj.name);
            createJobController.getRatePlansForProduct();
            
            createJobController.saveJob();
            
            ApexPages.Standardcontroller stdControllerObj = new Apexpages.Standardcontroller(createJobController.job);
            CreateJobController createJobControllerObj = new CreateJobController(stdControllerObj);
            
            Quote__c quote = new Quote__c(Name = 'Test quote1',Account__c = account.Id, CurrencyL__c = listCurrencys.get(0).Id,Number_Of_Terms__c = 24,
                                       Start_Date__c = system.today(), Billing_Contact__c = contact[0].Id,Shipping_Contact__c = contact[0].Id);
                                       
            ApexPages.Standardcontroller controllerQuote = new Apexpages.Standardcontroller(quote);
            CreateQuoteController createQuoteController = new CreateQuoteController(controllerQuote);
            
            createQuoteController.step1();
            
            system.currentPageReference().getParameters().put('productId',productBundleObj.Id);
            system.currentPageReference().getParameters().put('productName',productBundleObj.name);
            createQuoteController.getRatePlansForProduct();    
            
            system.currentPageReference().getParameters().put('productId',productBundleObj.Id);
            system.currentPageReference().getParameters().put('productName',productBundleObj.name);
            createQuoteController.getRatePlansForProduct();   
            
            system.currentPageReference().getParameters().put('productId', controllerProductBundleObj.productBundle.Id);
            system.currentPageReference().getParameters().put('productName', controllerProductBundleObj.productBundle.name);
            createQuoteController.getRatePlansForProduct();
            
            for(QuoteProductClass qpc : createQuoteController.quoteClass.quoteProducts)
            {
                system.currentPageReference().getParameters().put('quoterateplancounter','0');
                system.currentPageReference().getParameters().put('quoteRatePlanId',CreateQuoteController.quoteRatePlanClass.quoterateplan.id);
                system.currentPageReference().getParameters().put('productBundleId', string.valueOf(qpc.quoteproduct.Bundle_SequenceNumber__c));
                CreateQuoteController.removeQuotes();  
                break;
            }    
             
            createQuoteController.saveQuote();
            
            ApexPages.Standardcontroller controllerQuote1 = new Apexpages.Standardcontroller(createJobController.job);
            CreateJobController createJobController1 = new CreateJobController(controllerQuote1);         
        }
    }