src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to Contact for Billing Contact</description>
        <inlineHelpText>This is the Contact to which the Invoice is sent by email</inlineHelpText>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Delivery Type like Print,Email or both.If it selected as email or both then the email is sent to the Billing Contact on invoice.</description>
        <label>Delivery Type</label>
        <picklist>
            <picklistValues>
                <fullName>Print</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email &amp; Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>When is the last date of invoice to be paid.</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is loop up to contact for Shipping Contact</description>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Shipping Contact)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Value__c</fullName>
        <description>Subtotal - Discount + VAT + Tax</description>
        <formula>Amount__c  -  Discount_Value__c +  VAT__c +  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Subtotal - Discount + VAT + Tax</inlineHelpText>
        <label>Total Invoice Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <description>Shows the total amount of VAT for all invoice lines that has been applied to the Invoice</description>
        <inlineHelpText>The total amount of VAT for all invoice lines</inlineHelpText>
        <label>VAT</label>
        <summarizedField>Invoice_Lines__c.VAT__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Invoice_Lines__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Name__c</fullName>
        <label>Line Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Line_Amount__c</fullName>
        <description>Subtotal - Discount + VAT + Tax</description>
        <formula>Line_Amount__c  -  Discount_Value__c +  VAT__c +  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Subtotal - Discount + VAT + Tax</inlineHelpText>
        <label>Total Line Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>LINE-{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/ClassInvoiceGenerator.cls
public with sharing class ClassInvoiceGenerator {

        public Invoice__c invoice { get; set; }
        public String sShippingContact { get; set; }
        public String sBillingContact { get; set; }

        list<Invoice_Lines__c> listInvoiceLines = new list<Invoice_Lines__c>();
        String sInvoiceID = System.currentPageReference().getParameters().get('ID');

        public ClassInvoiceGenerator() {
            if(sInvoiceID != null) {
                invoice = [SELECT Name, Invoice_Date__c, Due_Date__c, CurrencyL__r.Name ,Billing_Contact__c ,VAT__c, Total_Invoice_Value__c ,Delivery_Type__c,
                           Shipping_Contact__r.MailingStreet,Shipping_Contact__r.MailingCity, Shipping_Contact__r.MailingCountry ,Shipping_Contact__r.MailingPostalCode,Shipping_Contact__r.MailingState,
                           Billing_Contact__r.MailingStreet,Billing_Contact__r.MailingCity, Billing_Contact__r.MailingCountry ,Billing_Contact__r.MailingPostalCode,Billing_Contact__r.MailingState      
                           FROM Invoice__c
                           WHERE id =: sInvoiceID];
                sShippingContact = invoice.Shipping_Contact__r.MailingStreet + '  '
                + invoice.Shipping_Contact__r.MailingCity + '  '
                + invoice.Shipping_Contact__r.MailingState + ' '
                + invoice.Shipping_Contact__r.MailingCountry + '  '
                + invoice.Shipping_Contact__r.MailingPostalCode;

                sBillingContact = invoice.Billing_Contact__r.MailingStreet + ' ' 
                + invoice.Billing_Contact__r.MailingCity + ' '
                + invoice.Billing_Contact__r.MailingState + ' '
                + invoice.Billing_Contact__r.MailingCountry + ' '
                + invoice.Billing_Contact__r.MailingPostalCode;
            }
        }               

        public List<Invoice_Lines__c> getListInvoiceLines() {
            listInvoiceLines = [SELECT VAT__c, Unit_Price__c, Total_Line_Amount__c, Quantity__c, Line_Name__c, Id 
                                FROM Invoice_Lines__c 
                                WHERE Invoice__c =: sInvoiceID];
            return  listInvoiceLines;               
        }
    }