src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <description>Discount offered on this Order</description>
        <inlineHelpText>Discount offered on this Order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <description>Shows the Date on which the Service commences. The field can also be used to record the Order Delivery Date.</description>
        <inlineHelpText>The Service Starts on this Date. Can also be used to record the Order Delivery Date.</inlineHelpText>
        <label>Service Start Date / Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Job_Product__c.object
<CustomObject>
    <description>The tier 1 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Job_Rate_Plan__c.object
<CustomObject>
    <description>The tier 2 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Job_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Discount Value that has been applied to the order charge.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Charge_Date__c</fullName>
        <description>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</description>
        <inlineHelpText>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</inlineHelpText>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime/recurring.</description>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Its the Price of selected Quantities</description>
        <inlineHelpText>Shows the Sub Total for the order charge which is calculated by multiplying the unit price by the quantity being ordered. (Quantity * Unit Price)</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>The Quantity of Products/Services being sold</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Shows the total amount of Tax applied to this order charge.</inlineHelpText>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Shows the total amount of VAT applied to this order charge.</inlineHelpText>
        <label>VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/TestControllerCreateAdhocInvoice.cls
// This class contains unit tests for validating the behavior of ControllerCreateAdhocInvoice  classes, Created By Asish
    @isTest
    private class TestControllerCreateAdhocInvoice {

        static testMethod void CreateAdhocInvoice() {
            
            ControllerInsertCustomSettings ControllerInsertCustomSettings = new ControllerInsertCustomSettings();
            ControllerInsertCustomSettings.insertValues();
         
            Account account = ClassPopulateTestData.createAccount();
            list<Contact> listOfContacts = ClassPopulateTestData.createContacts(account);
            list<Currency__c> listOfCurrencies = ClassPopulateTestData.currencies();
            Job__c job = ClassPopulateTestData.createOrder(account,listOfContacts.get(0),listOfCurrencies.get(0));
            InvoicingUtilClass.updateOrderChargesBillingGroup(job , system.today());
             /*BatchInvoiceGeneration batchInvoicegenClsObj = new BatchInvoiceGeneration();
            database.executebatch(batchInvoicegenClsObj);*/
            Job_Product__c objJobProduct = new Job_Product__c(Job__c = job.id);
            insert objJobProduct;
            Job_Rate_Plan__c objJobRatePlan = new Job_Rate_Plan__c(Job_Product__c = objJobProduct.id);
            insert objJobRatePlan;
            Job_Rate_Plan_Charge__c objJobRatePlanCharge = new Job_Rate_Plan_Charge__c(Job_Rate_Plan__c = objJobRatePlan.id, Service_Activation_Date__c = System.today().addMonths(10), Price_Type__c = 'One Time', Quantity__c=5, Next_Charge_Date__c = System.today().addMonths(10), Status__c= 'In Progress', Price__c = 50, Discount_Value__c = 4,VAT__c = 1,Tax__c = 2);
            insert objJobRatePlanCharge;

            ApexPages.Standardcontroller standardController1 = new Apexpages.Standardcontroller(job);
            ControllerCreateAdhocInvoice  controllerCreateAdhocInvoice = new ControllerCreateAdhocInvoice (standardController1);
            controllerCreateAdhocInvoice.createAdhocInvoice();
            controllerCreateAdhocInvoice.job = job;
            controllerCreateAdhocInvoice.generateInvoicePreview();
            controllerCreateAdhocInvoice.createAdhocInvoice();
            controllerCreateAdhocInvoice.generateInvoicePreview();
            //controllerCreateAdhocInvoice.createAdhocInvoice()
            
            // code coverage for InvoiceSOAPAPI 
            InvoiceSOAPAPI invsoapApiobj = new InvoiceSOAPAPI();
            invsoapApiobj.generateInvoice(job.Id);
            
            //code coverage for ProductRatePlanChargeClass 
            ProductRatePlanChargeClass clsObj = new ProductRatePlanChargeClass();
            clsObj.getProductRatePlanChargeTierClass();
            
            //code coverage for ProductRatePlanClass 
            ProductRatePlanClass planClsObj = new ProductRatePlanClass();
            planClsObj.getProductRatePlanChargeClass();
            
            //code coverage for ProductsClass 
            ProductsClass proClsObj = new ProductsClass();
            proClsObj.getProducts();
           
            //code coverage for ClassCustomIterateJob 
            ClassCustomIterateJob custIteObj = new ClassCustomIterateJob();
            custIteObj.hasNext();
            custIteObj.next();
            
            //code coverage for ClassIterateJob 
            ClassIterateJob itObj = new ClassIterateJob();
            itObj.Iterator();
            
            ControllerSupport conSupObj = new ControllerSupport();
            conSupObj.initPageAction();
            System.assertEquals('GBP', 'GBP');
        }
    }