src- Version 4.19/objects/Currency__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the different types of Currencies like GBP, USD etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Job</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyL__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Todays_MRR__c</fullName>
        <description>This is the Monthly Recurring Revenue calculated on a schedule. This considers the recurring charges that are active today based on the Service Activation Date and Service End Date at the line level. Plz refer the help doc on how to schedule this.</description>
        <inlineHelpText>This is the Monthly Recurring Revenue calculated on a schedule. This considers the recurring charges that are active today based on the Service Activation Date and Service End Date at the line level. Plz refer the help doc on how to schedule this.</inlineHelpText>
        <label>Today&apos;s MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Todays_MRR_with_Tax__c</fullName>
        <description>This is the Monthly Recurring Revenue with Tax calculated on a schedule. This considers the recurring charges that are active today based on the Service Activation Date and Service End Date at the line level. Plz refer the help doc on how to schedule this.</description>
        <inlineHelpText>This is the Monthly Recurring Revenue + Tax calculated on a schedule. This considers the recurring charges that are active today based on the Service Activation Date and Service End Date at the line level. Plz refer the help doc on how to schedule this.</inlineHelpText>
        <label>Today&apos;s MRR with Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/RunSchedulerBatchJobs.cls
/*
		* This scheduler class is created for InvoiceIt batch jobs object, 
		* This is used for invoking batches one after one and maintains records in BatchJobs object
		* For More Information refer this Ticket : INVOICEIT-399
		*/
		global with sharing class RunSchedulerBatchJobs implements Schedulable {
		     global void execute(SchedulableContext context) {
		        string query = 'SELECT Account__c, CurrencyL__c, CurrencyL__r.Name, Todays_MRR__c, Todays_MRR_With_Tax__c FROM Job__c '; 
		        BatchForCalculatingMRR batch = new BatchForCalculatingMRR(query,true);
		        ID batchprocessid = Database.executeBatch(batch, 10);
		     }
		}