src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it checked means Email has been sent to the customer.</description>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Run_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship to the Invoice Run.Invoice is child of  Invoice Run.
This field tells from which Invoice Run the Invoice is generated.</description>
        <label>Invoice Run (Created By)</label>
        <referenceTo>Invoice_Run__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice_Run__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the details of how many Invoices generated,how many Accounts processed &amp; Credit Notes generated.</description>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Invoice Run</label>
    <nameField>
        <label>Invoice Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/BatchForEmailingInvoices.cls
global with sharing class BatchForEmailingInvoices implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
      global String query;
      global Id invoiceRunId;
      global String errorLog = '';
      
      global BatchForEmailingInvoices (Id invoiceRunId){
           //this.query = query;
           this.invoiceRunId= invoiceRunId;
          
       }
       
       global Database.QueryLocator start(Database.BatchableContext BC) {
           String query = 'SELECT Id,Name,Email_Sent__c FROM Invoice__c '
                          + 'WHERE Invoice_Run_Created_By__c =\''+ String.escapeSingleQuotes(invoiceRunId) + '\' '
                          + 'AND Email_Sent__c = false' ;
           return Database.getQueryLocator(query);
       }
       
        global void execute(Database.BatchableContext BC, list<sObject> scope) {
          for(sObject sObj : scope) {
              Invoice__c invoice = (Invoice__c) sObj;  
              try {
                  Messaging.reserveSingleEmailCapacity(1);
                  String sMessage = ClassWebServiceEmailing.sendInvoice(invoice.Id);
                  if(sMessage.Contains('Exception') || sMessage.Contains('Error')) {
                    errorLog = errorLog + sMessage;   
                    errorLog += ' Invoice Id : ' + invoice.Id + '\n';
                    errorLog += ' Invoice Name : ' + invoice.Name + '\n';
                  }
                  else {
                      invoice.Email_Sent__c = true;
                      update invoice;
                  }   
                 
              }
               catch(Exception ex) {
                  errorLog +=  ex.getTypeName() + ':' + ex.getMessage() + ':'  + ex.getLineNumber() + ':' + ex.getStackTraceString() + '\n';
                  errorLog += ' Invoice Id : ' + invoice.Id + '\n';
                  errorLog += ' Invoice Name : ' + invoice.Name + '\n';
               }  
          }
        }
        
        global void finish(Database.BatchableContext BC) {
            AsyncApexJob aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors 
                                FROM AsyncApexJob 
                                WHERE ID =: BC.getJobId()];
            
            list<Invoice_Run__c> listInvoiceRun = [Select id,Exception_Log__c  from Invoice_Run__c where id =:invoiceRunId];
            list<Invoice__c> listInvoices1 = [Select id,Name,Email_Sent__c  
                                             from Invoice__c 
                                             where Invoice_Run_Created_By__c =:invoiceRunId
                                             AND Email_Sent__c = false];
            if(errorLog != '' && errorLog.Length() > 0 && listInvoiceRun != null && !listInvoiceRun.isEmpty()) {
                if(errorLog.Length() < 32768) {
                     if(listInvoiceRun.get(0).Exception_Log__c != null) {
                        listInvoiceRun.get(0).Exception_Log__c = listInvoiceRun.get(0).Exception_Log__c + errorLog;           
                     }
                     else {
                        listInvoiceRun.get(0).Exception_Log__c = errorLog;    
                     }
                 } else {
                      Attachment attachment = new Attachment();
                      attachment.Body = Blob.valueOf(errorLog);
                      attachment.Name = 'ErrorLogForEmails.txt';
                      attachment.ParentId = invoiceRunId; 
                      insert attachment;  
                      
                      String errorStatement = '  Error log for Emails is attached as an attachment, you can find the attachment in related list';
                      if(listInvoiceRun.get(0).Exception_Log__c != null) {
                          listInvoiceRun.get(0).Exception_Log__c = listInvoiceRun.get(0).Exception_Log__c + errorStatement;           
                      }
                  }
               
              update listInvoiceRun;  
              
              String sUserId = Userinfo.getUserId();
              String sEmailId = Userinfo.getUserEmail();
              
              Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
              if(sEmailId != null) {
                  email.setSaveAsActivity(false);
                  email.setTargetObjectId(sUserId);
                  String subject='Error While sending Invoices';
                  String body='The invoices sent to the customers are not succesfully sent. Please check your Exception log'; 
                  email.setHtmlBody(body); 
                  email.setSubject(subject);
                  
                  // Sends the email
                  Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
              }
            }
            else if(aaj.TotalJobItems > 0 && (listInvoices1 == null || listInvoices1.isEmpty())){
                
                String sUserId = Userinfo.getUserId();
                String sEmailId = Userinfo.getUserEmail();
              
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
                if(sEmailId != null) {
                   email.setSaveAsActivity(false);
                   email.setTargetObjectId(sUserId);
                   String subject='Invoices sent Successfully';
                   String body='The invoices sent to the customers are succesfully sent.'; 
                   email.setHtmlBody(body); 
                   email.setSubject(subject);
                  
                  // Sends the email
                   Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
               }  
              
            }
            else if(aaj.TotalJobItems == 0){
                String sUserId = Userinfo.getUserId();
                String sEmailId = Userinfo.getUserEmail();
              
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
                if(sEmailId != null) {
                   email.setSaveAsActivity(false);
                   email.setTargetObjectId(sUserId);
                   String subject='No Invoices Sent';
                   String body='There are no invoices in the Queue to be sent to the customer.'; 
                   email.setHtmlBody(body); 
                   email.setSubject(subject);
                  
                  // Sends the email
                   Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
               }  
                  
              
            }
        }  

  }