src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/BatchCancelInvoices.cls
global with sharing class BatchCancelInvoices implements Database.Batchable<sObject>, Database.Stateful{
    global String query;
    global set<id> setOfInvoicesId = new set<id>();

    global BatchCancelInvoices(set<id> setOfInvoicesId){
      this.setOfInvoicesId = setOfInvoicesId;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'SELECT Name FROM Invoice__c WHERE ID IN: setOfInvoicesId';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,list<Invoice__c> scope){
    try{
        ControllerCancelInvoice.isButtonClicked = true; 
        Invoice__c inv = new Invoice__c(id=scope[0].id,Invoice_Status__c ='Cancelled');
        update inv;
    }catch(Exception ex){
    }
    }    
    global void finish(Database.BatchableContext BC){
    }
}