src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Lines__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Lines__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Run_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship to the Invoice Run.Invoice is child of  Invoice Run.
This field tells from which Invoice Run the Invoice is generated.</description>
        <label>Invoice Run (Created By)</label>
        <referenceTo>Invoice_Run__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_State__c</fullName>
        <label>Invoice State</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Proforma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Invoice_Run__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the details of how many Invoices generated,how many Accounts processed &amp; Credit Notes generated.</description>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice Run</label>
    <nameField>
        <label>Invoice Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/CancelInvoices.cls
public  with sharing class CancelInvoices {
        private static final Integer PAGE_SIZE =100;    
        Invoice_Run__c invoiceRun ; 
        public String invoiceRunName{get;set;}
        Invoice_Run__c invoiceRunRecord;       
        public Integer page{get;set;}
        public Integer totalRecords{get;set;}
        public Integer totalPages{get;set;}
        public Integer startIdx{get;set;}
        public Integer endIdx{get;set;}
        public List<InvoiceWrapper> listinvoice{get;set;}
        public CancelInvoices(ApexPages.StandardController controller)
        {
            invoiceRun = (Invoice_Run__c) controller.getRecord(); 
            invoiceRunRecord = [SELECT Id,Name FROM Invoice_Run__c WHERE Id =:invoiceRun.id]; 
            invoiceRunName = invoiceRunRecord.Name; 
            this.listinvoice = new List<InvoiceWrapper>();
            this.page = 1;
            getInvoices();
       
        }   
        public Pagereference invoiceSelected(){    
            set<id> setOfInvoice = new set<id>();
             for(InvoiceWrapper invoiceWra :  listinvoice){
                if(invoiceWra.isSelected){ 
                    setOfInvoice.add(invoiceWra.invoices.id);   
                                
                }            
            }        
            if(setOfInvoice.size()>0){
                BatchCancelInvoices b = new BatchCancelInvoices(setOfInvoice);
                database.executebatch(b,1);
            }else{
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.TherearenoInvoiceselected));            
            }
            return new PageReference('/' + invoiceRun.id);        
        } 
        Public Pagereference allInvoice(){
        
                    
            map<Id, Invoice__c> mapOfInvoices = new map<Id, Invoice__c>([SELECT Id,Invoice_Run_Created_By__c,Invoice_State__c,Invoice_Status__c,Name,Amount__c,Account__r.Name,Invoice_Date__c FROM Invoice__c  WHERE Invoice_Status__c != 'Cancelled' AND Invoice_Status__c != 'Posted' AND Invoice_Run_Created_By__c=:invoiceRun.ID ORDER BY Name]);
           
            if(mapOfInvoices.size()>0){    
                        
                BatchCancelInvoices b = new BatchCancelInvoices(mapOfInvoices.keyset());
                database.executebatch(b,1);
            }else{             
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, system.Label.ThereAreNoInvoicesToDisplay));
            }
            return new PageReference('/' + invoiceRun.id);  
        }
        public void doNext(){
            
            if(getHasNext()){
                this.page++;
                getInvoices();
            }
     
        }
        public Boolean getHasNext(){
            if(this.page<this.totalPages){
                return true;
            }
            else{
                return false;
            }
        }
        public void doPrevious(){
            
            if(getHasPrevious()){
                this.page--;
                getInvoices();
            }
    }
          public Boolean getHasPrevious(){
            if(this.page>1){
                return true;
            }
            else{
                return false;
            }
        } 
        public List<InvoiceWrapper> getInvoices(){
            this.startIdx = (this.page-1)*PAGE_SIZE;
            this.endIdx = this.page*PAGE_SIZE;
            if(listinvoice!=null){
              List<InvoiceWrapper> listinvoice=new List<InvoiceWrapper>();
                this.totalRecords = 0;
        
                this.listinvoice.clear();
                for(Invoice__c invoice : [SELECT Id,Invoice_Run_Created_By__c,Invoice_State__c,Invoice_Status__c,Name,Amount__c,Account__r.Name,Invoice_Date__c FROM Invoice__c  WHERE Invoice_Status__c != 'Cancelled' AND Invoice_Status__c != 'Posted' AND Invoice_Run_Created_By__c=:invoiceRun.ID]){
                if(this.totalRecords>=this.startIdx && this.totalRecords<this.endIdx){  
                InvoiceWrapper invwrap=new InvoiceWrapper(invoice , false);      
                this.listinvoice.add(invwrap );
                }
                this.totalRecords++;
         }
            Decimal pages = Decimal.valueOf(this.totalRecords);
            pages = pages.divide(Decimal.valueOf(PAGE_SIZE), 2);
            this.totalPages = (Integer)pages.round(System.RoundingMode.CEILING);
          }  
            this.startIdx++;
            if(this.endIdx>this.totalRecords){
                this.endIdx = this.totalRecords;
            }        
           
            return listinvoice;
        }
        public with sharing class InvoiceWrapper{
            public Invoice__c invoices{get;set;}
            public Boolean IsSelected{get;set;}
            public InvoiceWrapper( Invoice__c invoices,  Boolean IsSelected){
            this.invoices=invoices;
            this.IsSelected=IsSelected;
            }
        }    
    }