src- Version 4.19/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it checked means Email has been sent to the customer.</description>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerSendInvoice.cls
public with sharing class ControllerSendInvoice {

        public Invoice__c invoice {set;get;}
        public boolean bDisplayNoteMessage {set;get;}
        
        public ControllerSendInvoice(ApexPages.StandardController stdController) {
            invoice = (Invoice__c) stdController.getRecord();
            this.invoice = [select id,Email_Sent__c from Invoice__c where id =:invoice.id];
        }
        
        public PageReference emailInvoice() {
            try{
                String s ='';
                if(!invoice.Email_Sent__c) {
                    String sMessage = ClassWebServiceEmailing.sendInvoice(invoice.Id);
                    bDisplayNoteMessage = true;
                    if(sMessage.Contains('Exception') || sMessage.Contains('Error')) {
                        s = sMessage ; 
                    }
                    else {
                        invoice.Email_Sent__c = true;
                        update invoice;
                        s = System.Label.LabelEmailSent;
                    }       
                }
                else {
                      s = System.Label.Email_is_already_sent;
                }
                
                Apexpages.Message message = new Apexpages.Message(ApexPages.Severity.INFO,s);
                Apexpages.addMessage(message);
            }
            catch(Exception ex) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.ExceptionMessage + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
                Apexpages.addMessage(errorMessage);
            }
            return null;
        }
        
        public PageReference backToInvoice() {
            return new PageReference('/' + invoice.Id);
        }

    }