src- Version 4.19/objects/Invoice_RunScheduler__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Holds information about scheduler.When it is run to generate invoices.</description>
    <fields>
        <fullName>Invoice_Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invoice Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Schedulers</relationshipLabel>
        <relationshipName>Invoice_Run_Schedulers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</description>
        <inlineHelpText>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</inlineHelpText>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Day_Of_Month__c</fullName>
        <description>This is the day of the month that appears on the Invoice as the Invoice Date.</description>
        <inlineHelpText>This is the day of the month that appears on the Invoice as the Invoice Date.</inlineHelpText>
        <label>Invoice Day Of Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Day_of_week__c</fullName>
        <description>Invoice Day of Week</description>
        <inlineHelpText>Invoice Day of Week like 1 for sunday</inlineHelpText>
        <label>Invoice Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Apex Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_date_and_time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</description>
        <inlineHelpText>If you use Invoice Date as 15mar &amp; Target Date as 30mar, the billing will run on 15mar and the charges will be calculated up to 30mar.</inlineHelpText>
        <label>Target Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Day_Of_Month__c</fullName>
        <description>This is the &quot;as of&quot; billing date. If you set the Target Date as 20th of the month, the services will be billed as of that date.</description>
        <inlineHelpText>This is the &quot;as of&quot; billing date. If you set the Target Date as 20th of the month, the services will be billed as of that date.</inlineHelpText>
        <label>Target Day Of Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Day_of_Week__c</fullName>
        <description>Target Day of week</description>
        <inlineHelpText>Target Day of week like 1 for sunday</inlineHelpText>
        <label>Target Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</description>
        <inlineHelpText>Type of Schedule.
Once - Billing will be done only one time.
Daily  - Billing will be repeated continuously daily and so on</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Once</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Scheduler</label>
    <nameField>
        <label>Invoice Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ControllerForScheduling.cls
public with sharing class ControllerForScheduling {

        public Invoice_RunScheduler__c invoiceRunScheduler {get; set;}
        public Boolean isEditMode {get; set;} 
        public string str {get; set;} 
        public ControllerForScheduling(ApexPages.StandardController stdController) {
            this.invoiceRunScheduler = (Invoice_RunScheduler__c)stdController.getRecord();

            if(invoiceRunScheduler.Id != null) {
                invoiceRunScheduler = CommonUtilClass.getinvoiceRunScheduler(invoiceRunScheduler.Id);   
                isEditMode = true;
            }
            else {
                invoiceRunScheduler.Type__c = System.Label.OptionOnce;
            }
        }

        public PageReference onChangeOfType() {
            if(invoiceRunScheduler.Type__c == System.Label.OptionDaily) {
                invoiceRunScheduler.Start_date_and_time__c = system.Now();
                invoiceRunScheduler.Invoice_Date__c = invoiceRunScheduler.Start_date_and_time__c.Date();
                invoiceRunScheduler.Target_Date__c = invoiceRunScheduler.Start_date_and_time__c.Date();
                Apexpages.Message infoMessage = new Apexpages.Message(ApexPages.Severity.INFO,System.Label.DailyDateMessage);
                Apexpages.addMessage(infoMessage);
            } 
            return null;
        }

        public void onChangeStartDate() {
            if(invoiceRunScheduler.Type__c == System.Label.OptionDaily) {
                invoiceRunScheduler.Invoice_Date__c = invoiceRunScheduler.Start_date_and_time__c.Date();
                invoiceRunScheduler.Target_Date__c = invoiceRunScheduler.Start_date_and_time__c.Date();
            }
        }

        public PageReference saveInvoiceRunScheduler() {
            SavePoint sp;
            boolean isValidations = validations();
            if(!isValidations) {
                try {            
                    sp = DataBase.setSavePoint();
                    if(isEditMode == true) {
                        System.abortJob(invoiceRunScheduler.JobId__c);
                    }

                    String cronExpr = null;
                    String jobId  = null;           
                    Date startDate =  invoiceRunScheduler.Start_date_and_time__c.Date();
                    Integer hours =  invoiceRunScheduler.Start_date_and_time__c.Hour();
                    Integer minutes = invoiceRunScheduler.Start_date_and_time__c.Minute();            
                    String schedulerType  = invoiceRunScheduler.Type__c;
                    Integer seconds = 0;
                    Integer dayOfMonth = startDate.day();
                    Integer month =  startDate.month(); 
                    Integer year =  startDate.year();
                    Date weekStart = startDate.toStartofWeek();
                    Integer dayOfWeek = weekStart.daysBetween(startDate);
                    String space = ' ';
                    String questionMark = '?';
                    String repeat  = '*';
                    String comma = ',';
                    dayOfWeek = dayOfWeek + 2;
                    
                    if(System.Label.OptionOnce == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ space +month +space+ questionMark + space+  year;              
                    }  
                    else if(System.Label.OptionWeekly == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space + questionMark + space + repeat +space+ dayOfWeek + space+  repeat;
                    }
                    else if(System.Label.OptionMonthly == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ space +month + comma + repeat +space+  questionMark + space+  year + comma + repeat;
                    }
                    else if(System.Label.OptionDaily == schedulerType)
                    {
                        cronExpr = seconds+ space  + minutes+ space + hours + space +dayOfMonth+ comma +repeat + space + repeat +space+ questionMark  + space+  repeat;
                    }
                    
                    jobId = System.schedule(invoiceRunScheduler.name,cronExpr,new RunScheduler());
                    invoiceRunScheduler.JobId__c = jobId;
                    upsert invoiceRunScheduler;
                }
                catch(system.AsyncException asyncException) {
                    Database.rollback(sp);
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.INFO,asyncException.getMessage());
                    Apexpages.addMessage(errorMessage);  
                    return null;
                }
                catch(system.DmlException dmlException) {
                    Database.rollback(sp);
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,dmlException.getMessage());
                    Apexpages.addMessage(errorMessage);  
                    return null;
                }
                catch(system.Exception ex) {
                    Database.rollback(sp);
                    Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,ex.getMessage());
                    Apexpages.addMessage(errorMessage);  
                    return null;
                }
                return new PageReference('/' + invoiceRunScheduler.Id);
            }
            else {
                return null;
            }
        }

        public boolean validations() {
            if(invoiceRunScheduler.Start_date_and_time__c == null) {
                invoiceRunScheduler.Start_date_and_time__c.addError(system.Label.Thisfieldisrequired);  
                return true;    
            } else if(invoiceRunScheduler.Name == null) {
                invoiceRunScheduler.Name.addError(system.Label.Thisfieldisrequired);    
                return true;
            } else if(invoiceRunScheduler.Invoice_Currency__c == null) {
                invoiceRunScheduler.Invoice_Currency__c.addError(system.Label.Thisfieldisrequired); 
                return true;
            } else if(invoiceRunScheduler.Type__c == System.Label.OptionWeekly) {
                if(invoiceRunScheduler.Invoice_Day_of_week__c == null) { 
                    invoiceRunScheduler.Invoice_Day_of_week__c.addError(system.Label.Thisfieldisrequired);
                    return true;
                } else if(invoiceRunScheduler.Target_Day_of_week__c == null) {
                    invoiceRunScheduler.Target_Day_of_week__c.addError(system.Label.Thisfieldisrequired);
                    return true;
                }

            } else if(invoiceRunScheduler.Type__c == System.Label.OptionMonthly) {
                if(invoiceRunScheduler.Invoice_Day_Of_Month__c == null) { 
                    invoiceRunScheduler.Invoice_Day_Of_Month__c.addError(system.Label.Thisfieldisrequired);
                    return true;
                } else if(invoiceRunScheduler.Target_Day_Of_Month__c == null) {
                    invoiceRunScheduler.Target_Day_Of_Month__c.addError(system.Label.Thisfieldisrequired);
                    return true;
                }
            } else if(invoiceRunScheduler.Start_date_and_time__c <= system.Now()) {
                Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,system.Label.Startdatehaspassed);
                Apexpages.addMessage(errorMessage);
                return true;
            }
            
            /*
                    Modified By     : Devender M 03 Sept 2013 INVOICEIT-224/SUP-39
                    
                    INVOICEIT-374
            */
            if(invoiceRunScheduler.Start_date_and_time__c != null && invoiceRunScheduler.Type__c == System.Label.OptionDaily && invoiceRunScheduler.Start_date_and_time__c > system.now() + 1) {
                invoiceRunScheduler.Start_date_and_time__c.addError(system.Label.DailySchedulerError);  
                return true;    
            }
            
            return false;
        }
        
        //Please do not move this test method to anywhere because this code will also call RunScheduler
      
    }