src- Version 4.19/objects/Invoice_RunScheduler__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Holds information about scheduler.When it is run to generate invoices.</description>
    <fields>
        <fullName>JobId__c</fullName>
        <label>Apex Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Invoice Scheduler</label>
    <nameField>
        <label>Invoice Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassAfterOnInvoiceScheduler.cls
public with sharing class ClassAfterOnInvoiceScheduler {
    /*
        Modified By     : Aish :4-4-2014  :INVOICEIT-301
        Comments        : If the Invoice scheduler record is deleted we need to abort the job in the backend
    */
    public void handleAfterOnInvoiceScheduler(map<id,Invoice_RunScheduler__c> newMap,map<id,Invoice_RunScheduler__c> oldMap) {
        for(Invoice_RunScheduler__c scheduler : oldMap.Values()) { 
            if(scheduler.JobId__c != null) { 
                System.abortJob(scheduler.JobId__c); 
            }
        }
    }
}