src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Job_Product__c.object
<CustomObject>
    <description>The tier 1 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Job_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Order Product Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Job_Rate_Plan__c.object
<CustomObject>
    <description>The tier 2 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Job_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <label>Order RatePlan Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>This holds the Sequence in which the charges are created and appears on the pdf  files</description>
        <inlineHelpText>This holds the Sequence in which the charges are created. Controls the order in which charges appear on Reports / Documents.</inlineHelpText>
        <label>Sequence No</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>The unit selling price of the order line</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge_Tier__c.object
<CustomObject>
    <fields>
        <fullName>End_Unit__c</fullName>
        <label>End Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Rate Plan Charge</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charge Tiers</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charge_Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Unit__c</fullName>
        <label>Start Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost_Price__c</fullName>
        <label>Unit Cost Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan Charge Tier</label>
    <nameField>
        <displayFormat>O-TIER-{0000}</displayFormat>
        <label>Tier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charge Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Stores the wide variety of products. To handle &quot;ANY&quot; product easily, the product catalog is formed of 3 tiers. This forms tier 1 of the product catalog.</description>
    <label>Invoice IT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/ClassOrderProductsInlineAJS.cls
global with sharing class ClassOrderProductsInlineAJS {

        public string sCharges {get; set;}
        public string sortingOrder{get; set;}
        public string sPrefix {get; set;}
        public ClassOrderProductsInlineAJS(ApexPages.StandardController controller) {
            Job__c orderObj = (Job__c)controller.getRecord();
            sCharges = getChargeFieldSetvalue(orderObj.Id);
            sPrefix = CommonUtilClass.getPrefix();
        }

        Global string getChargeFieldSetvalue(Id OrderId) {
            list<string> chargesFields = new list<string>();
            map<string,string> mapOfChargeFieldandLabel =  new map<string,string>();
            map<string,string> mapOfChargeFieldValues;
            list<sobject> sObj = new list<sobject>();
            list<Object> listofCharge = new list<Object>(); 
            JSONGenerator generator = JSON.createGenerator(true);

            if(OrderId != null){
                String query = 'SELECT ';
                String apiName = '';

                //Getting the parent fields from the field set i.e, OrderProduct
                for(Schema.FieldSetMember orderProductFieldSet : SObjectType.Job_Product__c.FieldSets.ProductFieldsInline.getFields()) {
                    query += 'Job_Rate_Plan__r.Job_Product__r.'+orderProductFieldSet.getFieldPath() + ', ';
                    mapOfChargeFieldandLabel.put('Job_Rate_Plan__r.Job_Product__r.'+orderProductFieldSet.getFieldPath(),orderProductFieldSet.getLabel());
                    chargesFields.add('Job_Rate_Plan__r.Job_Product__r.'+orderProductFieldSet.getFieldPath());
                }

                //Getting the child fields from the field set i.e, Charges
                for(Schema.FieldSetMember chargeFieldSet : SObjectType.Job_Rate_Plan_Charge__c.FieldSets.Order_Detail_Page.getFields()) {
                    query += chargeFieldSet.getFieldPath() + ', ';
                    mapOfChargeFieldandLabel.put(chargeFieldSet.getFieldPath(),chargeFieldSet.getLabel());
                    chargesFields.add(chargeFieldSet.getFieldPath());
                }
                chargesFields.add('Id');
                chargesFields.add('Job_Rate_Plan__r.Job_Product__r.Product__r.Name');
                mapOfChargeFieldandLabel.put('Id','Id');
                mapOfChargeFieldandLabel.put('Job_Rate_Plan__r.Job_Product__r.Product__r.Name','pName');
                if(query.contains('Sequence_No__c'))
                    query += 'Id,Job_Rate_Plan__r.Job_Product__r.Product__r.Name FROM Job_Rate_Plan_Charge__c WHERE Order__c=:OrderId ORDER BY  Job_Rate_Plan__r.Job_Product__r.SequenceNumber__c,Sequence_No__c ';
                else
                    query += 'Id,Sequence_No__c,Job_Rate_Plan__r.Job_Product__r.Product__r.Name FROM Job_Rate_Plan_Charge__c WHERE Order__c=:OrderId ORDER BY  Job_Rate_Plan__r.Job_Product__r.SequenceNumber__c,Sequence_No__c ';
                sObj = Database.query(query);

                generator.writeStartArray();
                for(sobject obj : sObj) {
                    generator.writeStartObject();   
                    for(string api : chargesFields) {
                        // If it contains the Job_Rate_Plan__r in the API that means it is the parent fields
                        if(api.contains('Job_Rate_Plan__r')) {
                            apiName = api.replace('Job_Rate_Plan__r.Job_Product__r.', '');
                            if(string.valueOf(obj.get('Sequence_No__c')) != null && string.valueOf(obj.get('Sequence_No__c')) == '1' && apiName.contains('Product__r') && string.valueOf(obj.getSobject('Job_Rate_Plan__r').getSobject('Job_Product__r').get('Product__c')) != null) {
                                generator.writeStringField(mapOfChargeFieldandLabel.get(api), string.valueOf(obj.getSobject('Job_Rate_Plan__r').getSobject('Job_Product__r').getSobject('Product__r').get('Name')));
                            } else if(!apiName.contains('Product__r') && string.valueOf(obj.get('Sequence_No__c')) != null && string.valueOf(obj.get('Sequence_No__c')) == '1' && string.valueOf(obj.getSobject('Job_Rate_Plan__r').getSobject('Job_Product__r').get(''+apiName)) != null) {
                                    generator.writeStringField(mapOfChargeFieldandLabel.get(api), string.valueOf(obj.getSobject('Job_Rate_Plan__r').getSobject('Job_Product__r').get(''+apiName)));
                            } else {
                                    generator.writeStringField(mapOfChargeFieldandLabel.get(api),'');
                            }      
                        } else {
                            if(string.valueOf(obj.get(api)) != null) 
                                generator.writeStringField(mapOfChargeFieldandLabel.get(api),string.valueOf(obj.get(api)));
                            else 
                                generator.writeStringField(mapOfChargeFieldandLabel.get(api),'');             
                        }
                    }
                    generator.writeEndObject();
                }
                generator.writeEndArray(); 
            }
            String jsonString = generator.getAsString();
            
            return jsonString;
        }

        @RemoteAction
        Global static list<Job_Rate_Plan_Charge_Tier__c> getChargeTiers(String sChargeId) {
            list<Job_Rate_Plan_Charge_Tier__c> listOfProductRatePlanChargeTier = new list<Job_Rate_Plan_Charge_Tier__c>();
            if(sChargeId != null && sChargeId != '') {
                    listOfProductRatePlanChargeTier = [SELECT End_Unit__c,Start_Unit__c,Unit_Cost_Price__c,Unit_Price__c,Name FROM Job_Rate_Plan_Charge_Tier__c WHERE Job_Rate_Plan_Charge__c =: sChargeId];    
            }
            return listOfProductRatePlanChargeTier;
        } 
    }