src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corresponding Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Orders created from this Quote</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewed_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewed From</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Orders (Renewed From)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Based on the status user will check the Quote is Active/Converted  or not</description>
        <inlineHelpText>This field is used to check the status for the Quote if it is Active/Converted/Cancelled/Expired
based on that the Quote will be generated.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/ClassQuoteEmailHandler.cls
/** Email services are automated processes that use Apex classes to process the contents, headers, and attachments of inbound email. */
    global with sharing class ClassQuoteEmailHandler implements Messaging.InboundEmailHandler {
        global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {       
            // Create an inboundEmailResult object for returning
            //the result of the Apex Email Service
            Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
            Messaging.SingleEmailMessage emailTobeSent = new Messaging.SingleEmailMessage();
            list<String> listEmailMembers = new list<String>();
            try {
                // Contact and Lead lists to hold all the updated records
                // Convert the subject line to lower case, so I can match on lower case            
                String sEmailSubject = email.subject;
                if(sEmailSubject != null){
                    integer iUpperIndex  = sEmailSubject.IndexOf('(');
                    integer iLowerIndex  = sEmailSubject.IndexOf(')');
                    sEmailSubject = sEmailSubject.substring(iUpperIndex + 1, iLowerIndex);
                }
                Quote__c quote = [SELECT (SELECT Id FROM Orders__r WHERE Status__c !=: CommonUtilClass.STATUS_CANCELLED) 
                                  FROM Quote__c 
                                  WHERE id =: sEmailSubject];
                if(quote.Orders__r.size() > 0) {
                    //means that the quote is already converted into order.Send an email saying that it is already converted
                    listEmailMembers.add(email.fromAddress);
                    emailTobeSent.setToAddresses(listEmailMembers);
                    emailTobeSent.setSubject(email.subject);
                    emailTobeSent.setHtmlBody(system.Label.Quoteisalreadyconverted);
                     if(!Test.isRunningTest()) {
                        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailTobeSent});   
                     }
                    return result;
                }
                else if(quote != null) {              
                    ApexPages.Standardcontroller controller = new Apexpages.Standardcontroller(quote);
                    createQuoteController createQuoteController = new CreateQuoteController(controller);
                    createQuoteController.convertQuote();
                    //means that the quote is converted into order.Send an email saying that it is converted
                    listEmailMembers.add(email.fromAddress);
                    emailTobeSent.setToAddresses(listEmailMembers);
                    emailTobeSent.setSubject(email.subject);
                    emailTobeSent.setHtmlBody(system.Label.Yourrequesthasbeenaccepted);
                    if(!Test.isRunningTest()) {
                        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailTobeSent});   
                    }
                    return result;       
                }
                // Return true and exit. True will confirm it is complete and no bounced email should be send the sender of the unsubscribe request.
                return result;
            }
            catch(Exception ex) {
                listEmailMembers.add(email.fromAddress);
                emailTobeSent.setToAddresses(listEmailMembers);
                emailTobeSent.setSubject(email.subject);
                emailTobeSent.setHtmlBody(system.Label.Wecannotprocessyourrequest);
                if(!Test.isRunningTest()) {
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailTobeSent});   
                }
                return null;
            }
        }
    }