src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Master_Order_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relate to the master charge when you have multiple accounts who are subscribed to the same usage based service and you wish to roll up the usages from Child Orders to Master Order. All those aggregated units are calculated based on pricing on Master Order</description>
        <inlineHelpText>Relate to the master charge when you have multiple accounts who are subscribed to the same usage based service and you wish to roll up the usages from Child Orders to Master Order. All those aggregated units are calculated based on pricing on Master Order</inlineHelpText>
        <label>Obsolete_Master Order Rate Plan Charge</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Child Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Master_Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Charge_Date__c</fullName>
        <description>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</description>
        <inlineHelpText>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</inlineHelpText>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Usage_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to the usage charge against the Master Order where the current usage units are rolled up to.</description>
        <inlineHelpText>Points to the usage charge against the Master Order where the current usage units are rolled up to.</inlineHelpText>
        <label>Master Usage</label>
        <referenceTo>Usage_Charge__c</referenceTo>
        <relationshipLabel>Child Usages</relationshipLabel>
        <relationshipName>MasterUsages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Rate Plan Charge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Rate_Plan_Charge__c.Order__c</field>
                <operation>equals</operation>
                <valueField>$Source.Order__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Charge_Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Un-billed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rolled-Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <displayFormat>USG-{000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/classes/ClassAfterOnUsageCharge.cls
public with sharing class ClassAfterOnUsageCharge {
        
        public void handleBeforeOnUsageCharge(list<Usage_Charge__c> newUsages, map<Id, Usage_Charge__c> newMap, map<Id, Usage_Charge__c> oldMap)
        {
            for(Usage_Charge__c usageCharge : newUsages) {
                
                if(usageCharge.Order_Rate_Plan_Charge__c != null) {
                    // Since ORPC is present, do nothing it goes in a standard way  
                } else {
                    if(usageCharge.Account__c != null) {
                        if(usageCharge.Order__c != null) {
                            // account is not null and order is not null, then pick up only the related order based on the UOM[ORPC Usage charges]
                        } else {
                            // account is not null and order is null, then pick up only All related orders present for the account based on the UOM[ORPC Usage charges]
                        }   
                    } else {
                        // account is null
                        if(usageCharge.Order__c != null) {
                            // account is null and order is not null, then pick up only the related order's ORPC Usage charges based on the UOM 
                        }
                    }
                }
            }       
        }
        
        public void handleAfterOnUsageCharge(map<Id, Usage_Charge__c> newMap, map<Id, Usage_Charge__c> oldMap)
        {   
            map<Id, Job_Rate_Plan_Charge__c> mapOfChargesToUpdate = new map<Id, Job_Rate_Plan_Charge__c>();
            
            Date usageEndDate;
            Id chargeId;
            list<Id> listOfChargeIds = new list<Id>();
            list<Usage_Charge__c> usageChargesToRollUp = new list<Usage_Charge__c>();
            map<Id,Usage_Charge__c> map_ChildUsageChargeId_usageChargesToInsertAgainstMasterOrderCharge = new map<Id,Usage_Charge__c>();
            
            for(Usage_Charge__c usageCharge : newMap.values()) {
                listOfChargeIds.add(usageCharge.Order_Rate_Plan_Charge__c);
            }
            //We need to check if the corresponding charge's next charge date is null
            //If it is then update that to the end date of the usage charge
            //Else update that to take the minimum of both dates
            
            Job_Rate_Plan_Charge__c[] charges = [   SELECT Id, Next_Charge_Date__c, Master_Order_Rate_Plan_Charge__c 
                                                    FROM Job_Rate_Plan_Charge__c
                                                    WHERE Id IN :listOfChargeIds];
            for(Job_Rate_Plan_Charge__c charge : charges){
                mapOfChargesToUpdate.put(charge.Id,charge);
            }
            
            for(Usage_Charge__c usageCharge : newMap.values()) {
                Job_Rate_Plan_Charge__c charge = mapOfChargesToUpdate.get(usageCharge.Order_Rate_Plan_Charge__c);
                
                //If there is charge has the master order charge field populated, then ignore that from the date update. 
                //We need to update the usage charges to Rolled-Up and insert the same usage charges against the master order charge record
                if(charge.Master_Order_Rate_Plan_Charge__c != null){
                    Usage_Charge__c newUsageCharge = usageCharge.clone(false,true);
                    newUsageCharge.Order_Rate_Plan_Charge__c = charge.Master_Order_Rate_Plan_Charge__c;
                    
                    map_ChildUsageChargeId_usageChargesToInsertAgainstMasterOrderCharge.put(usageCharge.Id, newUsageCharge);
                }else if( charge.Next_Charge_Date__c == null 
                    || charge.Next_Charge_Date__c > usageCharge.End_Date__c)
                {
                    charge.Next_Charge_Date__c = usageCharge.End_Date__c;       
                }
            }
            
            update mapOfChargesToUpdate.values();
            insert map_ChildUsageChargeId_usageChargesToInsertAgainstMasterOrderCharge.values();
            
            //Now that the master usage records are inserted, update the child usage records with that id
            for(Id childUsageId : map_ChildUsageChargeId_usageChargesToInsertAgainstMasterOrderCharge.keySet()){
                Usage_Charge__c usageCopy = new Usage_Charge__c(Id = childUsageId);
                Usage_Charge__c masterUsage = map_ChildUsageChargeId_usageChargesToInsertAgainstMasterOrderCharge.get(childUsageId);
                usageCopy.Status__c = CommonUtilClass.STATUS_ROLLED_UP;
                usageCopy.Master_Usage__c = masterUsage.Id;
                
                usageChargesToRollUp.add(usageCopy);
            }
            
            update usageChargesToRollUp;
        } 
    }