src- Version 4.19/objects/Job__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>Once the customer accepts the Quote it is converted into Order. Order is a confirmed sale by the customer.</description>
    <fields>
        <fullName>Minimum_Next_Charge_Date_For_Product__c</fullName>
        <label>Minimum Next Charge Date For Product</label>
        <type>Date</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Job_Product__c.object
<CustomObject>
    <description>The tier 1 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/objects/Job_Rate_Plan__c.object
<CustomObject>
    <description>The tier 2 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Job_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <description>The tier 3 of the product catalog linked to the Order.</description>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Charge_Date__c</fullName>
        <description>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</description>
        <inlineHelpText>This holds the Next Charge Date for this rate plan charge. This means this charge is included in the invoice only if the the Invoice Target Date is on or after this date.</inlineHelpText>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the Order record that the charge is related to - click to be taken directly to the Order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the name of the order charge.</inlineHelpText>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recalculate_Revenue_Forecasts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recalculate Revenue Forecasts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Revenue Recognition Rule</label>
        <referenceTo>Revenue_Recognition_Rule__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Revenue_Recognition_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>This forms tier 3 of the product catalog.</description>
    <fields>
        <fullName>Revenue_Recognition_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Revenue Recognition Rule</label>
        <referenceTo>Revenue_Recognition_Rule__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Revenue_Recognition_Rule__c.object
<CustomObject>
    <label>Revenue Recognition Rule</label>
    <nameField>
        <label>Revenue Recognition Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognition Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src- Version 4.19/classes/ClassAfterOnJobRatePlanCharges.cls
public with sharing class ClassAfterOnJobRatePlanCharges {
        
        /*
            Modified By     : Devender M 07 Jan 2014 INVOICEIT-297
            Comments        : Look from Order rate plan charge to Order and Quote rate plan charge to Quote.
        */

        public void handleBeforeOnJobCharge() {
            set<Id> setOforderRatePlanIds = new set<Id>();
            Job_Rate_Plan_Charge__c newJobRatePlanCharge;
            list<Job_Rate_Plan_Charge__c> orderChargesToPopulate = new list<Job_Rate_Plan_Charge__c>();
            set<Id> setOfProductChargeIds = new set<Id>();
            map<Id, Product_Rate_Plan_Charge__c> map_ProductChargeId_ProductCharge = new map<Id, Product_Rate_Plan_Charge__c>();
            
            // we need to populate the QuoteId in Quote rate plan charge
            for(SObject orderChargeSobject : Trigger.new) {
                newJobRatePlanCharge = (Job_Rate_Plan_Charge__c) orderChargeSobject;
                if(trigger.isInsert) {
                    setOforderRatePlanIds.add(newJobRatePlanCharge.Job_Rate_Plan__c);
                    if(newJobRatePlanCharge.Product_Rate_Plan_Charge__c != null && newJobRatePlanCharge.Revenue_Recognition_Rule__c == null)
                        setOfProductChargeIds.add(newJobRatePlanCharge.Product_Rate_Plan_Charge__c);
                    orderChargesToPopulate.add(newJobRatePlanCharge);
                } else {
                    if(newJobRatePlanCharge.order__c == null) {
                        setOforderRatePlanIds.add(newJobRatePlanCharge.Job_Rate_Plan__c);   
                        orderChargesToPopulate.add(newJobRatePlanCharge);
                    }
                }
            }
            
            if(trigger.isInsert && !setOfProductChargeIds.isEmpty()) {
                map_ProductChargeId_ProductCharge = new  map<Id, Product_Rate_Plan_Charge__c>([SELECT Revenue_Recognition_Rule__c
                                                                                                 FROM Product_Rate_Plan_Charge__c
                                                                                                 WHERE Id IN: setOfProductChargeIds]);
            } 
            if(!setOforderRatePlanIds.isEmpty()) {
                map<Id, Job_Rate_Plan__c> map_OrderRatePlanId_OrderRatePlan = new map<Id, Job_Rate_Plan__c>([SELECT Job_Product__r.Job__c
                                                                                                             FROM Job_Rate_Plan__c
                                                                                                             WHERE Id IN: setOforderRatePlanIds]);
                
                
                                                                                                            
                // here we are populating the QuoteId in QRPC for only necessary ones. No need of iterating again the trigger.new
                for(Job_Rate_Plan_Charge__c jobCharge : orderChargesToPopulate) {
                    if(map_OrderRatePlanId_OrderRatePlan != null && map_OrderRatePlanId_OrderRatePlan.containskey(jobCharge.Job_Rate_Plan__c))
                        jobCharge.Order__c = map_OrderRatePlanId_OrderRatePlan.get(jobCharge.Job_Rate_Plan__c).Job_Product__r.Job__c;
                    if(trigger.isInsert && jobCharge.Product_Rate_Plan_Charge__c != null && jobCharge.Revenue_Recognition_Rule__c == null && map_ProductChargeId_ProductCharge.containskey(jobCharge.Product_Rate_Plan_Charge__c))
                        jobCharge.Revenue_Recognition_Rule__c = map_ProductChargeId_ProductCharge.get(jobCharge.Product_Rate_Plan_Charge__c).Revenue_Recognition_Rule__c;
                }
            }                                                                                                   
        }
        
        public void handleAfterUpdateOnJobCharge(){
            list<Job__c> listOfJobsToUpdate = new list<Job__c>();
            set<Id> setOfJobIds;
            list<AggregateResult> listOfAggregateResult;
            list<Job_Rate_Plan_Charge__c> listOfJobChargesOfInterest = new list<Job_Rate_Plan_Charge__c>();
            
            list<Id> listofChargeIds = new list<Id>();

            for(SObject s : Trigger.newMap.Values()) {
                Job_Rate_Plan_Charge__c newJobRatePlanCharge = (Job_Rate_Plan_Charge__c)s; 
                Job_Rate_Plan_Charge__c oldJobRatePlanCharge = (Job_Rate_Plan_Charge__c)Trigger.oldMap.get(newJobRatePlanCharge.Id);
                //charges intrested for Minimum_Next_Charge_Date_For_Product__c
                if(newJobRatePlanCharge.Next_Charge_Date__c != oldJobRatePlanCharge.Next_Charge_Date__c) 
                {
                    listOfJobChargesOfInterest.add(newJobRatePlanCharge);
                }

                // Modified by Dev M INVOICEIT-549 : Recalculate Revenue Forecasts when ever the check box is true
                 if(newJobRatePlanCharge.Recalculate_Revenue_Forecasts__c != oldJobRatePlanCharge.Recalculate_Revenue_Forecasts__c
                    && newJobRatePlanCharge.Recalculate_Revenue_Forecasts__c) 
                {
                    listofChargeIds.add(newJobRatePlanCharge.Id);
                } 
            }
            
                
            if(!listOfJobChargesOfInterest.isEmpty()) {
                setOfJobIds = new set<Id>();
                for(Job_Rate_Plan_Charge__c jobRatePlanCharge : [SELECT Job_Rate_Plan__r.Job_Product__r.Job__r.Id 
                                                                  FROM Job_Rate_Plan_Charge__c 
                                                                  WHERE Id IN: listOfJobChargesOfInterest]) 
                {
                    setOfJobIds.add(jobRatePlanCharge.Job_Rate_Plan__r.Job_Product__r.Job__r.Id);
                }
            
                listOfAggregateResult = [SELECT Job_Rate_Plan__r.Job_Product__r.Job__r.Id, min(Next_Charge_Date__c) minCharge
                                         FROM Job_Rate_Plan_Charge__c
                                         WHERE Job_Rate_Plan__r.Job_Product__r.Job__r.Id IN: setOfJobIds
                                         GROUP BY Job_Rate_Plan__r.Job_Product__r.Job__r.Id];
                
                for(AggregateResult aggResult : listOfAggregateResult) {
                    listOfJobsToUpdate.add(new Job__c(Id = (Id)aggResult.get('Id'), Minimum_Next_Charge_Date_For_Product__c = (Date)aggResult.get('minCharge')));
                }
                
                //update the jobs with the min next charge date
                if(!listOfJobsToUpdate.isEmpty()) {
                    update listOfJobsToUpdate;
                }   
            }

            // Here were are processing the records for Revenue Forecasts
             if(!listofChargeIds.isEmpty()) {
                RevenueTransactionsForOrderUtilClass.createRevenueForecastForOrderCharge(listofChargeIds);
            }
        }
    }