src- Version 4.19/objects/Quote__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>A Quote is a document that a vendor or service provider would give to a customer to describe specific goods and services that they may provide and its cost</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It tells the Parent Quote from which the Quote is cloned</description>
        <inlineHelpText>This field  will auto populates  when ever Quote is cloned.</inlineHelpText>
        <label>Parent Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Cloned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Metadata/objects/Quote_Product__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 1 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 2 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <label>Quote Product</label>
        <referenceTo>Quote_Product__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src- Version 4.19/objects/Quote_Rate_Plan_Charge__c.object
<CustomObject>
    <customHelpPage>support</customHelpPage>
    <description>The tier 3 of the product catalog linked to the Quote.</description>
    <fields>
        <fullName>Quote_Rate_Plan__c</fullName>
        <label>Quote Rate Plan</label>
        <referenceTo>Quote_Rate_Plan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charge</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Metadata/classes/ClassAfterOnQuoteRatePlanCharges.cls
public with sharing class ClassAfterOnQuoteRatePlanCharges { 
        /*  Modified By       : Devender M: 07 Jan 2014: INVOICEIT-297
            Comments        : Look from Order rate plan charge to Order and Quote rate plan charge to Quote.
        */
        public void handleBeforeOnQuoteCharge() {
            set<Id> setOfQuoteRatePlanIds = new set<Id>();
            Quote_Rate_Plan_Charge__c newQuoteRatePlanCharge;
            list<Quote_Rate_Plan_Charge__c> quoteChargesToPopulate = new list<Quote_Rate_Plan_Charge__c>(); 
            // we need to populate the QuoteId in Quote rate plan charge
            for(SObject quoteChargeSobject : Trigger.new) {
                newQuoteRatePlanCharge = (Quote_Rate_Plan_Charge__c) quoteChargeSobject;
                
                if(trigger.isInsert) {
                    setOfQuoteRatePlanIds.add(newQuoteRatePlanCharge.Quote_Rate_Plan__c);
                    quoteChargesToPopulate.add(newQuoteRatePlanCharge);
                } else {
                    if(newQuoteRatePlanCharge.Quote__c == null) {
                        setOfQuoteRatePlanIds.add(newQuoteRatePlanCharge.Quote_Rate_Plan__c);
                        quoteChargesToPopulate.add(newQuoteRatePlanCharge); 
                    }
                }
            }       
            if(!setOfQuoteRatePlanIds.isEmpty()) {
                map<Id, Quote_Rate_Plan__c> map_QuoteRatePlanId_QuoteRatePlan = new map<Id, Quote_Rate_Plan__c>([SELECT Quote_Product__r.Quote__c  
                                                                                                                 FROM Quote_Rate_Plan__c 
                                                                                                                 WHERE Id IN: setOfQuoteRatePlanIds]
                                                                                                                );        
                // here we are populating the QuoteId in QRPC for only necessary ones. No need of iterating again the trigger.new                                                                                               
                for(Quote_Rate_Plan_Charge__c quoteCharge : quoteChargesToPopulate) {
                    quoteCharge.Quote__c = map_QuoteRatePlanId_QuoteRatePlan.get(quoteCharge.Quote_Rate_Plan__c).Quote_Product__r.Quote__c;
                }   
            }
        }
    }